/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PodsRouteImport } from './routes/_pods'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard/index'
import { Route as DashboardAdminRouteImport } from './routes/_dashboard/admin'
import { Route as DashboardAdminIndexRouteImport } from './routes/_dashboard/admin/index'
import { Route as PodsPodsPublishedRouteImport } from './routes/_pods/pods/published'
import { Route as PodsPodsPublishRouteImport } from './routes/_pods/pods/publish'
import { Route as PodsPodsCreateRouteImport } from './routes/_pods/pods/create'
import { Route as PodsPodsBrowseRouteImport } from './routes/_pods/pods/browse'
import { Route as PodsPodsPodSlugRouteImport } from './routes/_pods/pods/$podSlug'
import { Route as DashboardManagerRequestsRouteImport } from './routes/_dashboard/manager/requests'
import { Route as DashboardAdminSdnRouteImport } from './routes/_dashboard/admin/sdn'
import { Route as DashboardAdminProxmoxSyncRouteImport } from './routes/_dashboard/admin/proxmox-sync'
import { Route as DashboardInventoryItemsItemIdRouteImport } from './routes/_dashboard/inventory/items/$itemId'
import { Route as DashboardAdminPrincipalsUsersRouteImport } from './routes/_dashboard/admin/principals/users'
import { Route as DashboardAdminPrincipalsGroupsRouteImport } from './routes/_dashboard/admin/principals/groups'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PodsRoute = PodsRouteImport.update({
  id: '/_pods',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminIndexRoute = DashboardAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const PodsPodsPublishedRoute = PodsPodsPublishedRouteImport.update({
  id: '/pods/published',
  path: '/pods/published',
  getParentRoute: () => PodsRoute,
} as any)
const PodsPodsPublishRoute = PodsPodsPublishRouteImport.update({
  id: '/pods/publish',
  path: '/pods/publish',
  getParentRoute: () => PodsRoute,
} as any)
const PodsPodsCreateRoute = PodsPodsCreateRouteImport.update({
  id: '/pods/create',
  path: '/pods/create',
  getParentRoute: () => PodsRoute,
} as any)
const PodsPodsBrowseRoute = PodsPodsBrowseRouteImport.update({
  id: '/pods/browse',
  path: '/pods/browse',
  getParentRoute: () => PodsRoute,
} as any)
const PodsPodsPodSlugRoute = PodsPodsPodSlugRouteImport.update({
  id: '/pods/$podSlug',
  path: '/pods/$podSlug',
  getParentRoute: () => PodsRoute,
} as any)
const DashboardManagerRequestsRoute =
  DashboardManagerRequestsRouteImport.update({
    id: '/manager/requests',
    path: '/manager/requests',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAdminSdnRoute = DashboardAdminSdnRouteImport.update({
  id: '/sdn',
  path: '/sdn',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminProxmoxSyncRoute =
  DashboardAdminProxmoxSyncRouteImport.update({
    id: '/proxmox-sync',
    path: '/proxmox-sync',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardInventoryItemsItemIdRoute =
  DashboardInventoryItemsItemIdRouteImport.update({
    id: '/inventory/items/$itemId',
    path: '/inventory/items/$itemId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAdminPrincipalsUsersRoute =
  DashboardAdminPrincipalsUsersRouteImport.update({
    id: '/principals/users',
    path: '/principals/users',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardAdminPrincipalsGroupsRoute =
  DashboardAdminPrincipalsGroupsRouteImport.update({
    id: '/principals/groups',
    path: '/principals/groups',
    getParentRoute: () => DashboardAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof DashboardIndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof DashboardAdminRouteWithChildren
  '/admin/proxmox-sync': typeof DashboardAdminProxmoxSyncRoute
  '/admin/sdn': typeof DashboardAdminSdnRoute
  '/manager/requests': typeof DashboardManagerRequestsRoute
  '/pods/$podSlug': typeof PodsPodsPodSlugRoute
  '/pods/browse': typeof PodsPodsBrowseRoute
  '/pods/create': typeof PodsPodsCreateRoute
  '/pods/publish': typeof PodsPodsPublishRoute
  '/pods/published': typeof PodsPodsPublishedRoute
  '/admin/': typeof DashboardAdminIndexRoute
  '/admin/principals/groups': typeof DashboardAdminPrincipalsGroupsRoute
  '/admin/principals/users': typeof DashboardAdminPrincipalsUsersRoute
  '/inventory/items/$itemId': typeof DashboardInventoryItemsItemIdRoute
}
export interface FileRoutesByTo {
  '/': typeof DashboardIndexRoute
  '/login': typeof LoginRoute
  '/admin/proxmox-sync': typeof DashboardAdminProxmoxSyncRoute
  '/admin/sdn': typeof DashboardAdminSdnRoute
  '/manager/requests': typeof DashboardManagerRequestsRoute
  '/pods/$podSlug': typeof PodsPodsPodSlugRoute
  '/pods/browse': typeof PodsPodsBrowseRoute
  '/pods/create': typeof PodsPodsCreateRoute
  '/pods/publish': typeof PodsPodsPublishRoute
  '/pods/published': typeof PodsPodsPublishedRoute
  '/admin': typeof DashboardAdminIndexRoute
  '/admin/principals/groups': typeof DashboardAdminPrincipalsGroupsRoute
  '/admin/principals/users': typeof DashboardAdminPrincipalsUsersRoute
  '/inventory/items/$itemId': typeof DashboardInventoryItemsItemIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteWithChildren
  '/_pods': typeof PodsRouteWithChildren
  '/login': typeof LoginRoute
  '/_dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/_dashboard/': typeof DashboardIndexRoute
  '/_dashboard/admin/proxmox-sync': typeof DashboardAdminProxmoxSyncRoute
  '/_dashboard/admin/sdn': typeof DashboardAdminSdnRoute
  '/_dashboard/manager/requests': typeof DashboardManagerRequestsRoute
  '/_pods/pods/$podSlug': typeof PodsPodsPodSlugRoute
  '/_pods/pods/browse': typeof PodsPodsBrowseRoute
  '/_pods/pods/create': typeof PodsPodsCreateRoute
  '/_pods/pods/publish': typeof PodsPodsPublishRoute
  '/_pods/pods/published': typeof PodsPodsPublishedRoute
  '/_dashboard/admin/': typeof DashboardAdminIndexRoute
  '/_dashboard/admin/principals/groups': typeof DashboardAdminPrincipalsGroupsRoute
  '/_dashboard/admin/principals/users': typeof DashboardAdminPrincipalsUsersRoute
  '/_dashboard/inventory/items/$itemId': typeof DashboardInventoryItemsItemIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/admin/proxmox-sync'
    | '/admin/sdn'
    | '/manager/requests'
    | '/pods/$podSlug'
    | '/pods/browse'
    | '/pods/create'
    | '/pods/publish'
    | '/pods/published'
    | '/admin/'
    | '/admin/principals/groups'
    | '/admin/principals/users'
    | '/inventory/items/$itemId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/proxmox-sync'
    | '/admin/sdn'
    | '/manager/requests'
    | '/pods/$podSlug'
    | '/pods/browse'
    | '/pods/create'
    | '/pods/publish'
    | '/pods/published'
    | '/admin'
    | '/admin/principals/groups'
    | '/admin/principals/users'
    | '/inventory/items/$itemId'
  id:
    | '__root__'
    | '/_dashboard'
    | '/_pods'
    | '/login'
    | '/_dashboard/admin'
    | '/_dashboard/'
    | '/_dashboard/admin/proxmox-sync'
    | '/_dashboard/admin/sdn'
    | '/_dashboard/manager/requests'
    | '/_pods/pods/$podSlug'
    | '/_pods/pods/browse'
    | '/_pods/pods/create'
    | '/_pods/pods/publish'
    | '/_pods/pods/published'
    | '/_dashboard/admin/'
    | '/_dashboard/admin/principals/groups'
    | '/_dashboard/admin/principals/users'
    | '/_dashboard/inventory/items/$itemId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren
  PodsRoute: typeof PodsRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pods': {
      id: '/_pods'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/admin': {
      id: '/_dashboard/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/admin/': {
      id: '/_dashboard/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof DashboardAdminIndexRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/_pods/pods/published': {
      id: '/_pods/pods/published'
      path: '/pods/published'
      fullPath: '/pods/published'
      preLoaderRoute: typeof PodsPodsPublishedRouteImport
      parentRoute: typeof PodsRoute
    }
    '/_pods/pods/publish': {
      id: '/_pods/pods/publish'
      path: '/pods/publish'
      fullPath: '/pods/publish'
      preLoaderRoute: typeof PodsPodsPublishRouteImport
      parentRoute: typeof PodsRoute
    }
    '/_pods/pods/create': {
      id: '/_pods/pods/create'
      path: '/pods/create'
      fullPath: '/pods/create'
      preLoaderRoute: typeof PodsPodsCreateRouteImport
      parentRoute: typeof PodsRoute
    }
    '/_pods/pods/browse': {
      id: '/_pods/pods/browse'
      path: '/pods/browse'
      fullPath: '/pods/browse'
      preLoaderRoute: typeof PodsPodsBrowseRouteImport
      parentRoute: typeof PodsRoute
    }
    '/_pods/pods/$podSlug': {
      id: '/_pods/pods/$podSlug'
      path: '/pods/$podSlug'
      fullPath: '/pods/$podSlug'
      preLoaderRoute: typeof PodsPodsPodSlugRouteImport
      parentRoute: typeof PodsRoute
    }
    '/_dashboard/manager/requests': {
      id: '/_dashboard/manager/requests'
      path: '/manager/requests'
      fullPath: '/manager/requests'
      preLoaderRoute: typeof DashboardManagerRequestsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/admin/sdn': {
      id: '/_dashboard/admin/sdn'
      path: '/sdn'
      fullPath: '/admin/sdn'
      preLoaderRoute: typeof DashboardAdminSdnRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/_dashboard/admin/proxmox-sync': {
      id: '/_dashboard/admin/proxmox-sync'
      path: '/proxmox-sync'
      fullPath: '/admin/proxmox-sync'
      preLoaderRoute: typeof DashboardAdminProxmoxSyncRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/_dashboard/inventory/items/$itemId': {
      id: '/_dashboard/inventory/items/$itemId'
      path: '/inventory/items/$itemId'
      fullPath: '/inventory/items/$itemId'
      preLoaderRoute: typeof DashboardInventoryItemsItemIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/admin/principals/users': {
      id: '/_dashboard/admin/principals/users'
      path: '/principals/users'
      fullPath: '/admin/principals/users'
      preLoaderRoute: typeof DashboardAdminPrincipalsUsersRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/_dashboard/admin/principals/groups': {
      id: '/_dashboard/admin/principals/groups'
      path: '/principals/groups'
      fullPath: '/admin/principals/groups'
      preLoaderRoute: typeof DashboardAdminPrincipalsGroupsRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
  }
}

interface DashboardAdminRouteChildren {
  DashboardAdminProxmoxSyncRoute: typeof DashboardAdminProxmoxSyncRoute
  DashboardAdminSdnRoute: typeof DashboardAdminSdnRoute
  DashboardAdminIndexRoute: typeof DashboardAdminIndexRoute
  DashboardAdminPrincipalsGroupsRoute: typeof DashboardAdminPrincipalsGroupsRoute
  DashboardAdminPrincipalsUsersRoute: typeof DashboardAdminPrincipalsUsersRoute
}

const DashboardAdminRouteChildren: DashboardAdminRouteChildren = {
  DashboardAdminProxmoxSyncRoute: DashboardAdminProxmoxSyncRoute,
  DashboardAdminSdnRoute: DashboardAdminSdnRoute,
  DashboardAdminIndexRoute: DashboardAdminIndexRoute,
  DashboardAdminPrincipalsGroupsRoute: DashboardAdminPrincipalsGroupsRoute,
  DashboardAdminPrincipalsUsersRoute: DashboardAdminPrincipalsUsersRoute,
}

const DashboardAdminRouteWithChildren = DashboardAdminRoute._addFileChildren(
  DashboardAdminRouteChildren,
)

interface DashboardRouteChildren {
  DashboardAdminRoute: typeof DashboardAdminRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardManagerRequestsRoute: typeof DashboardManagerRequestsRoute
  DashboardInventoryItemsItemIdRoute: typeof DashboardInventoryItemsItemIdRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAdminRoute: DashboardAdminRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardManagerRequestsRoute: DashboardManagerRequestsRoute,
  DashboardInventoryItemsItemIdRoute: DashboardInventoryItemsItemIdRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface PodsRouteChildren {
  PodsPodsPodSlugRoute: typeof PodsPodsPodSlugRoute
  PodsPodsBrowseRoute: typeof PodsPodsBrowseRoute
  PodsPodsCreateRoute: typeof PodsPodsCreateRoute
  PodsPodsPublishRoute: typeof PodsPodsPublishRoute
  PodsPodsPublishedRoute: typeof PodsPodsPublishedRoute
}

const PodsRouteChildren: PodsRouteChildren = {
  PodsPodsPodSlugRoute: PodsPodsPodSlugRoute,
  PodsPodsBrowseRoute: PodsPodsBrowseRoute,
  PodsPodsCreateRoute: PodsPodsCreateRoute,
  PodsPodsPublishRoute: PodsPodsPublishRoute,
  PodsPodsPublishedRoute: PodsPodsPublishedRoute,
}

const PodsRouteWithChildren = PodsRoute._addFileChildren(PodsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRouteWithChildren,
  PodsRoute: PodsRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
