/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard/index'
import { Route as DashboardUsersRouteImport } from './routes/_dashboard/users'
import { Route as DashboardSdnRouteImport } from './routes/_dashboard/sdn'
import { Route as DashboardGroupsRouteImport } from './routes/_dashboard/groups'
import { Route as DashboardVmItemIdRouteImport } from './routes/_dashboard/vm/$itemId'

const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUsersRoute = DashboardUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSdnRoute = DashboardSdnRouteImport.update({
  id: '/sdn',
  path: '/sdn',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGroupsRoute = DashboardGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardVmItemIdRoute = DashboardVmItemIdRouteImport.update({
  id: '/vm/$itemId',
  path: '/vm/$itemId',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof DashboardIndexRoute
  '/groups': typeof DashboardGroupsRoute
  '/sdn': typeof DashboardSdnRoute
  '/users': typeof DashboardUsersRoute
  '/vm/$itemId': typeof DashboardVmItemIdRoute
}
export interface FileRoutesByTo {
  '/groups': typeof DashboardGroupsRoute
  '/sdn': typeof DashboardSdnRoute
  '/users': typeof DashboardUsersRoute
  '/': typeof DashboardIndexRoute
  '/vm/$itemId': typeof DashboardVmItemIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteWithChildren
  '/_dashboard/groups': typeof DashboardGroupsRoute
  '/_dashboard/sdn': typeof DashboardSdnRoute
  '/_dashboard/users': typeof DashboardUsersRoute
  '/_dashboard/': typeof DashboardIndexRoute
  '/_dashboard/vm/$itemId': typeof DashboardVmItemIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/groups' | '/sdn' | '/users' | '/vm/$itemId'
  fileRoutesByTo: FileRoutesByTo
  to: '/groups' | '/sdn' | '/users' | '/' | '/vm/$itemId'
  id:
    | '__root__'
    | '/_dashboard'
    | '/_dashboard/groups'
    | '/_dashboard/sdn'
    | '/_dashboard/users'
    | '/_dashboard/'
    | '/_dashboard/vm/$itemId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/users': {
      id: '/_dashboard/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof DashboardUsersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/sdn': {
      id: '/_dashboard/sdn'
      path: '/sdn'
      fullPath: '/sdn'
      preLoaderRoute: typeof DashboardSdnRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/groups': {
      id: '/_dashboard/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof DashboardGroupsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/vm/$itemId': {
      id: '/_dashboard/vm/$itemId'
      path: '/vm/$itemId'
      fullPath: '/vm/$itemId'
      preLoaderRoute: typeof DashboardVmItemIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardGroupsRoute: typeof DashboardGroupsRoute
  DashboardSdnRoute: typeof DashboardSdnRoute
  DashboardUsersRoute: typeof DashboardUsersRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardVmItemIdRoute: typeof DashboardVmItemIdRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardGroupsRoute: DashboardGroupsRoute,
  DashboardSdnRoute: DashboardSdnRoute,
  DashboardUsersRoute: DashboardUsersRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardVmItemIdRoute: DashboardVmItemIdRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
