/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard/index'
import { Route as DashboardManagementSdnRouteImport } from './routes/_dashboard/management/sdn'
import { Route as DashboardManagementPrincipalsUsersRouteImport } from './routes/_dashboard/management/principals/users'
import { Route as DashboardManagementPrincipalsGroupsRouteImport } from './routes/_dashboard/management/principals/groups'
import { Route as DashboardInventoryItemsItemIdRouteImport } from './routes/_dashboard/inventory/items/$itemId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardManagementSdnRoute = DashboardManagementSdnRouteImport.update({
  id: '/management/sdn',
  path: '/management/sdn',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardManagementPrincipalsUsersRoute =
  DashboardManagementPrincipalsUsersRouteImport.update({
    id: '/management/principals/users',
    path: '/management/principals/users',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardManagementPrincipalsGroupsRoute =
  DashboardManagementPrincipalsGroupsRouteImport.update({
    id: '/management/principals/groups',
    path: '/management/principals/groups',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardInventoryItemsItemIdRoute =
  DashboardInventoryItemsItemIdRouteImport.update({
    id: '/inventory/items/$itemId',
    path: '/inventory/items/$itemId',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof DashboardIndexRoute
  '/login': typeof LoginRoute
  '/management/sdn': typeof DashboardManagementSdnRoute
  '/inventory/items/$itemId': typeof DashboardInventoryItemsItemIdRoute
  '/management/principals/groups': typeof DashboardManagementPrincipalsGroupsRoute
  '/management/principals/users': typeof DashboardManagementPrincipalsUsersRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof DashboardIndexRoute
  '/management/sdn': typeof DashboardManagementSdnRoute
  '/inventory/items/$itemId': typeof DashboardInventoryItemsItemIdRoute
  '/management/principals/groups': typeof DashboardManagementPrincipalsGroupsRoute
  '/management/principals/users': typeof DashboardManagementPrincipalsUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/_dashboard/': typeof DashboardIndexRoute
  '/_dashboard/management/sdn': typeof DashboardManagementSdnRoute
  '/_dashboard/inventory/items/$itemId': typeof DashboardInventoryItemsItemIdRoute
  '/_dashboard/management/principals/groups': typeof DashboardManagementPrincipalsGroupsRoute
  '/_dashboard/management/principals/users': typeof DashboardManagementPrincipalsUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/management/sdn'
    | '/inventory/items/$itemId'
    | '/management/principals/groups'
    | '/management/principals/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/management/sdn'
    | '/inventory/items/$itemId'
    | '/management/principals/groups'
    | '/management/principals/users'
  id:
    | '__root__'
    | '/_dashboard'
    | '/login'
    | '/_dashboard/'
    | '/_dashboard/management/sdn'
    | '/_dashboard/inventory/items/$itemId'
    | '/_dashboard/management/principals/groups'
    | '/_dashboard/management/principals/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/management/sdn': {
      id: '/_dashboard/management/sdn'
      path: '/management/sdn'
      fullPath: '/management/sdn'
      preLoaderRoute: typeof DashboardManagementSdnRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/management/principals/users': {
      id: '/_dashboard/management/principals/users'
      path: '/management/principals/users'
      fullPath: '/management/principals/users'
      preLoaderRoute: typeof DashboardManagementPrincipalsUsersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/management/principals/groups': {
      id: '/_dashboard/management/principals/groups'
      path: '/management/principals/groups'
      fullPath: '/management/principals/groups'
      preLoaderRoute: typeof DashboardManagementPrincipalsGroupsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/inventory/items/$itemId': {
      id: '/_dashboard/inventory/items/$itemId'
      path: '/inventory/items/$itemId'
      fullPath: '/inventory/items/$itemId'
      preLoaderRoute: typeof DashboardInventoryItemsItemIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardManagementSdnRoute: typeof DashboardManagementSdnRoute
  DashboardInventoryItemsItemIdRoute: typeof DashboardInventoryItemsItemIdRoute
  DashboardManagementPrincipalsGroupsRoute: typeof DashboardManagementPrincipalsGroupsRoute
  DashboardManagementPrincipalsUsersRoute: typeof DashboardManagementPrincipalsUsersRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardManagementSdnRoute: DashboardManagementSdnRoute,
  DashboardInventoryItemsItemIdRoute: DashboardInventoryItemsItemIdRoute,
  DashboardManagementPrincipalsGroupsRoute:
    DashboardManagementPrincipalsGroupsRoute,
  DashboardManagementPrincipalsUsersRoute:
    DashboardManagementPrincipalsUsersRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
