apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kamino
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd-image-updater.argoproj.io/image-list: kaminoapi=ghcr.io/maxwellcaron/kamino-api:latest,kaminoweb=ghcr.io/maxwellcaron/kamino-web:latest
    argocd-image-updater.argoproj.io/kaminoapi.update-strategy: digest
    argocd-image-updater.argoproj.io/kaminoweb.update-strategy: digest
spec:
  project: default
  source:
    repoURL: https://github.com/MaxwellCaron/kamino.git
    targetRevision: main
    path: deploy/k8s/overlays/prod
    kustomize:
      patches:
        - target:
            kind: ConfigMap
            name: kamino-config
          patch: |-
            - op: replace
              path: /data/PUBLIC_HOST
              value: placeholder.invalid
  destination:
    server: https://kubernetes.default.svc
    namespace: kamino
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
