apiVersion: v1
kind: ConfigMap
metadata:
  name: kamino-config
  labels:
    app.kubernetes.io/part-of: kamino
data:
  PUBLIC_HOST: placeholder.invalid
  GIN_MODE: release
  PORT: :8080
  FRONTEND_URL: https://placeholder.invalid
  PROXMOX_INSECURE: "false"
  PROXMOX_INITIAL_SYNC_ENABLED: "true"
  PRINCIPAL_PROVIDER: active_directory
  PRINCIPAL_INITIAL_SYNC_ENABLED: "true"
  PROXMOX_AUTH_REALM: pve
  LDAP_INSECURE: "false"
