apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kamino
  labels:
    app.kubernetes.io/part-of: kamino
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - placeholder.invalid
      secretName: kamino-tls
  rules:
    - host: placeholder.invalid
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  name: http
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  name: http
