// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countActionEventsFiltered = `-- name: CountActionEventsFiltered :one
WITH action_event_display AS (
    SELECT
        ae.id,
        ae.actor_principal_id,
        ae.action_kind,
        ae.target_kind,
        ae.inventory_item_id,
        ae.pod_id,
        ae.status,
        ae.error_message,
        ae.metadata,
        ae.created_at,
        COALESCE(actor.name, actor.external_id, '') AS actor_username,
        COALESCE(ii.name, NULLIF(target_tomb.snapshot->>'name', ''), '') AS inventory_item_name,
        COALESCE(ii.parent_id, NULLIF(target_tomb.snapshot->>'parent_id', '')::UUID) AS inventory_item_parent_id,
        COALESCE(parent.name, NULLIF(target_tomb.snapshot->>'parent_name', ''), '') AS inventory_item_parent_name,
        COALESCE(NULLIF(get_inventory_item_path(ii.id), ''), NULLIF(target_tomb.snapshot->>'path', ''), '')::TEXT AS inventory_item_path,
        COALESCE(pv.node, NULLIF(target_tomb.snapshot->>'node', ''), '') AS inventory_vm_node,
        COALESCE(pv.vmid, NULLIF(target_tomb.snapshot->>'vmid', '')::INTEGER, 0) AS inventory_vm_vmid,
        COALESCE(pp.title, NULLIF(target_tomb.snapshot->>'title', ''), '') AS pod_title,
        COALESCE(pp.slug, NULLIF(target_tomb.snapshot->>'slug', ''), '') AS pod_slug,
        COALESCE(
            NULLIF(get_inventory_item_path(cp.folder_id), ''),
            NULLIF(clone_tomb.snapshot->>'folder_path', ''),
            NULLIF(get_inventory_item_path(pp.source_folder_id), ''),
            NULLIF(target_tomb.snapshot->>'folder_path', ''),
            ''
        )::TEXT AS pod_folder_path
    FROM action_events ae
    LEFT JOIN principals actor
      ON actor.id = ae.actor_principal_id
    LEFT JOIN inventory_items ii
      ON ii.id = ae.inventory_item_id
    LEFT JOIN inventory_items parent
      ON parent.id = ii.parent_id
    LEFT JOIN proxmox_vms pv
      ON pv.inventory_item_id = ae.inventory_item_id
    LEFT JOIN published_pods pp
      ON pp.id = ae.pod_id
    LEFT JOIN LATERAL (
        SELECT CASE
            WHEN COALESCE(ae.metadata->>'clone_id', '') ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
                THEN (ae.metadata->>'clone_id')::UUID
        END AS clone_id
    ) clone_ref ON TRUE
    LEFT JOIN cloned_pods cp
      ON cp.id = clone_ref.clone_id
    LEFT JOIN action_target_tombstones clone_tomb
      ON clone_tomb.target_kind = 'pod_clone'
     AND clone_tomb.target_id = clone_ref.clone_id
    LEFT JOIN action_target_tombstones target_tomb
      ON target_tomb.target_kind = ae.target_kind
     AND target_tomb.target_id = CASE
         WHEN ae.target_kind = 'vm' THEN ae.inventory_item_id
         WHEN ae.target_kind = 'pod' THEN ae.pod_id
         ELSE NULL
     END
)
SELECT count(*)::int
FROM action_event_display
WHERE (
    $1::TEXT = ''
    OR actor_username ILIKE '%' || $1::TEXT || '%'
    OR action_kind ILIKE '%' || $1::TEXT || '%'
    OR target_kind ILIKE '%' || $1::TEXT || '%'
    OR status ILIKE '%' || $1::TEXT || '%'
    OR error_message ILIKE '%' || $1::TEXT || '%'
    OR inventory_item_name ILIKE '%' || $1::TEXT || '%'
    OR inventory_item_id::TEXT ILIKE '%' || $1::TEXT || '%'
    OR inventory_item_parent_name ILIKE '%' || $1::TEXT || '%'
    OR inventory_item_path ILIKE '%' || $1::TEXT || '%'
    OR inventory_vm_node ILIKE '%' || $1::TEXT || '%'
    OR inventory_vm_vmid::TEXT ILIKE '%' || $1::TEXT || '%'
    OR pod_id::TEXT ILIKE '%' || $1::TEXT || '%'
    OR pod_title ILIKE '%' || $1::TEXT || '%'
    OR pod_slug ILIKE '%' || $1::TEXT || '%'
    OR pod_folder_path ILIKE '%' || $1::TEXT || '%'
    OR metadata->>'clone_id' ILIKE '%' || $1::TEXT || '%'
)
`

func (q *Queries) CountActionEventsFiltered(ctx context.Context, search string) (int32, error) {
	row := q.db.QueryRow(ctx, countActionEventsFiltered, search)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const insertActionEvent = `-- name: InsertActionEvent :one

INSERT INTO action_events (
    actor_principal_id,
    action_kind,
    target_kind,
    inventory_item_id,
    pod_id,
    status,
    error_message,
    metadata
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING
    id,
    actor_principal_id,
    action_kind,
    target_kind,
    inventory_item_id,
    pod_id,
    status,
    error_message,
    metadata,
    created_at
`

type InsertActionEventParams struct {
	ActorPrincipalID *uuid.UUID `json:"actor_principal_id"`
	ActionKind       string     `json:"action_kind"`
	TargetKind       string     `json:"target_kind"`
	InventoryItemID  *uuid.UUID `json:"inventory_item_id"`
	PodID            *uuid.UUID `json:"pod_id"`
	Status           string     `json:"status"`
	ErrorMessage     *string    `json:"error_message"`
	Metadata         []byte     `json:"metadata"`
}

// ----------------------------------------------------------------------------
// Direct action audit ledger
// ----------------------------------------------------------------------------
func (q *Queries) InsertActionEvent(ctx context.Context, arg InsertActionEventParams) (ActionEvents, error) {
	row := q.db.QueryRow(ctx, insertActionEvent,
		arg.ActorPrincipalID,
		arg.ActionKind,
		arg.TargetKind,
		arg.InventoryItemID,
		arg.PodID,
		arg.Status,
		arg.ErrorMessage,
		arg.Metadata,
	)
	var i ActionEvents
	err := row.Scan(
		&i.ID,
		&i.ActorPrincipalID,
		&i.ActionKind,
		&i.TargetKind,
		&i.InventoryItemID,
		&i.PodID,
		&i.Status,
		&i.ErrorMessage,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const listActionEventsPaginated = `-- name: ListActionEventsPaginated :many
WITH action_event_display AS (
    SELECT
        ae.id,
        ae.actor_principal_id,
        ae.action_kind,
        ae.target_kind,
        ae.inventory_item_id,
        ae.pod_id,
        ae.status,
        ae.error_message,
        ae.metadata,
        ae.created_at,
        COALESCE(actor.name, actor.external_id, '') AS actor_username,
        COALESCE(ii.name, NULLIF(target_tomb.snapshot->>'name', ''), '') AS inventory_item_name,
        COALESCE(ii.parent_id, NULLIF(target_tomb.snapshot->>'parent_id', '')::UUID) AS inventory_item_parent_id,
        COALESCE(parent.name, NULLIF(target_tomb.snapshot->>'parent_name', ''), '') AS inventory_item_parent_name,
        COALESCE(NULLIF(get_inventory_item_path(ii.id), ''), NULLIF(target_tomb.snapshot->>'path', ''), '')::TEXT AS inventory_item_path,
        COALESCE(pv.node, NULLIF(target_tomb.snapshot->>'node', ''), '') AS inventory_vm_node,
        COALESCE(pv.vmid, NULLIF(target_tomb.snapshot->>'vmid', '')::INTEGER, 0) AS inventory_vm_vmid,
        COALESCE(pp.title, NULLIF(target_tomb.snapshot->>'title', ''), '') AS pod_title,
        COALESCE(pp.slug, NULLIF(target_tomb.snapshot->>'slug', ''), '') AS pod_slug,
        COALESCE(
            NULLIF(get_inventory_item_path(cp.folder_id), ''),
            NULLIF(clone_tomb.snapshot->>'folder_path', ''),
            NULLIF(get_inventory_item_path(pp.source_folder_id), ''),
            NULLIF(target_tomb.snapshot->>'folder_path', ''),
            ''
        )::TEXT AS pod_folder_path
    FROM action_events ae
    LEFT JOIN principals actor
      ON actor.id = ae.actor_principal_id
    LEFT JOIN inventory_items ii
      ON ii.id = ae.inventory_item_id
    LEFT JOIN inventory_items parent
      ON parent.id = ii.parent_id
    LEFT JOIN proxmox_vms pv
      ON pv.inventory_item_id = ae.inventory_item_id
    LEFT JOIN published_pods pp
      ON pp.id = ae.pod_id
    LEFT JOIN LATERAL (
        SELECT CASE
            WHEN COALESCE(ae.metadata->>'clone_id', '') ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
                THEN (ae.metadata->>'clone_id')::UUID
        END AS clone_id
    ) clone_ref ON TRUE
    LEFT JOIN cloned_pods cp
      ON cp.id = clone_ref.clone_id
    LEFT JOIN action_target_tombstones clone_tomb
      ON clone_tomb.target_kind = 'pod_clone'
     AND clone_tomb.target_id = clone_ref.clone_id
    LEFT JOIN action_target_tombstones target_tomb
      ON target_tomb.target_kind = ae.target_kind
     AND target_tomb.target_id = CASE
         WHEN ae.target_kind = 'vm' THEN ae.inventory_item_id
         WHEN ae.target_kind = 'pod' THEN ae.pod_id
         ELSE NULL
     END
)
SELECT id, actor_principal_id, action_kind, target_kind, inventory_item_id, pod_id, status, error_message, metadata, created_at, actor_username, inventory_item_name, inventory_item_parent_id, inventory_item_parent_name, inventory_item_path, inventory_vm_node, inventory_vm_vmid, pod_title, pod_slug, pod_folder_path
FROM action_event_display
WHERE (
    $1::TEXT = ''
    OR actor_username ILIKE '%' || $1::TEXT || '%'
    OR action_kind ILIKE '%' || $1::TEXT || '%'
    OR target_kind ILIKE '%' || $1::TEXT || '%'
    OR status ILIKE '%' || $1::TEXT || '%'
    OR error_message ILIKE '%' || $1::TEXT || '%'
    OR inventory_item_name ILIKE '%' || $1::TEXT || '%'
    OR inventory_item_id::TEXT ILIKE '%' || $1::TEXT || '%'
    OR inventory_item_parent_name ILIKE '%' || $1::TEXT || '%'
    OR inventory_item_path ILIKE '%' || $1::TEXT || '%'
    OR inventory_vm_node ILIKE '%' || $1::TEXT || '%'
    OR inventory_vm_vmid::TEXT ILIKE '%' || $1::TEXT || '%'
    OR pod_id::TEXT ILIKE '%' || $1::TEXT || '%'
    OR pod_title ILIKE '%' || $1::TEXT || '%'
    OR pod_slug ILIKE '%' || $1::TEXT || '%'
    OR pod_folder_path ILIKE '%' || $1::TEXT || '%'
    OR metadata->>'clone_id' ILIKE '%' || $1::TEXT || '%'
)
ORDER BY created_at DESC, id DESC
LIMIT $3
OFFSET $2
`

type ListActionEventsPaginatedParams struct {
	Search    string `json:"search"`
	RowOffset int32  `json:"row_offset"`
	Rows      int32  `json:"rows"`
}

type ListActionEventsPaginatedRow struct {
	ID                      int64              `json:"id"`
	ActorPrincipalID        *uuid.UUID         `json:"actor_principal_id"`
	ActionKind              string             `json:"action_kind"`
	TargetKind              string             `json:"target_kind"`
	InventoryItemID         *uuid.UUID         `json:"inventory_item_id"`
	PodID                   *uuid.UUID         `json:"pod_id"`
	Status                  string             `json:"status"`
	ErrorMessage            *string            `json:"error_message"`
	Metadata                []byte             `json:"metadata"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	ActorUsername           string             `json:"actor_username"`
	InventoryItemName       string             `json:"inventory_item_name"`
	InventoryItemParentID   *uuid.UUID         `json:"inventory_item_parent_id"`
	InventoryItemParentName string             `json:"inventory_item_parent_name"`
	InventoryItemPath       string             `json:"inventory_item_path"`
	InventoryVmNode         string             `json:"inventory_vm_node"`
	InventoryVmVmid         int32              `json:"inventory_vm_vmid"`
	PodTitle                string             `json:"pod_title"`
	PodSlug                 string             `json:"pod_slug"`
	PodFolderPath           string             `json:"pod_folder_path"`
}

func (q *Queries) ListActionEventsPaginated(ctx context.Context, arg ListActionEventsPaginatedParams) ([]ListActionEventsPaginatedRow, error) {
	rows, err := q.db.Query(ctx, listActionEventsPaginated, arg.Search, arg.RowOffset, arg.Rows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActionEventsPaginatedRow
	for rows.Next() {
		var i ListActionEventsPaginatedRow
		if err := rows.Scan(
			&i.ID,
			&i.ActorPrincipalID,
			&i.ActionKind,
			&i.TargetKind,
			&i.InventoryItemID,
			&i.PodID,
			&i.Status,
			&i.ErrorMessage,
			&i.Metadata,
			&i.CreatedAt,
			&i.ActorUsername,
			&i.InventoryItemName,
			&i.InventoryItemParentID,
			&i.InventoryItemParentName,
			&i.InventoryItemPath,
			&i.InventoryVmNode,
			&i.InventoryVmVmid,
			&i.PodTitle,
			&i.PodSlug,
			&i.PodFolderPath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
