// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: authorization_vms.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getBulkVMItems = `-- name: GetBulkVMItems :many
SELECT
    ii.id,
    COALESCE(pv.node, '') AS node,
    COALESCE(pv.vmid, 0)::INTEGER AS vmid,
    COALESCE(pv.guest_type, 'qemu') AS guest_type,
    COALESCE(pv.upstream_uuid, '00000000-0000-0000-0000-000000000000'::UUID) AS upstream_uuid,
    (pv.upstream_uuid IS NOT NULL) AS has_vm
FROM inventory_items ii
LEFT JOIN LATERAL (
    SELECT
        proxmox_vms.node,
        proxmox_vms.vmid,
        proxmox_vms.guest_type,
        proxmox_vms.upstream_uuid
    FROM proxmox_vms
    WHERE proxmox_vms.inventory_item_id = ii.id
) AS pv ON TRUE
WHERE ii.id = ANY($1::UUID[])
`

type GetBulkVMItemsRow struct {
	ID           uuid.UUID   `json:"id"`
	Node         string      `json:"node"`
	Vmid         int32       `json:"vmid"`
	GuestType    string      `json:"guest_type"`
	UpstreamUuid uuid.UUID   `json:"upstream_uuid"`
	HasVm        interface{} `json:"has_vm"`
}

func (q *Queries) GetBulkVMItems(ctx context.Context, itemIds []uuid.UUID) ([]GetBulkVMItemsRow, error) {
	rows, err := q.db.Query(ctx, getBulkVMItems, itemIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBulkVMItemsRow
	for rows.Next() {
		var i GetBulkVMItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.Node,
			&i.Vmid,
			&i.GuestType,
			&i.UpstreamUuid,
			&i.HasVm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBulkVMItemsForUpdate = `-- name: GetBulkVMItemsForUpdate :many
SELECT
    ii.id,
    COALESCE(pv.node, '') AS node,
    COALESCE(pv.vmid, 0)::INTEGER AS vmid,
    COALESCE(pv.guest_type, 'qemu') AS guest_type,
    COALESCE(pv.upstream_uuid, '00000000-0000-0000-0000-000000000000'::UUID) AS upstream_uuid,
    (pv.upstream_uuid IS NOT NULL) AS has_vm
FROM inventory_items ii
LEFT JOIN LATERAL (
    SELECT
        proxmox_vms.node,
        proxmox_vms.vmid,
        proxmox_vms.guest_type,
        proxmox_vms.upstream_uuid
    FROM proxmox_vms
    WHERE proxmox_vms.inventory_item_id = ii.id
    FOR UPDATE
) AS pv ON TRUE
WHERE ii.id = ANY($1::UUID[])
`

type GetBulkVMItemsForUpdateRow struct {
	ID           uuid.UUID   `json:"id"`
	Node         string      `json:"node"`
	Vmid         int32       `json:"vmid"`
	GuestType    string      `json:"guest_type"`
	UpstreamUuid uuid.UUID   `json:"upstream_uuid"`
	HasVm        interface{} `json:"has_vm"`
}

func (q *Queries) GetBulkVMItemsForUpdate(ctx context.Context, itemIds []uuid.UUID) ([]GetBulkVMItemsForUpdateRow, error) {
	rows, err := q.db.Query(ctx, getBulkVMItemsForUpdate, itemIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBulkVMItemsForUpdateRow
	for rows.Next() {
		var i GetBulkVMItemsForUpdateRow
		if err := rows.Scan(
			&i.ID,
			&i.Node,
			&i.Vmid,
			&i.GuestType,
			&i.UpstreamUuid,
			&i.HasVm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBulkVMItemsWithPermissions = `-- name: GetBulkVMItemsWithPermissions :many
WITH RECURSIVE
effective_principals AS (
    SELECT ep.principal_id FROM get_user_effective_principals($1) AS ep(principal_id)
)
SELECT
    ii.id,
    COALESCE(pv.node, '') AS node,
    COALESCE(pv.vmid, 0)::INTEGER AS vmid,
    COALESCE(pv.guest_type, 'qemu') AS guest_type,
    COALESCE(pv.upstream_uuid, '00000000-0000-0000-0000-000000000000'::UUID) AS upstream_uuid,
    (pv.upstream_uuid IS NOT NULL) AS has_vm,
    perms.allowed_mask,
    perms.denied_mask
FROM inventory_items ii
LEFT JOIN LATERAL (
    SELECT
        proxmox_vms.node,
        proxmox_vms.vmid,
        proxmox_vms.guest_type,
        proxmox_vms.upstream_uuid
    FROM proxmox_vms
    WHERE proxmox_vms.inventory_item_id = ii.id
) AS pv ON TRUE
CROSS JOIN LATERAL (
    SELECT
        gep.allowed_mask::BIGINT AS allowed_mask,
        gep.denied_mask::BIGINT AS denied_mask
    FROM get_effective_permissions_for_set(
        $1,
        (SELECT array_agg(principal_id) FROM effective_principals),
        ii.id
    ) AS gep(allowed_mask, denied_mask)
) AS perms
WHERE ii.id = ANY($2::UUID[])
`

type GetBulkVMItemsWithPermissionsParams struct {
	PrincipalID uuid.UUID   `json:"principal_id"`
	ItemIds     []uuid.UUID `json:"item_ids"`
}

type GetBulkVMItemsWithPermissionsRow struct {
	ID           uuid.UUID   `json:"id"`
	Node         string      `json:"node"`
	Vmid         int32       `json:"vmid"`
	GuestType    string      `json:"guest_type"`
	UpstreamUuid uuid.UUID   `json:"upstream_uuid"`
	HasVm        interface{} `json:"has_vm"`
	AllowedMask  int64       `json:"allowed_mask"`
	DeniedMask   int64       `json:"denied_mask"`
}

func (q *Queries) GetBulkVMItemsWithPermissions(ctx context.Context, arg GetBulkVMItemsWithPermissionsParams) ([]GetBulkVMItemsWithPermissionsRow, error) {
	rows, err := q.db.Query(ctx, getBulkVMItemsWithPermissions, arg.PrincipalID, arg.ItemIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBulkVMItemsWithPermissionsRow
	for rows.Next() {
		var i GetBulkVMItemsWithPermissionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Node,
			&i.Vmid,
			&i.GuestType,
			&i.UpstreamUuid,
			&i.HasVm,
			&i.AllowedMask,
			&i.DeniedMask,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBulkVMItemsWithPermissionsForUpdate = `-- name: GetBulkVMItemsWithPermissionsForUpdate :many
WITH RECURSIVE
effective_principals AS (
    SELECT ep.principal_id FROM get_user_effective_principals($1) AS ep(principal_id)
)
SELECT
    ii.id,
    COALESCE(pv.node, '') AS node,
    COALESCE(pv.vmid, 0)::INTEGER AS vmid,
    COALESCE(pv.guest_type, 'qemu') AS guest_type,
    COALESCE(pv.upstream_uuid, '00000000-0000-0000-0000-000000000000'::UUID) AS upstream_uuid,
    (pv.upstream_uuid IS NOT NULL) AS has_vm,
    perms.allowed_mask,
    perms.denied_mask
FROM inventory_items ii
LEFT JOIN LATERAL (
    SELECT
        proxmox_vms.node,
        proxmox_vms.vmid,
        proxmox_vms.guest_type,
        proxmox_vms.upstream_uuid
    FROM proxmox_vms
    WHERE proxmox_vms.inventory_item_id = ii.id
    FOR UPDATE
) AS pv ON TRUE
CROSS JOIN LATERAL (
    SELECT
        gep.allowed_mask::BIGINT AS allowed_mask,
        gep.denied_mask::BIGINT AS denied_mask
    FROM get_effective_permissions_for_set(
        $1,
        (SELECT array_agg(principal_id) FROM effective_principals),
        ii.id
    ) AS gep(allowed_mask, denied_mask)
) AS perms
WHERE ii.id = ANY($2::UUID[])
`

type GetBulkVMItemsWithPermissionsForUpdateParams struct {
	PrincipalID uuid.UUID   `json:"principal_id"`
	ItemIds     []uuid.UUID `json:"item_ids"`
}

type GetBulkVMItemsWithPermissionsForUpdateRow struct {
	ID           uuid.UUID   `json:"id"`
	Node         string      `json:"node"`
	Vmid         int32       `json:"vmid"`
	GuestType    string      `json:"guest_type"`
	UpstreamUuid uuid.UUID   `json:"upstream_uuid"`
	HasVm        interface{} `json:"has_vm"`
	AllowedMask  int64       `json:"allowed_mask"`
	DeniedMask   int64       `json:"denied_mask"`
}

func (q *Queries) GetBulkVMItemsWithPermissionsForUpdate(ctx context.Context, arg GetBulkVMItemsWithPermissionsForUpdateParams) ([]GetBulkVMItemsWithPermissionsForUpdateRow, error) {
	rows, err := q.db.Query(ctx, getBulkVMItemsWithPermissionsForUpdate, arg.PrincipalID, arg.ItemIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBulkVMItemsWithPermissionsForUpdateRow
	for rows.Next() {
		var i GetBulkVMItemsWithPermissionsForUpdateRow
		if err := rows.Scan(
			&i.ID,
			&i.Node,
			&i.Vmid,
			&i.GuestType,
			&i.UpstreamUuid,
			&i.HasVm,
			&i.AllowedMask,
			&i.DeniedMask,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInventoryItemIDByProxmoxVM = `-- name: GetInventoryItemIDByProxmoxVM :one
SELECT inventory_item_id
FROM proxmox_vms
WHERE node = $1 AND vmid = $2
`

type GetInventoryItemIDByProxmoxVMParams struct {
	Node string `json:"node"`
	Vmid int32  `json:"vmid"`
}

func (q *Queries) GetInventoryItemIDByProxmoxVM(ctx context.Context, arg GetInventoryItemIDByProxmoxVMParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getInventoryItemIDByProxmoxVM, arg.Node, arg.Vmid)
	var inventory_item_id uuid.UUID
	err := row.Scan(&inventory_item_id)
	return inventory_item_id, err
}

const listVisibleVMIDsForPrincipal = `-- name: ListVisibleVMIDsForPrincipal :many
WITH RECURSIVE
effective_principals AS (
    SELECT ep.principal_id FROM get_user_effective_principals($1) AS ep(principal_id)
)
SELECT pv.vmid
FROM proxmox_vms pv
JOIN inventory_items ii
  ON ii.id = pv.inventory_item_id
CROSS JOIN LATERAL (
    SELECT
        gep.allowed_mask::BIGINT AS allowed_mask,
        gep.denied_mask::BIGINT AS denied_mask
    FROM get_effective_permissions_for_set(
        $1,
        (SELECT array_agg(principal_id) FROM effective_principals),
        ii.id
    ) AS gep(allowed_mask, denied_mask)
) AS perms
WHERE (perms.allowed_mask & 1::BIGINT) = 1::BIGINT
`

func (q *Queries) ListVisibleVMIDsForPrincipal(ctx context.Context, principalID uuid.UUID) ([]int32, error) {
	rows, err := q.db.Query(ctx, listVisibleVMIDsForPrincipal, principalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var vmid int32
		if err := rows.Scan(&vmid); err != nil {
			return nil, err
		}
		items = append(items, vmid)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
