// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: authorization.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const countInventoryACLEntries = `-- name: CountInventoryACLEntries :one
SELECT COUNT(*)::BIGINT
FROM inventory_acl_entries
`

func (q *Queries) CountInventoryACLEntries(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countInventoryACLEntries)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createInventoryACLEntry = `-- name: CreateInventoryACLEntry :exec
INSERT INTO inventory_acl_entries (
    inventory_item_id,
    principal_id,
    effect,
    permissions,
    applies_to_self,
    applies_to_children,
    inherited_only
) VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT DO NOTHING
`

type CreateInventoryACLEntryParams struct {
	InventoryItemID   uuid.UUID          `json:"inventory_item_id"`
	PrincipalID       uuid.UUID          `json:"principal_id"`
	Effect            InventoryAceEffect `json:"effect"`
	Permissions       int64              `json:"permissions"`
	AppliesToSelf     bool               `json:"applies_to_self"`
	AppliesToChildren bool               `json:"applies_to_children"`
	InheritedOnly     bool               `json:"inherited_only"`
}

func (q *Queries) CreateInventoryACLEntry(ctx context.Context, arg CreateInventoryACLEntryParams) error {
	_, err := q.db.Exec(ctx, createInventoryACLEntry,
		arg.InventoryItemID,
		arg.PrincipalID,
		arg.Effect,
		arg.Permissions,
		arg.AppliesToSelf,
		arg.AppliesToChildren,
		arg.InheritedOnly,
	)
	return err
}

const createManagementPermissionGrant = `-- name: CreateManagementPermissionGrant :exec
INSERT INTO management_permission_grants (
    group_principal_id,
    permission_key
) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type CreateManagementPermissionGrantParams struct {
	GroupPrincipalID uuid.UUID `json:"group_principal_id"`
	PermissionKey    string    `json:"permission_key"`
}

func (q *Queries) CreateManagementPermissionGrant(ctx context.Context, arg CreateManagementPermissionGrantParams) error {
	_, err := q.db.Exec(ctx, createManagementPermissionGrant, arg.GroupPrincipalID, arg.PermissionKey)
	return err
}

const deleteInventoryACLEntriesForItem = `-- name: DeleteInventoryACLEntriesForItem :exec
DELETE FROM inventory_acl_entries
WHERE inventory_item_id = $1
`

func (q *Queries) DeleteInventoryACLEntriesForItem(ctx context.Context, inventoryItemID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteInventoryACLEntriesForItem, inventoryItemID)
	return err
}

const deleteManagementPermissionGrantsForGroup = `-- name: DeleteManagementPermissionGrantsForGroup :exec
DELETE FROM management_permission_grants
WHERE group_principal_id = $1
`

func (q *Queries) DeleteManagementPermissionGrantsForGroup(ctx context.Context, groupPrincipalID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteManagementPermissionGrantsForGroup, groupPrincipalID)
	return err
}

const getEffectiveInventoryPermissions = `-- name: GetEffectiveInventoryPermissions :one
SELECT gep.allowed_mask::BIGINT AS allowed_mask, gep.denied_mask::BIGINT AS denied_mask
FROM get_effective_permissions(
    $1,
    $2
) AS gep(allowed_mask, denied_mask)
`

type GetEffectiveInventoryPermissionsParams struct {
	PrincipalID     uuid.UUID `json:"principal_id"`
	InventoryItemID uuid.UUID `json:"inventory_item_id"`
}

type GetEffectiveInventoryPermissionsRow struct {
	AllowedMask int64 `json:"allowed_mask"`
	DeniedMask  int64 `json:"denied_mask"`
}

func (q *Queries) GetEffectiveInventoryPermissions(ctx context.Context, arg GetEffectiveInventoryPermissionsParams) (GetEffectiveInventoryPermissionsRow, error) {
	row := q.db.QueryRow(ctx, getEffectiveInventoryPermissions, arg.PrincipalID, arg.InventoryItemID)
	var i GetEffectiveInventoryPermissionsRow
	err := row.Scan(&i.AllowedMask, &i.DeniedMask)
	return i, err
}

const getInventoryItemIDByProxmoxVM = `-- name: GetInventoryItemIDByProxmoxVM :one
SELECT inventory_item_id
FROM proxmox_vms
WHERE node = $1 AND vmid = $2
`

type GetInventoryItemIDByProxmoxVMParams struct {
	Node string `json:"node"`
	Vmid int32  `json:"vmid"`
}

func (q *Queries) GetInventoryItemIDByProxmoxVM(ctx context.Context, arg GetInventoryItemIDByProxmoxVMParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getInventoryItemIDByProxmoxVM, arg.Node, arg.Vmid)
	var inventory_item_id uuid.UUID
	err := row.Scan(&inventory_item_id)
	return inventory_item_id, err
}

const getInventoryItemWithPermissions = `-- name: GetInventoryItemWithPermissions :one
SELECT
    ii.id,
    ii.parent_id,
    ii.kind,
    ii.name,
    ii.inherit_permissions,
    pv.node,
    pv.vmid,
    pv.is_template,
    pv.notes,
    pv.cpu_count,
    pv.memory_mb,
    pv.disk_gb,
    perms.allowed_mask,
    perms.denied_mask
FROM inventory_items ii
LEFT JOIN proxmox_vms pv
  ON pv.inventory_item_id = ii.id
CROSS JOIN LATERAL (
    SELECT
        gep.allowed_mask::BIGINT AS allowed_mask,
        gep.denied_mask::BIGINT AS denied_mask
    FROM get_effective_permissions($1, ii.id) AS gep(allowed_mask, denied_mask)
) AS perms
WHERE ii.id = $2
`

type GetInventoryItemWithPermissionsParams struct {
	PrincipalID     uuid.UUID `json:"principal_id"`
	InventoryItemID uuid.UUID `json:"inventory_item_id"`
}

type GetInventoryItemWithPermissionsRow struct {
	ID                 uuid.UUID         `json:"id"`
	ParentID           *uuid.UUID        `json:"parent_id"`
	Kind               InventoryItemKind `json:"kind"`
	Name               string            `json:"name"`
	InheritPermissions bool              `json:"inherit_permissions"`
	Node               *string           `json:"node"`
	Vmid               *int32            `json:"vmid"`
	IsTemplate         *bool             `json:"is_template"`
	Notes              *string           `json:"notes"`
	CpuCount           *int32            `json:"cpu_count"`
	MemoryMb           *int32            `json:"memory_mb"`
	DiskGb             *float64          `json:"disk_gb"`
	AllowedMask        int64             `json:"allowed_mask"`
	DeniedMask         int64             `json:"denied_mask"`
}

func (q *Queries) GetInventoryItemWithPermissions(ctx context.Context, arg GetInventoryItemWithPermissionsParams) (GetInventoryItemWithPermissionsRow, error) {
	row := q.db.QueryRow(ctx, getInventoryItemWithPermissions, arg.PrincipalID, arg.InventoryItemID)
	var i GetInventoryItemWithPermissionsRow
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Kind,
		&i.Name,
		&i.InheritPermissions,
		&i.Node,
		&i.Vmid,
		&i.IsTemplate,
		&i.Notes,
		&i.CpuCount,
		&i.MemoryMb,
		&i.DiskGb,
		&i.AllowedMask,
		&i.DeniedMask,
	)
	return i, err
}

const getPrincipalGroupsByName = `-- name: GetPrincipalGroupsByName :many
SELECT id, name
FROM principals
WHERE principal_type = 'group'
  AND name = ANY($1::TEXT[])
`

type GetPrincipalGroupsByNameRow struct {
	ID   uuid.UUID `json:"id"`
	Name *string   `json:"name"`
}

func (q *Queries) GetPrincipalGroupsByName(ctx context.Context, dollar_1 []string) ([]GetPrincipalGroupsByNameRow, error) {
	rows, err := q.db.Query(ctx, getPrincipalGroupsByName, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPrincipalGroupsByNameRow
	for rows.Next() {
		var i GetPrincipalGroupsByNameRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVisibleInventoryItemsForPrincipal = `-- name: GetVisibleInventoryItemsForPrincipal :many
SELECT
    ii.id,
    ii.parent_id,
    ii.kind,
    ii.name,
    ii.inherit_permissions,
    pv.node,
    pv.vmid,
    pv.is_template,
    pv.notes,
    pv.cpu_count,
    pv.memory_mb,
    pv.disk_gb,
    perms.allowed_mask,
    perms.denied_mask
FROM inventory_items ii
LEFT JOIN proxmox_vms pv
  ON pv.inventory_item_id = ii.id
CROSS JOIN LATERAL (
    SELECT
        gep.allowed_mask::BIGINT AS allowed_mask,
        gep.denied_mask::BIGINT AS denied_mask
    FROM get_effective_permissions($1, ii.id) AS gep(allowed_mask, denied_mask)
) AS perms
WHERE (perms.allowed_mask & 1::BIGINT) = 1::BIGINT
ORDER BY
  CASE WHEN ii.kind = 'folder' THEN 0 ELSE 1 END,
  lower(ii.name) ASC,
  ii.name ASC
`

type GetVisibleInventoryItemsForPrincipalRow struct {
	ID                 uuid.UUID         `json:"id"`
	ParentID           *uuid.UUID        `json:"parent_id"`
	Kind               InventoryItemKind `json:"kind"`
	Name               string            `json:"name"`
	InheritPermissions bool              `json:"inherit_permissions"`
	Node               *string           `json:"node"`
	Vmid               *int32            `json:"vmid"`
	IsTemplate         *bool             `json:"is_template"`
	Notes              *string           `json:"notes"`
	CpuCount           *int32            `json:"cpu_count"`
	MemoryMb           *int32            `json:"memory_mb"`
	DiskGb             *float64          `json:"disk_gb"`
	AllowedMask        int64             `json:"allowed_mask"`
	DeniedMask         int64             `json:"denied_mask"`
}

func (q *Queries) GetVisibleInventoryItemsForPrincipal(ctx context.Context, principalID uuid.UUID) ([]GetVisibleInventoryItemsForPrincipalRow, error) {
	rows, err := q.db.Query(ctx, getVisibleInventoryItemsForPrincipal, principalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetVisibleInventoryItemsForPrincipalRow
	for rows.Next() {
		var i GetVisibleInventoryItemsForPrincipalRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Kind,
			&i.Name,
			&i.InheritPermissions,
			&i.Node,
			&i.Vmid,
			&i.IsTemplate,
			&i.Notes,
			&i.CpuCount,
			&i.MemoryMb,
			&i.DiskGb,
			&i.AllowedMask,
			&i.DeniedMask,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hasInventoryPermission = `-- name: HasInventoryPermission :one
SELECT has_permission(
    $1,
    $2,
    $3
)
`

type HasInventoryPermissionParams struct {
	PrincipalID     uuid.UUID `json:"principal_id"`
	InventoryItemID uuid.UUID `json:"inventory_item_id"`
	RequiredMask    int64     `json:"required_mask"`
}

func (q *Queries) HasInventoryPermission(ctx context.Context, arg HasInventoryPermissionParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasInventoryPermission, arg.PrincipalID, arg.InventoryItemID, arg.RequiredMask)
	var has_permission bool
	err := row.Scan(&has_permission)
	return has_permission, err
}

const listEffectiveManagementPermissionKeys = `-- name: ListEffectiveManagementPermissionKeys :many
SELECT gep.permission_key::TEXT AS permission_key
FROM get_effective_management_permissions(
    $1
) AS gep(permission_key)
`

func (q *Queries) ListEffectiveManagementPermissionKeys(ctx context.Context, principalID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listEffectiveManagementPermissionKeys, principalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var permission_key string
		if err := rows.Scan(&permission_key); err != nil {
			return nil, err
		}
		items = append(items, permission_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEffectivePrincipalIDs = `-- name: ListEffectivePrincipalIDs :many
SELECT ep.principal_id::UUID
FROM get_user_effective_principals($1) AS ep(principal_id)
`

func (q *Queries) ListEffectivePrincipalIDs(ctx context.Context, principalID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listEffectivePrincipalIDs, principalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var ep_principal_id uuid.UUID
		if err := rows.Scan(&ep_principal_id); err != nil {
			return nil, err
		}
		items = append(items, ep_principal_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInheritedInventoryACLEntriesForItem = `-- name: ListInheritedInventoryACLEntriesForItem :many
SELECT
    ace.id,
    chain.ancestor_depth AS ancestor_depth,
    ace.inventory_item_id AS source_item_id,
    source_item.name AS source_item_name,
    ace.principal_id,
    p.principal_type,
    p.external_id,
    p.name,
    ace.effect,
    ace.permissions,
    ace.applies_to_self,
    ace.applies_to_children,
    ace.inherited_only
FROM get_inventory_ancestor_chain($1)
AS chain(inventory_item_id, ancestor_depth, kind, inherit_permissions)
JOIN inventory_acl_entries ace
  ON ace.inventory_item_id = chain.inventory_item_id
JOIN inventory_items source_item
  ON source_item.id = ace.inventory_item_id
JOIN principals p
  ON p.id = ace.principal_id
WHERE chain.ancestor_depth > 0
  AND ace.applies_to_children = true
ORDER BY
    lower(COALESCE(p.name, p.external_id)) ASC,
    COALESCE(p.name, p.external_id) ASC,
    ancestor_depth ASC,
    source_item.name ASC,
    ace.effect ASC,
    ace.permissions ASC
`

type ListInheritedInventoryACLEntriesForItemRow struct {
	ID                uuid.UUID          `json:"id"`
	AncestorDepth     interface{}        `json:"ancestor_depth"`
	SourceItemID      uuid.UUID          `json:"source_item_id"`
	SourceItemName    string             `json:"source_item_name"`
	PrincipalID       uuid.UUID          `json:"principal_id"`
	PrincipalType     PrincipalType      `json:"principal_type"`
	ExternalID        string             `json:"external_id"`
	Name              *string            `json:"name"`
	Effect            InventoryAceEffect `json:"effect"`
	Permissions       int64              `json:"permissions"`
	AppliesToSelf     bool               `json:"applies_to_self"`
	AppliesToChildren bool               `json:"applies_to_children"`
	InheritedOnly     bool               `json:"inherited_only"`
}

func (q *Queries) ListInheritedInventoryACLEntriesForItem(ctx context.Context, pInventoryItemID uuid.UUID) ([]ListInheritedInventoryACLEntriesForItemRow, error) {
	rows, err := q.db.Query(ctx, listInheritedInventoryACLEntriesForItem, pInventoryItemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInheritedInventoryACLEntriesForItemRow
	for rows.Next() {
		var i ListInheritedInventoryACLEntriesForItemRow
		if err := rows.Scan(
			&i.ID,
			&i.AncestorDepth,
			&i.SourceItemID,
			&i.SourceItemName,
			&i.PrincipalID,
			&i.PrincipalType,
			&i.ExternalID,
			&i.Name,
			&i.Effect,
			&i.Permissions,
			&i.AppliesToSelf,
			&i.AppliesToChildren,
			&i.InheritedOnly,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInventoryACLEntriesForItem = `-- name: ListInventoryACLEntriesForItem :many
SELECT
    ace.id,
    ace.inventory_item_id,
    ace.principal_id,
    p.principal_type,
    p.external_id,
    p.name,
    ace.effect,
    ace.permissions,
    ace.applies_to_self,
    ace.applies_to_children,
    ace.inherited_only
FROM inventory_acl_entries ace
JOIN principals p
  ON p.id = ace.principal_id
WHERE ace.inventory_item_id = $1
ORDER BY
    lower(COALESCE(p.name, p.external_id)) ASC,
    COALESCE(p.name, p.external_id) ASC,
    ace.effect ASC,
    ace.permissions ASC
`

type ListInventoryACLEntriesForItemRow struct {
	ID                uuid.UUID          `json:"id"`
	InventoryItemID   uuid.UUID          `json:"inventory_item_id"`
	PrincipalID       uuid.UUID          `json:"principal_id"`
	PrincipalType     PrincipalType      `json:"principal_type"`
	ExternalID        string             `json:"external_id"`
	Name              *string            `json:"name"`
	Effect            InventoryAceEffect `json:"effect"`
	Permissions       int64              `json:"permissions"`
	AppliesToSelf     bool               `json:"applies_to_self"`
	AppliesToChildren bool               `json:"applies_to_children"`
	InheritedOnly     bool               `json:"inherited_only"`
}

func (q *Queries) ListInventoryACLEntriesForItem(ctx context.Context, inventoryItemID uuid.UUID) ([]ListInventoryACLEntriesForItemRow, error) {
	rows, err := q.db.Query(ctx, listInventoryACLEntriesForItem, inventoryItemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInventoryACLEntriesForItemRow
	for rows.Next() {
		var i ListInventoryACLEntriesForItemRow
		if err := rows.Scan(
			&i.ID,
			&i.InventoryItemID,
			&i.PrincipalID,
			&i.PrincipalType,
			&i.ExternalID,
			&i.Name,
			&i.Effect,
			&i.Permissions,
			&i.AppliesToSelf,
			&i.AppliesToChildren,
			&i.InheritedOnly,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listManagementPermissionGrantsForGroup = `-- name: ListManagementPermissionGrantsForGroup :many
SELECT permission_key
FROM management_permission_grants
WHERE group_principal_id = $1
`

func (q *Queries) ListManagementPermissionGrantsForGroup(ctx context.Context, groupPrincipalID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listManagementPermissionGrantsForGroup, groupPrincipalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var permission_key string
		if err := rows.Scan(&permission_key); err != nil {
			return nil, err
		}
		items = append(items, permission_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRootInventoryFolderIDs = `-- name: ListRootInventoryFolderIDs :many
SELECT id
FROM inventory_items
WHERE parent_id IS NULL
  AND kind = 'folder'
`

func (q *Queries) ListRootInventoryFolderIDs(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listRootInventoryFolderIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVisibleVMIDsForPrincipal = `-- name: ListVisibleVMIDsForPrincipal :many
SELECT pv.vmid
FROM proxmox_vms pv
JOIN inventory_items ii
  ON ii.id = pv.inventory_item_id
CROSS JOIN LATERAL (
    SELECT
        gep.allowed_mask::BIGINT AS allowed_mask,
        gep.denied_mask::BIGINT AS denied_mask
    FROM get_effective_permissions($1, ii.id) AS gep(allowed_mask, denied_mask)
) AS perms
WHERE (perms.allowed_mask & 1::BIGINT) = 1::BIGINT
`

func (q *Queries) ListVisibleVMIDsForPrincipal(ctx context.Context, principalID uuid.UUID) ([]int32, error) {
	rows, err := q.db.Query(ctx, listVisibleVMIDsForPrincipal, principalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var vmid int32
		if err := rows.Scan(&vmid); err != nil {
			return nil, err
		}
		items = append(items, vmid)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
