// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAuthSession = `-- name: CreateAuthSession :exec
INSERT INTO auth_sessions (
    id,
    principal_id,
    token_hash,
    family_id,
    user_agent,
    ip_address,
    expires_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateAuthSessionParams struct {
	ID          uuid.UUID          `json:"id"`
	PrincipalID uuid.UUID          `json:"principal_id"`
	TokenHash   string             `json:"token_hash"`
	FamilyID    uuid.UUID          `json:"family_id"`
	UserAgent   *string            `json:"user_agent"`
	IpAddress   *string            `json:"ip_address"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateAuthSession(ctx context.Context, arg CreateAuthSessionParams) error {
	_, err := q.db.Exec(ctx, createAuthSession,
		arg.ID,
		arg.PrincipalID,
		arg.TokenHash,
		arg.FamilyID,
		arg.UserAgent,
		arg.IpAddress,
		arg.ExpiresAt,
	)
	return err
}

const getAuthSessionByTokenHashForUpdate = `-- name: GetAuthSessionByTokenHashForUpdate :one
SELECT
    id,
    principal_id,
    token_hash,
    family_id,
    replaced_by_session_id,
    user_agent,
    ip_address,
    created_at,
    last_used_at,
    expires_at,
    revoked_at
FROM auth_sessions
WHERE token_hash = $1
FOR UPDATE
`

func (q *Queries) GetAuthSessionByTokenHashForUpdate(ctx context.Context, tokenHash string) (AuthSessions, error) {
	row := q.db.QueryRow(ctx, getAuthSessionByTokenHashForUpdate, tokenHash)
	var i AuthSessions
	err := row.Scan(
		&i.ID,
		&i.PrincipalID,
		&i.TokenHash,
		&i.FamilyID,
		&i.ReplacedBySessionID,
		&i.UserAgent,
		&i.IpAddress,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const revokeAuthSession = `-- name: RevokeAuthSession :exec
UPDATE auth_sessions
SET revoked_at = COALESCE(revoked_at, now())
WHERE id = $1
`

func (q *Queries) RevokeAuthSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAuthSession, id)
	return err
}

const revokeAuthSessionFamily = `-- name: RevokeAuthSessionFamily :execrows
UPDATE auth_sessions
SET revoked_at = COALESCE(revoked_at, now())
WHERE family_id = $1
  AND revoked_at IS NULL
`

func (q *Queries) RevokeAuthSessionFamily(ctx context.Context, familyID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAuthSessionFamily, familyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rotateAuthSession = `-- name: RotateAuthSession :exec
UPDATE auth_sessions
SET
    revoked_at = now(),
    replaced_by_session_id = $2,
    last_used_at = now()
WHERE id = $1
`

type RotateAuthSessionParams struct {
	ID                  uuid.UUID  `json:"id"`
	ReplacedBySessionID *uuid.UUID `json:"replaced_by_session_id"`
}

func (q *Queries) RotateAuthSession(ctx context.Context, arg RotateAuthSessionParams) error {
	_, err := q.db.Exec(ctx, rotateAuthSession, arg.ID, arg.ReplacedBySessionID)
	return err
}
