// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: capacity.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createFolderVMCapacityReservation = `-- name: CreateFolderVMCapacityReservation :one
INSERT INTO folder_vm_capacity_reservations (folder_id, vm_count, operation)
VALUES ($1, $2, $3)
RETURNING id, folder_id, vm_count, operation, created_at
`

type CreateFolderVMCapacityReservationParams struct {
	FolderID  uuid.UUID `json:"folder_id"`
	VmCount   int32     `json:"vm_count"`
	Operation string    `json:"operation"`
}

func (q *Queries) CreateFolderVMCapacityReservation(ctx context.Context, arg CreateFolderVMCapacityReservationParams) (FolderVmCapacityReservations, error) {
	row := q.db.QueryRow(ctx, createFolderVMCapacityReservation, arg.FolderID, arg.VmCount, arg.Operation)
	var i FolderVmCapacityReservations
	err := row.Scan(
		&i.ID,
		&i.FolderID,
		&i.VmCount,
		&i.Operation,
		&i.CreatedAt,
	)
	return i, err
}

const releaseFolderVMCapacityReservation = `-- name: ReleaseFolderVMCapacityReservation :exec
DELETE FROM folder_vm_capacity_reservations
WHERE id = $1
`

func (q *Queries) ReleaseFolderVMCapacityReservation(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, releaseFolderVMCapacityReservation, id)
	return err
}

const sumActiveFolderVMCapacityReservations = `-- name: SumActiveFolderVMCapacityReservations :one
SELECT COALESCE(SUM(vm_count), 0)::INTEGER AS total
FROM folder_vm_capacity_reservations
WHERE folder_id = $1
`

func (q *Queries) SumActiveFolderVMCapacityReservations(ctx context.Context, folderID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, sumActiveFolderVMCapacityReservations, folderID)
	var total int32
	err := row.Scan(&total)
	return total, err
}
