// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: inventory.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createChildFolder = `-- name: CreateChildFolder :one
INSERT INTO inventory_items (parent_id, kind, name)
VALUES ($1, 'folder', $2)
RETURNING id
`

type CreateChildFolderParams struct {
	ParentID pgtype.UUID `json:"parent_id"`
	Name     string      `json:"name"`
}

func (q *Queries) CreateChildFolder(ctx context.Context, arg CreateChildFolderParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createChildFolder, arg.ParentID, arg.Name)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const createRootFolder = `-- name: CreateRootFolder :one
INSERT INTO inventory_items (parent_id, kind, name)
VALUES (NULL, 'folder', $1)
RETURNING id
`

func (q *Queries) CreateRootFolder(ctx context.Context, name string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createRootFolder, name)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const createVMItem = `-- name: CreateVMItem :one
INSERT INTO inventory_items (parent_id, kind, name)
VALUES ($1, 'vm', $2)
RETURNING id
`

type CreateVMItemParams struct {
	ParentID pgtype.UUID `json:"parent_id"`
	Name     string      `json:"name"`
}

func (q *Queries) CreateVMItem(ctx context.Context, arg CreateVMItemParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createVMItem, arg.ParentID, arg.Name)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteInventoryItem = `-- name: DeleteInventoryItem :exec
DELETE FROM inventory_items WHERE id = $1
`

func (q *Queries) DeleteInventoryItem(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteInventoryItem, id)
	return err
}

const getAllProxmoxVMNodeVMIDs = `-- name: GetAllProxmoxVMNodeVMIDs :many
SELECT pv.inventory_item_id, pv.node, pv.vmid
FROM proxmox_vms pv
`

type GetAllProxmoxVMNodeVMIDsRow struct {
	InventoryItemID pgtype.UUID `json:"inventory_item_id"`
	Node            string      `json:"node"`
	Vmid            int32       `json:"vmid"`
}

func (q *Queries) GetAllProxmoxVMNodeVMIDs(ctx context.Context) ([]GetAllProxmoxVMNodeVMIDsRow, error) {
	rows, err := q.db.Query(ctx, getAllProxmoxVMNodeVMIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllProxmoxVMNodeVMIDsRow
	for rows.Next() {
		var i GetAllProxmoxVMNodeVMIDsRow
		if err := rows.Scan(&i.InventoryItemID, &i.Node, &i.Vmid); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChildFolderByName = `-- name: GetChildFolderByName :one
SELECT id
FROM inventory_items
WHERE parent_id = $1
  AND kind = 'folder'
  AND name = $2
`

type GetChildFolderByNameParams struct {
	ParentID pgtype.UUID `json:"parent_id"`
	Name     string      `json:"name"`
}

func (q *Queries) GetChildFolderByName(ctx context.Context, arg GetChildFolderByNameParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getChildFolderByName, arg.ParentID, arg.Name)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getChildFolderIDs = `-- name: GetChildFolderIDs :many
SELECT id, name
FROM inventory_items
WHERE parent_id = $1
  AND kind = 'folder'
`

type GetChildFolderIDsRow struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
}

func (q *Queries) GetChildFolderIDs(ctx context.Context, parentID pgtype.UUID) ([]GetChildFolderIDsRow, error) {
	rows, err := q.db.Query(ctx, getChildFolderIDs, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetChildFolderIDsRow
	for rows.Next() {
		var i GetChildFolderIDsRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProxmoxVMByNodeVMID = `-- name: GetProxmoxVMByNodeVMID :one
SELECT pv.inventory_item_id,
       pv.cpu_count,
       pv.memory_mb,
       pv.disk_gb,
       ii.parent_id,
       ii.name
FROM proxmox_vms pv
JOIN inventory_items ii ON ii.id = pv.inventory_item_id
WHERE pv.node = $1 AND pv.vmid = $2
`

type GetProxmoxVMByNodeVMIDParams struct {
	Node string `json:"node"`
	Vmid int32  `json:"vmid"`
}

type GetProxmoxVMByNodeVMIDRow struct {
	InventoryItemID pgtype.UUID    `json:"inventory_item_id"`
	CpuCount        *int32         `json:"cpu_count"`
	MemoryMb        *int32         `json:"memory_mb"`
	DiskGb          pgtype.Numeric `json:"disk_gb"`
	ParentID        pgtype.UUID    `json:"parent_id"`
	Name            string         `json:"name"`
}

func (q *Queries) GetProxmoxVMByNodeVMID(ctx context.Context, arg GetProxmoxVMByNodeVMIDParams) (GetProxmoxVMByNodeVMIDRow, error) {
	row := q.db.QueryRow(ctx, getProxmoxVMByNodeVMID, arg.Node, arg.Vmid)
	var i GetProxmoxVMByNodeVMIDRow
	err := row.Scan(
		&i.InventoryItemID,
		&i.CpuCount,
		&i.MemoryMb,
		&i.DiskGb,
		&i.ParentID,
		&i.Name,
	)
	return i, err
}

const getRootFolderByName = `-- name: GetRootFolderByName :one
SELECT id
FROM inventory_items
WHERE parent_id IS NULL
  AND kind = 'folder'
  AND name = $1
`

func (q *Queries) GetRootFolderByName(ctx context.Context, name string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getRootFolderByName, name)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const insertProxmoxVM = `-- name: InsertProxmoxVM :exec
INSERT INTO proxmox_vms (inventory_item_id, node, vmid, cpu_count, memory_mb, disk_gb)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertProxmoxVMParams struct {
	InventoryItemID pgtype.UUID    `json:"inventory_item_id"`
	Node            string         `json:"node"`
	Vmid            int32          `json:"vmid"`
	CpuCount        *int32         `json:"cpu_count"`
	MemoryMb        *int32         `json:"memory_mb"`
	DiskGb          pgtype.Numeric `json:"disk_gb"`
}

func (q *Queries) InsertProxmoxVM(ctx context.Context, arg InsertProxmoxVMParams) error {
	_, err := q.db.Exec(ctx, insertProxmoxVM,
		arg.InventoryItemID,
		arg.Node,
		arg.Vmid,
		arg.CpuCount,
		arg.MemoryMb,
		arg.DiskGb,
	)
	return err
}

const updateInventoryItemName = `-- name: UpdateInventoryItemName :exec
UPDATE inventory_items
SET name = $1
WHERE id = $2
`

type UpdateInventoryItemNameParams struct {
	Name string      `json:"name"`
	ID   pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateInventoryItemName(ctx context.Context, arg UpdateInventoryItemNameParams) error {
	_, err := q.db.Exec(ctx, updateInventoryItemName, arg.Name, arg.ID)
	return err
}

const updateInventoryItemParent = `-- name: UpdateInventoryItemParent :exec
UPDATE inventory_items
SET parent_id = $1
WHERE id = $2
`

type UpdateInventoryItemParentParams struct {
	ParentID pgtype.UUID `json:"parent_id"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateInventoryItemParent(ctx context.Context, arg UpdateInventoryItemParentParams) error {
	_, err := q.db.Exec(ctx, updateInventoryItemParent, arg.ParentID, arg.ID)
	return err
}

const updateProxmoxVM = `-- name: UpdateProxmoxVM :exec
UPDATE proxmox_vms
SET cpu_count = $1, memory_mb = $2, disk_gb = $3
WHERE node = $4 AND vmid = $5
`

type UpdateProxmoxVMParams struct {
	CpuCount *int32         `json:"cpu_count"`
	MemoryMb *int32         `json:"memory_mb"`
	DiskGb   pgtype.Numeric `json:"disk_gb"`
	Node     string         `json:"node"`
	Vmid     int32          `json:"vmid"`
}

func (q *Queries) UpdateProxmoxVM(ctx context.Context, arg UpdateProxmoxVMParams) error {
	_, err := q.db.Exec(ctx, updateProxmoxVM,
		arg.CpuCount,
		arg.MemoryMb,
		arg.DiskGb,
		arg.Node,
		arg.Vmid,
	)
	return err
}
