// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: inventory.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createChildFolder = `-- name: CreateChildFolder :one
INSERT INTO inventory_items (parent_id, kind, name)
VALUES ($1, 'folder', $2)
RETURNING id
`

type CreateChildFolderParams struct {
	ParentID *uuid.UUID `json:"parent_id"`
	Name     string     `json:"name"`
}

func (q *Queries) CreateChildFolder(ctx context.Context, arg CreateChildFolderParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createChildFolder, arg.ParentID, arg.Name)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createRootFolder = `-- name: CreateRootFolder :one
INSERT INTO inventory_items (parent_id, kind, name)
VALUES (NULL, 'folder', $1)
RETURNING id
`

func (q *Queries) CreateRootFolder(ctx context.Context, name string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createRootFolder, name)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createVMItem = `-- name: CreateVMItem :one
INSERT INTO inventory_items (parent_id, kind, name)
VALUES ($1, 'vm', $2)
RETURNING id
`

type CreateVMItemParams struct {
	ParentID *uuid.UUID `json:"parent_id"`
	Name     string     `json:"name"`
}

func (q *Queries) CreateVMItem(ctx context.Context, arg CreateVMItemParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createVMItem, arg.ParentID, arg.Name)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteInventoryItem = `-- name: DeleteInventoryItem :exec
DELETE FROM inventory_items WHERE id = $1
`

func (q *Queries) DeleteInventoryItem(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteInventoryItem, id)
	return err
}

const getAllInventoryItems = `-- name: GetAllInventoryItems :many
SELECT ii.id, ii.parent_id, ii.kind, ii.name, ii.description,
       ii.vm_limit AS direct_vm_limit,
       (CASE
         WHEN ii.kind = 'folder' THEN COALESCE(inventory_folder_effective_vm_limit(ii.id), 0)
         ELSE 0
       END)::INTEGER AS effective_vm_limit,
       (CASE
         WHEN ii.kind = 'folder' THEN inventory_folder_vm_count(ii.id, NULL)
         ELSE 0
       END)::INTEGER AS vm_count,
       pv.node, pv.vmid, pv.guest_type, pv.is_template, pv.notes, pv.cpu_count, pv.memory_mb, pv.disk_gb
FROM inventory_items ii
LEFT JOIN proxmox_vms pv ON pv.inventory_item_id = ii.id
ORDER BY
  CASE WHEN ii.kind = 'folder' THEN 0 ELSE 1 END,
  lower(ii.name) ASC,
  ii.name ASC
`

type GetAllInventoryItemsRow struct {
	ID               uuid.UUID         `json:"id"`
	ParentID         *uuid.UUID        `json:"parent_id"`
	Kind             InventoryItemKind `json:"kind"`
	Name             string            `json:"name"`
	Description      *string           `json:"description"`
	DirectVmLimit    *int32            `json:"direct_vm_limit"`
	EffectiveVmLimit int32             `json:"effective_vm_limit"`
	VmCount          int32             `json:"vm_count"`
	Node             *string           `json:"node"`
	Vmid             *int32            `json:"vmid"`
	GuestType        *string           `json:"guest_type"`
	IsTemplate       *bool             `json:"is_template"`
	Notes            *string           `json:"notes"`
	CpuCount         *int32            `json:"cpu_count"`
	MemoryMb         *int32            `json:"memory_mb"`
	DiskGb           *float64          `json:"disk_gb"`
}

func (q *Queries) GetAllInventoryItems(ctx context.Context) ([]GetAllInventoryItemsRow, error) {
	rows, err := q.db.Query(ctx, getAllInventoryItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllInventoryItemsRow
	for rows.Next() {
		var i GetAllInventoryItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Kind,
			&i.Name,
			&i.Description,
			&i.DirectVmLimit,
			&i.EffectiveVmLimit,
			&i.VmCount,
			&i.Node,
			&i.Vmid,
			&i.GuestType,
			&i.IsTemplate,
			&i.Notes,
			&i.CpuCount,
			&i.MemoryMb,
			&i.DiskGb,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllProxmoxVMNodeVMIDs = `-- name: GetAllProxmoxVMNodeVMIDs :many
SELECT pv.inventory_item_id, pv.node, pv.vmid
FROM proxmox_vms pv
`

type GetAllProxmoxVMNodeVMIDsRow struct {
	InventoryItemID uuid.UUID `json:"inventory_item_id"`
	Node            string    `json:"node"`
	Vmid            int32     `json:"vmid"`
}

func (q *Queries) GetAllProxmoxVMNodeVMIDs(ctx context.Context) ([]GetAllProxmoxVMNodeVMIDsRow, error) {
	rows, err := q.db.Query(ctx, getAllProxmoxVMNodeVMIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllProxmoxVMNodeVMIDsRow
	for rows.Next() {
		var i GetAllProxmoxVMNodeVMIDsRow
		if err := rows.Scan(&i.InventoryItemID, &i.Node, &i.Vmid); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChildFolderByName = `-- name: GetChildFolderByName :one
SELECT id
FROM inventory_items
WHERE parent_id = $1
  AND kind = 'folder'
  AND name = $2
`

type GetChildFolderByNameParams struct {
	ParentID *uuid.UUID `json:"parent_id"`
	Name     string     `json:"name"`
}

func (q *Queries) GetChildFolderByName(ctx context.Context, arg GetChildFolderByNameParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getChildFolderByName, arg.ParentID, arg.Name)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getChildFolderIDs = `-- name: GetChildFolderIDs :many
SELECT id, name
FROM inventory_items
WHERE parent_id = $1
  AND kind = 'folder'
`

type GetChildFolderIDsRow struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) GetChildFolderIDs(ctx context.Context, parentID *uuid.UUID) ([]GetChildFolderIDsRow, error) {
	rows, err := q.db.Query(ctx, getChildFolderIDs, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetChildFolderIDsRow
	for rows.Next() {
		var i GetChildFolderIDsRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInventoryItemByID = `-- name: GetInventoryItemByID :one
SELECT ii.id, ii.parent_id, ii.kind, ii.name, ii.description, ii.inherit_permissions,
       ii.vm_limit AS direct_vm_limit,
       (CASE
         WHEN ii.kind = 'folder' THEN COALESCE(inventory_folder_effective_vm_limit(ii.id), 0)
         ELSE 0
       END)::INTEGER AS effective_vm_limit,
       (CASE
         WHEN ii.kind = 'folder' THEN inventory_folder_vm_count(ii.id, NULL)
         ELSE 0
       END)::INTEGER AS vm_count,
       pv.node, pv.vmid, pv.guest_type, pv.is_template, pv.notes, pv.cpu_count, pv.memory_mb, pv.disk_gb
FROM inventory_items ii
LEFT JOIN proxmox_vms pv ON pv.inventory_item_id = ii.id
WHERE ii.id = $1
`

type GetInventoryItemByIDRow struct {
	ID                 uuid.UUID         `json:"id"`
	ParentID           *uuid.UUID        `json:"parent_id"`
	Kind               InventoryItemKind `json:"kind"`
	Name               string            `json:"name"`
	Description        *string           `json:"description"`
	InheritPermissions bool              `json:"inherit_permissions"`
	DirectVmLimit      *int32            `json:"direct_vm_limit"`
	EffectiveVmLimit   int32             `json:"effective_vm_limit"`
	VmCount            int32             `json:"vm_count"`
	Node               *string           `json:"node"`
	Vmid               *int32            `json:"vmid"`
	GuestType          *string           `json:"guest_type"`
	IsTemplate         *bool             `json:"is_template"`
	Notes              *string           `json:"notes"`
	CpuCount           *int32            `json:"cpu_count"`
	MemoryMb           *int32            `json:"memory_mb"`
	DiskGb             *float64          `json:"disk_gb"`
}

func (q *Queries) GetInventoryItemByID(ctx context.Context, id uuid.UUID) (GetInventoryItemByIDRow, error) {
	row := q.db.QueryRow(ctx, getInventoryItemByID, id)
	var i GetInventoryItemByIDRow
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Kind,
		&i.Name,
		&i.Description,
		&i.InheritPermissions,
		&i.DirectVmLimit,
		&i.EffectiveVmLimit,
		&i.VmCount,
		&i.Node,
		&i.Vmid,
		&i.GuestType,
		&i.IsTemplate,
		&i.Notes,
		&i.CpuCount,
		&i.MemoryMb,
		&i.DiskGb,
	)
	return i, err
}

const getInventoryItemForUpdate = `-- name: GetInventoryItemForUpdate :one
SELECT id, parent_id, kind, name, inherit_permissions, vm_limit
FROM inventory_items
WHERE id = $1
FOR UPDATE
`

type GetInventoryItemForUpdateRow struct {
	ID                 uuid.UUID         `json:"id"`
	ParentID           *uuid.UUID        `json:"parent_id"`
	Kind               InventoryItemKind `json:"kind"`
	Name               string            `json:"name"`
	InheritPermissions bool              `json:"inherit_permissions"`
	VmLimit            *int32            `json:"vm_limit"`
}

func (q *Queries) GetInventoryItemForUpdate(ctx context.Context, id uuid.UUID) (GetInventoryItemForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getInventoryItemForUpdate, id)
	var i GetInventoryItemForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Kind,
		&i.Name,
		&i.InheritPermissions,
		&i.VmLimit,
	)
	return i, err
}

const getProxmoxVMByInventoryItemID = `-- name: GetProxmoxVMByInventoryItemID :one
SELECT inventory_item_id,
       node,
       vmid,
       guest_type,
       upstream_uuid,
       is_template,
       notes,
       cpu_count,
       memory_mb,
       disk_gb
FROM proxmox_vms
WHERE inventory_item_id = $1
`

type GetProxmoxVMByInventoryItemIDRow struct {
	InventoryItemID uuid.UUID `json:"inventory_item_id"`
	Node            string    `json:"node"`
	Vmid            int32     `json:"vmid"`
	GuestType       string    `json:"guest_type"`
	UpstreamUuid    uuid.UUID `json:"upstream_uuid"`
	IsTemplate      bool      `json:"is_template"`
	Notes           *string   `json:"notes"`
	CpuCount        *int32    `json:"cpu_count"`
	MemoryMb        *int32    `json:"memory_mb"`
	DiskGb          *float64  `json:"disk_gb"`
}

func (q *Queries) GetProxmoxVMByInventoryItemID(ctx context.Context, inventoryItemID uuid.UUID) (GetProxmoxVMByInventoryItemIDRow, error) {
	row := q.db.QueryRow(ctx, getProxmoxVMByInventoryItemID, inventoryItemID)
	var i GetProxmoxVMByInventoryItemIDRow
	err := row.Scan(
		&i.InventoryItemID,
		&i.Node,
		&i.Vmid,
		&i.GuestType,
		&i.UpstreamUuid,
		&i.IsTemplate,
		&i.Notes,
		&i.CpuCount,
		&i.MemoryMb,
		&i.DiskGb,
	)
	return i, err
}

const getProxmoxVMByInventoryItemIDForUpdate = `-- name: GetProxmoxVMByInventoryItemIDForUpdate :one
SELECT inventory_item_id,
       node,
       vmid,
       guest_type,
       upstream_uuid,
       is_template,
       notes,
       cpu_count,
       memory_mb,
       disk_gb
FROM proxmox_vms
WHERE inventory_item_id = $1
FOR UPDATE
`

type GetProxmoxVMByInventoryItemIDForUpdateRow struct {
	InventoryItemID uuid.UUID `json:"inventory_item_id"`
	Node            string    `json:"node"`
	Vmid            int32     `json:"vmid"`
	GuestType       string    `json:"guest_type"`
	UpstreamUuid    uuid.UUID `json:"upstream_uuid"`
	IsTemplate      bool      `json:"is_template"`
	Notes           *string   `json:"notes"`
	CpuCount        *int32    `json:"cpu_count"`
	MemoryMb        *int32    `json:"memory_mb"`
	DiskGb          *float64  `json:"disk_gb"`
}

func (q *Queries) GetProxmoxVMByInventoryItemIDForUpdate(ctx context.Context, inventoryItemID uuid.UUID) (GetProxmoxVMByInventoryItemIDForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getProxmoxVMByInventoryItemIDForUpdate, inventoryItemID)
	var i GetProxmoxVMByInventoryItemIDForUpdateRow
	err := row.Scan(
		&i.InventoryItemID,
		&i.Node,
		&i.Vmid,
		&i.GuestType,
		&i.UpstreamUuid,
		&i.IsTemplate,
		&i.Notes,
		&i.CpuCount,
		&i.MemoryMb,
		&i.DiskGb,
	)
	return i, err
}

const getProxmoxVMByNodeVMID = `-- name: GetProxmoxVMByNodeVMID :one
SELECT pv.inventory_item_id,
       pv.node,
       pv.vmid,
       pv.guest_type,
       pv.upstream_uuid,
       pv.cpu_count,
       pv.memory_mb,
       pv.disk_gb,
       ii.parent_id,
       ii.name
FROM proxmox_vms pv
JOIN inventory_items ii ON ii.id = pv.inventory_item_id
WHERE pv.node = $1 AND pv.vmid = $2
`

type GetProxmoxVMByNodeVMIDParams struct {
	Node string `json:"node"`
	Vmid int32  `json:"vmid"`
}

type GetProxmoxVMByNodeVMIDRow struct {
	InventoryItemID uuid.UUID  `json:"inventory_item_id"`
	Node            string     `json:"node"`
	Vmid            int32      `json:"vmid"`
	GuestType       string     `json:"guest_type"`
	UpstreamUuid    uuid.UUID  `json:"upstream_uuid"`
	CpuCount        *int32     `json:"cpu_count"`
	MemoryMb        *int32     `json:"memory_mb"`
	DiskGb          *float64   `json:"disk_gb"`
	ParentID        *uuid.UUID `json:"parent_id"`
	Name            string     `json:"name"`
}

func (q *Queries) GetProxmoxVMByNodeVMID(ctx context.Context, arg GetProxmoxVMByNodeVMIDParams) (GetProxmoxVMByNodeVMIDRow, error) {
	row := q.db.QueryRow(ctx, getProxmoxVMByNodeVMID, arg.Node, arg.Vmid)
	var i GetProxmoxVMByNodeVMIDRow
	err := row.Scan(
		&i.InventoryItemID,
		&i.Node,
		&i.Vmid,
		&i.GuestType,
		&i.UpstreamUuid,
		&i.CpuCount,
		&i.MemoryMb,
		&i.DiskGb,
		&i.ParentID,
		&i.Name,
	)
	return i, err
}

const getProxmoxVMByUpstreamUUID = `-- name: GetProxmoxVMByUpstreamUUID :one
SELECT pv.inventory_item_id,
       pv.node,
       pv.vmid,
       pv.guest_type,
       pv.upstream_uuid,
       pv.cpu_count,
       pv.memory_mb,
       pv.disk_gb,
       ii.parent_id,
       ii.name
FROM proxmox_vms pv
JOIN inventory_items ii ON ii.id = pv.inventory_item_id
WHERE pv.upstream_uuid = $1
`

type GetProxmoxVMByUpstreamUUIDRow struct {
	InventoryItemID uuid.UUID  `json:"inventory_item_id"`
	Node            string     `json:"node"`
	Vmid            int32      `json:"vmid"`
	GuestType       string     `json:"guest_type"`
	UpstreamUuid    uuid.UUID  `json:"upstream_uuid"`
	CpuCount        *int32     `json:"cpu_count"`
	MemoryMb        *int32     `json:"memory_mb"`
	DiskGb          *float64   `json:"disk_gb"`
	ParentID        *uuid.UUID `json:"parent_id"`
	Name            string     `json:"name"`
}

func (q *Queries) GetProxmoxVMByUpstreamUUID(ctx context.Context, upstreamUuid uuid.UUID) (GetProxmoxVMByUpstreamUUIDRow, error) {
	row := q.db.QueryRow(ctx, getProxmoxVMByUpstreamUUID, upstreamUuid)
	var i GetProxmoxVMByUpstreamUUIDRow
	err := row.Scan(
		&i.InventoryItemID,
		&i.Node,
		&i.Vmid,
		&i.GuestType,
		&i.UpstreamUuid,
		&i.CpuCount,
		&i.MemoryMb,
		&i.DiskGb,
		&i.ParentID,
		&i.Name,
	)
	return i, err
}

const getRootFolderByName = `-- name: GetRootFolderByName :one

SELECT id
FROM inventory_items
WHERE parent_id IS NULL
  AND kind = 'folder'
  AND name = $1
`

// ---------------------------------------------------------------------------
// Sync queries
// ---------------------------------------------------------------------------
func (q *Queries) GetRootFolderByName(ctx context.Context, name string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getRootFolderByName, name)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertProxmoxVM = `-- name: InsertProxmoxVM :exec
INSERT INTO proxmox_vms (inventory_item_id, node, vmid, guest_type, upstream_uuid, is_template, cpu_count, memory_mb, disk_gb)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertProxmoxVMParams struct {
	InventoryItemID uuid.UUID `json:"inventory_item_id"`
	Node            string    `json:"node"`
	Vmid            int32     `json:"vmid"`
	GuestType       string    `json:"guest_type"`
	UpstreamUuid    uuid.UUID `json:"upstream_uuid"`
	IsTemplate      bool      `json:"is_template"`
	CpuCount        *int32    `json:"cpu_count"`
	MemoryMb        *int32    `json:"memory_mb"`
	DiskGb          *float64  `json:"disk_gb"`
}

func (q *Queries) InsertProxmoxVM(ctx context.Context, arg InsertProxmoxVMParams) error {
	_, err := q.db.Exec(ctx, insertProxmoxVM,
		arg.InventoryItemID,
		arg.Node,
		arg.Vmid,
		arg.GuestType,
		arg.UpstreamUuid,
		arg.IsTemplate,
		arg.CpuCount,
		arg.MemoryMb,
		arg.DiskGb,
	)
	return err
}

const listInventoryDeletionBlockersInSubtree = `-- name: ListInventoryDeletionBlockersInSubtree :many
WITH RECURSIVE subtree AS (
    SELECT inventory_items.id
    FROM inventory_items
    WHERE inventory_items.id = $1

    UNION ALL

    SELECT child.id
    FROM inventory_items child
    JOIN subtree parent ON child.parent_id = parent.id
)
SELECT pp.source_folder_id AS inventory_item_id,
       'published pod source folder' AS blocker_type,
       pp.title AS blocker_name
FROM published_pods pp
WHERE pp.source_folder_id IN (SELECT id FROM subtree)

UNION ALL

SELECT ppv.source_inventory_item_id AS inventory_item_id,
       'published pod VM' AS blocker_type,
       pp.title || ' / ' || ppv.name AS blocker_name
FROM published_pod_vms ppv
JOIN published_pods pp ON pp.id = ppv.pod_id
WHERE ppv.source_inventory_item_id IN (SELECT id FROM subtree)

UNION ALL

SELECT ir.inventory_item_id AS inventory_item_id,
       'inventory request' AS blocker_type,
       r.kind AS blocker_name
FROM inventory_requests ir
JOIN requests r ON r.id = ir.request_id
WHERE ir.inventory_item_id IN (SELECT id FROM subtree)
ORDER BY blocker_type, blocker_name
`

type ListInventoryDeletionBlockersInSubtreeRow struct {
	InventoryItemID uuid.UUID `json:"inventory_item_id"`
	BlockerType     string    `json:"blocker_type"`
	BlockerName     string    `json:"blocker_name"`
}

func (q *Queries) ListInventoryDeletionBlockersInSubtree(ctx context.Context, id uuid.UUID) ([]ListInventoryDeletionBlockersInSubtreeRow, error) {
	rows, err := q.db.Query(ctx, listInventoryDeletionBlockersInSubtree, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInventoryDeletionBlockersInSubtreeRow
	for rows.Next() {
		var i ListInventoryDeletionBlockersInSubtreeRow
		if err := rows.Scan(&i.InventoryItemID, &i.BlockerType, &i.BlockerName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const normalizeInventoryItemInheritance = `-- name: NormalizeInventoryItemInheritance :execrows
UPDATE inventory_items
SET inherit_permissions = true
WHERE inherit_permissions = false
`

func (q *Queries) NormalizeInventoryItemInheritance(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, normalizeInventoryItemInheritance)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateInventoryFolderDescription = `-- name: UpdateInventoryFolderDescription :exec
UPDATE inventory_items
SET description = $1
WHERE id = $2
  AND kind = 'folder'
`

type UpdateInventoryFolderDescriptionParams struct {
	Description *string   `json:"description"`
	ID          uuid.UUID `json:"id"`
}

func (q *Queries) UpdateInventoryFolderDescription(ctx context.Context, arg UpdateInventoryFolderDescriptionParams) error {
	_, err := q.db.Exec(ctx, updateInventoryFolderDescription, arg.Description, arg.ID)
	return err
}

const updateInventoryFolderDetails = `-- name: UpdateInventoryFolderDetails :exec

UPDATE inventory_items
SET name = $1,
    description = $2
WHERE id = $3
  AND kind = 'folder'
`

type UpdateInventoryFolderDetailsParams struct {
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	ID          uuid.UUID `json:"id"`
}

// ---------------------------------------------------------------------------
// Read queries for API endpoints
// ---------------------------------------------------------------------------
func (q *Queries) UpdateInventoryFolderDetails(ctx context.Context, arg UpdateInventoryFolderDetailsParams) error {
	_, err := q.db.Exec(ctx, updateInventoryFolderDetails, arg.Name, arg.Description, arg.ID)
	return err
}

const updateInventoryFolderVMLimit = `-- name: UpdateInventoryFolderVMLimit :exec
UPDATE inventory_items
SET vm_limit = $1
WHERE id = $2
  AND kind = 'folder'
`

type UpdateInventoryFolderVMLimitParams struct {
	VmLimit *int32    `json:"vm_limit"`
	ID      uuid.UUID `json:"id"`
}

func (q *Queries) UpdateInventoryFolderVMLimit(ctx context.Context, arg UpdateInventoryFolderVMLimitParams) error {
	_, err := q.db.Exec(ctx, updateInventoryFolderVMLimit, arg.VmLimit, arg.ID)
	return err
}

const updateInventoryItemInheritance = `-- name: UpdateInventoryItemInheritance :exec
UPDATE inventory_items
SET inherit_permissions = $1
WHERE id = $2
`

type UpdateInventoryItemInheritanceParams struct {
	InheritPermissions bool      `json:"inherit_permissions"`
	ID                 uuid.UUID `json:"id"`
}

func (q *Queries) UpdateInventoryItemInheritance(ctx context.Context, arg UpdateInventoryItemInheritanceParams) error {
	_, err := q.db.Exec(ctx, updateInventoryItemInheritance, arg.InheritPermissions, arg.ID)
	return err
}

const updateInventoryItemName = `-- name: UpdateInventoryItemName :exec
UPDATE inventory_items
SET name = $1
WHERE id = $2
`

type UpdateInventoryItemNameParams struct {
	Name string    `json:"name"`
	ID   uuid.UUID `json:"id"`
}

func (q *Queries) UpdateInventoryItemName(ctx context.Context, arg UpdateInventoryItemNameParams) error {
	_, err := q.db.Exec(ctx, updateInventoryItemName, arg.Name, arg.ID)
	return err
}

const updateInventoryItemParent = `-- name: UpdateInventoryItemParent :exec
UPDATE inventory_items
SET parent_id = $1
WHERE id = $2
`

type UpdateInventoryItemParentParams struct {
	ParentID *uuid.UUID `json:"parent_id"`
	ID       uuid.UUID  `json:"id"`
}

func (q *Queries) UpdateInventoryItemParent(ctx context.Context, arg UpdateInventoryItemParentParams) error {
	_, err := q.db.Exec(ctx, updateInventoryItemParent, arg.ParentID, arg.ID)
	return err
}

const updateProxmoxVM = `-- name: UpdateProxmoxVM :exec
UPDATE proxmox_vms
SET node = $2,
    vmid = $3,
    guest_type = $4,
    upstream_uuid = $5,
    is_template = $6,
    cpu_count = $7,
    memory_mb = $8,
    disk_gb = $9
WHERE inventory_item_id = $1
`

type UpdateProxmoxVMParams struct {
	InventoryItemID uuid.UUID `json:"inventory_item_id"`
	Node            string    `json:"node"`
	Vmid            int32     `json:"vmid"`
	GuestType       string    `json:"guest_type"`
	UpstreamUuid    uuid.UUID `json:"upstream_uuid"`
	IsTemplate      bool      `json:"is_template"`
	CpuCount        *int32    `json:"cpu_count"`
	MemoryMb        *int32    `json:"memory_mb"`
	DiskGb          *float64  `json:"disk_gb"`
}

func (q *Queries) UpdateProxmoxVM(ctx context.Context, arg UpdateProxmoxVMParams) error {
	_, err := q.db.Exec(ctx, updateProxmoxVM,
		arg.InventoryItemID,
		arg.Node,
		arg.Vmid,
		arg.GuestType,
		arg.UpstreamUuid,
		arg.IsTemplate,
		arg.CpuCount,
		arg.MemoryMb,
		arg.DiskGb,
	)
	return err
}

const updateProxmoxVMHardwareSummaryByItemID = `-- name: UpdateProxmoxVMHardwareSummaryByItemID :exec
UPDATE proxmox_vms
SET cpu_count = $1,
    memory_mb = $2,
    disk_gb = $3
WHERE inventory_item_id = $4
`

type UpdateProxmoxVMHardwareSummaryByItemIDParams struct {
	CpuCount        *int32    `json:"cpu_count"`
	MemoryMb        *int32    `json:"memory_mb"`
	DiskGb          *float64  `json:"disk_gb"`
	InventoryItemID uuid.UUID `json:"inventory_item_id"`
}

func (q *Queries) UpdateProxmoxVMHardwareSummaryByItemID(ctx context.Context, arg UpdateProxmoxVMHardwareSummaryByItemIDParams) error {
	_, err := q.db.Exec(ctx, updateProxmoxVMHardwareSummaryByItemID,
		arg.CpuCount,
		arg.MemoryMb,
		arg.DiskGb,
		arg.InventoryItemID,
	)
	return err
}

const updateProxmoxVMIsTemplateByItemID = `-- name: UpdateProxmoxVMIsTemplateByItemID :exec
UPDATE proxmox_vms
SET is_template = true
WHERE inventory_item_id = $1
`

func (q *Queries) UpdateProxmoxVMIsTemplateByItemID(ctx context.Context, inventoryItemID uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateProxmoxVMIsTemplateByItemID, inventoryItemID)
	return err
}

const updateProxmoxVMNotesByItemID = `-- name: UpdateProxmoxVMNotesByItemID :exec
UPDATE proxmox_vms
SET notes = $1
WHERE inventory_item_id = $2
`

type UpdateProxmoxVMNotesByItemIDParams struct {
	Notes           *string   `json:"notes"`
	InventoryItemID uuid.UUID `json:"inventory_item_id"`
}

func (q *Queries) UpdateProxmoxVMNotesByItemID(ctx context.Context, arg UpdateProxmoxVMNotesByItemIDParams) error {
	_, err := q.db.Exec(ctx, updateProxmoxVMNotesByItemID, arg.Notes, arg.InventoryItemID)
	return err
}
