// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: inventory.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createChildFolder = `-- name: CreateChildFolder :one
INSERT INTO inventory_items (parent_id, kind, name)
VALUES ($1, 'folder', $2)
RETURNING id
`

type CreateChildFolderParams struct {
	ParentID *uuid.UUID `json:"parent_id"`
	Name     string     `json:"name"`
}

func (q *Queries) CreateChildFolder(ctx context.Context, arg CreateChildFolderParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createChildFolder, arg.ParentID, arg.Name)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createRootFolder = `-- name: CreateRootFolder :one
INSERT INTO inventory_items (parent_id, kind, name)
VALUES (NULL, 'folder', $1)
RETURNING id
`

func (q *Queries) CreateRootFolder(ctx context.Context, name string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createRootFolder, name)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createVMItem = `-- name: CreateVMItem :one
INSERT INTO inventory_items (parent_id, kind, name)
VALUES ($1, 'vm', $2)
RETURNING id
`

type CreateVMItemParams struct {
	ParentID *uuid.UUID `json:"parent_id"`
	Name     string     `json:"name"`
}

func (q *Queries) CreateVMItem(ctx context.Context, arg CreateVMItemParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createVMItem, arg.ParentID, arg.Name)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteInventoryItem = `-- name: DeleteInventoryItem :exec
DELETE FROM inventory_items WHERE id = $1
`

func (q *Queries) DeleteInventoryItem(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteInventoryItem, id)
	return err
}

const deleteInventoryItemByProxmoxVM = `-- name: DeleteInventoryItemByProxmoxVM :exec
DELETE FROM inventory_items
WHERE id = (SELECT inventory_item_id FROM proxmox_vms WHERE node = $1 AND vmid = $2)
`

type DeleteInventoryItemByProxmoxVMParams struct {
	Node string `json:"node"`
	Vmid int32  `json:"vmid"`
}

func (q *Queries) DeleteInventoryItemByProxmoxVM(ctx context.Context, arg DeleteInventoryItemByProxmoxVMParams) error {
	_, err := q.db.Exec(ctx, deleteInventoryItemByProxmoxVM, arg.Node, arg.Vmid)
	return err
}

const getAllInventoryItems = `-- name: GetAllInventoryItems :many

SELECT ii.id, ii.parent_id, ii.kind, ii.name,
       pv.node, pv.vmid, pv.is_template, pv.notes, pv.cpu_count, pv.memory_mb, pv.disk_gb
FROM inventory_items ii
LEFT JOIN proxmox_vms pv ON pv.inventory_item_id = ii.id
ORDER BY
  CASE WHEN ii.kind = 'folder' THEN 0 ELSE 1 END,
  lower(ii.name) ASC,
  ii.name ASC
`

type GetAllInventoryItemsRow struct {
	ID         uuid.UUID         `json:"id"`
	ParentID   *uuid.UUID        `json:"parent_id"`
	Kind       InventoryItemKind `json:"kind"`
	Name       string            `json:"name"`
	Node       *string           `json:"node"`
	Vmid       *int32            `json:"vmid"`
	IsTemplate *bool             `json:"is_template"`
	Notes      *string           `json:"notes"`
	CpuCount   *int32            `json:"cpu_count"`
	MemoryMb   *int32            `json:"memory_mb"`
	DiskGb     *float64          `json:"disk_gb"`
}

// ---------------------------------------------------------------------------
// Read queries for API endpoints
// ---------------------------------------------------------------------------
func (q *Queries) GetAllInventoryItems(ctx context.Context) ([]GetAllInventoryItemsRow, error) {
	rows, err := q.db.Query(ctx, getAllInventoryItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllInventoryItemsRow
	for rows.Next() {
		var i GetAllInventoryItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Kind,
			&i.Name,
			&i.Node,
			&i.Vmid,
			&i.IsTemplate,
			&i.Notes,
			&i.CpuCount,
			&i.MemoryMb,
			&i.DiskGb,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllProxmoxVMNodeVMIDs = `-- name: GetAllProxmoxVMNodeVMIDs :many
SELECT pv.inventory_item_id, pv.node, pv.vmid
FROM proxmox_vms pv
`

type GetAllProxmoxVMNodeVMIDsRow struct {
	InventoryItemID uuid.UUID `json:"inventory_item_id"`
	Node            string    `json:"node"`
	Vmid            int32     `json:"vmid"`
}

func (q *Queries) GetAllProxmoxVMNodeVMIDs(ctx context.Context) ([]GetAllProxmoxVMNodeVMIDsRow, error) {
	rows, err := q.db.Query(ctx, getAllProxmoxVMNodeVMIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllProxmoxVMNodeVMIDsRow
	for rows.Next() {
		var i GetAllProxmoxVMNodeVMIDsRow
		if err := rows.Scan(&i.InventoryItemID, &i.Node, &i.Vmid); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChildFolderByName = `-- name: GetChildFolderByName :one
SELECT id
FROM inventory_items
WHERE parent_id = $1
  AND kind = 'folder'
  AND name = $2
`

type GetChildFolderByNameParams struct {
	ParentID *uuid.UUID `json:"parent_id"`
	Name     string     `json:"name"`
}

func (q *Queries) GetChildFolderByName(ctx context.Context, arg GetChildFolderByNameParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getChildFolderByName, arg.ParentID, arg.Name)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getChildFolderIDs = `-- name: GetChildFolderIDs :many
SELECT id, name
FROM inventory_items
WHERE parent_id = $1
  AND kind = 'folder'
`

type GetChildFolderIDsRow struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) GetChildFolderIDs(ctx context.Context, parentID *uuid.UUID) ([]GetChildFolderIDsRow, error) {
	rows, err := q.db.Query(ctx, getChildFolderIDs, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetChildFolderIDsRow
	for rows.Next() {
		var i GetChildFolderIDsRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInventoryItemByID = `-- name: GetInventoryItemByID :one
SELECT ii.id, ii.parent_id, ii.kind, ii.name, ii.inherit_permissions,
       pv.node, pv.vmid, pv.is_template, pv.notes, pv.cpu_count, pv.memory_mb, pv.disk_gb
FROM inventory_items ii
LEFT JOIN proxmox_vms pv ON pv.inventory_item_id = ii.id
WHERE ii.id = $1
`

type GetInventoryItemByIDRow struct {
	ID                 uuid.UUID         `json:"id"`
	ParentID           *uuid.UUID        `json:"parent_id"`
	Kind               InventoryItemKind `json:"kind"`
	Name               string            `json:"name"`
	InheritPermissions bool              `json:"inherit_permissions"`
	Node               *string           `json:"node"`
	Vmid               *int32            `json:"vmid"`
	IsTemplate         *bool             `json:"is_template"`
	Notes              *string           `json:"notes"`
	CpuCount           *int32            `json:"cpu_count"`
	MemoryMb           *int32            `json:"memory_mb"`
	DiskGb             *float64          `json:"disk_gb"`
}

func (q *Queries) GetInventoryItemByID(ctx context.Context, id uuid.UUID) (GetInventoryItemByIDRow, error) {
	row := q.db.QueryRow(ctx, getInventoryItemByID, id)
	var i GetInventoryItemByIDRow
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Kind,
		&i.Name,
		&i.InheritPermissions,
		&i.Node,
		&i.Vmid,
		&i.IsTemplate,
		&i.Notes,
		&i.CpuCount,
		&i.MemoryMb,
		&i.DiskGb,
	)
	return i, err
}

const getInventoryItemForUpdate = `-- name: GetInventoryItemForUpdate :one
SELECT id, parent_id, kind, name, inherit_permissions
FROM inventory_items
WHERE id = $1
FOR UPDATE
`

type GetInventoryItemForUpdateRow struct {
	ID                 uuid.UUID         `json:"id"`
	ParentID           *uuid.UUID        `json:"parent_id"`
	Kind               InventoryItemKind `json:"kind"`
	Name               string            `json:"name"`
	InheritPermissions bool              `json:"inherit_permissions"`
}

func (q *Queries) GetInventoryItemForUpdate(ctx context.Context, id uuid.UUID) (GetInventoryItemForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getInventoryItemForUpdate, id)
	var i GetInventoryItemForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Kind,
		&i.Name,
		&i.InheritPermissions,
	)
	return i, err
}

const getProxmoxVMByNodeVMID = `-- name: GetProxmoxVMByNodeVMID :one
SELECT pv.inventory_item_id,
       pv.cpu_count,
       pv.memory_mb,
       pv.disk_gb,
       ii.parent_id,
       ii.name
FROM proxmox_vms pv
JOIN inventory_items ii ON ii.id = pv.inventory_item_id
WHERE pv.node = $1 AND pv.vmid = $2
`

type GetProxmoxVMByNodeVMIDParams struct {
	Node string `json:"node"`
	Vmid int32  `json:"vmid"`
}

type GetProxmoxVMByNodeVMIDRow struct {
	InventoryItemID uuid.UUID  `json:"inventory_item_id"`
	CpuCount        *int32     `json:"cpu_count"`
	MemoryMb        *int32     `json:"memory_mb"`
	DiskGb          *float64   `json:"disk_gb"`
	ParentID        *uuid.UUID `json:"parent_id"`
	Name            string     `json:"name"`
}

func (q *Queries) GetProxmoxVMByNodeVMID(ctx context.Context, arg GetProxmoxVMByNodeVMIDParams) (GetProxmoxVMByNodeVMIDRow, error) {
	row := q.db.QueryRow(ctx, getProxmoxVMByNodeVMID, arg.Node, arg.Vmid)
	var i GetProxmoxVMByNodeVMIDRow
	err := row.Scan(
		&i.InventoryItemID,
		&i.CpuCount,
		&i.MemoryMb,
		&i.DiskGb,
		&i.ParentID,
		&i.Name,
	)
	return i, err
}

const getRootFolderByName = `-- name: GetRootFolderByName :one

SELECT id
FROM inventory_items
WHERE parent_id IS NULL
  AND kind = 'folder'
  AND name = $1
`

// ---------------------------------------------------------------------------
// Sync queries
// ---------------------------------------------------------------------------
func (q *Queries) GetRootFolderByName(ctx context.Context, name string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getRootFolderByName, name)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertProxmoxVM = `-- name: InsertProxmoxVM :exec
INSERT INTO proxmox_vms (inventory_item_id, node, vmid, is_template, cpu_count, memory_mb, disk_gb)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertProxmoxVMParams struct {
	InventoryItemID uuid.UUID `json:"inventory_item_id"`
	Node            string    `json:"node"`
	Vmid            int32     `json:"vmid"`
	IsTemplate      bool      `json:"is_template"`
	CpuCount        *int32    `json:"cpu_count"`
	MemoryMb        *int32    `json:"memory_mb"`
	DiskGb          *float64  `json:"disk_gb"`
}

func (q *Queries) InsertProxmoxVM(ctx context.Context, arg InsertProxmoxVMParams) error {
	_, err := q.db.Exec(ctx, insertProxmoxVM,
		arg.InventoryItemID,
		arg.Node,
		arg.Vmid,
		arg.IsTemplate,
		arg.CpuCount,
		arg.MemoryMb,
		arg.DiskGb,
	)
	return err
}

const normalizeInventoryItemInheritance = `-- name: NormalizeInventoryItemInheritance :execrows
UPDATE inventory_items
SET inherit_permissions = true
WHERE inherit_permissions = false
`

func (q *Queries) NormalizeInventoryItemInheritance(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, normalizeInventoryItemInheritance)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateInventoryItemInheritance = `-- name: UpdateInventoryItemInheritance :exec
UPDATE inventory_items
SET inherit_permissions = $1
WHERE id = $2
`

type UpdateInventoryItemInheritanceParams struct {
	InheritPermissions bool      `json:"inherit_permissions"`
	ID                 uuid.UUID `json:"id"`
}

func (q *Queries) UpdateInventoryItemInheritance(ctx context.Context, arg UpdateInventoryItemInheritanceParams) error {
	_, err := q.db.Exec(ctx, updateInventoryItemInheritance, arg.InheritPermissions, arg.ID)
	return err
}

const updateInventoryItemName = `-- name: UpdateInventoryItemName :exec
UPDATE inventory_items
SET name = $1
WHERE id = $2
`

type UpdateInventoryItemNameParams struct {
	Name string    `json:"name"`
	ID   uuid.UUID `json:"id"`
}

func (q *Queries) UpdateInventoryItemName(ctx context.Context, arg UpdateInventoryItemNameParams) error {
	_, err := q.db.Exec(ctx, updateInventoryItemName, arg.Name, arg.ID)
	return err
}

const updateInventoryItemNameByProxmoxVM = `-- name: UpdateInventoryItemNameByProxmoxVM :exec
UPDATE inventory_items SET name = $1
WHERE id = (SELECT inventory_item_id FROM proxmox_vms WHERE node = $2 AND vmid = $3)
`

type UpdateInventoryItemNameByProxmoxVMParams struct {
	Name string `json:"name"`
	Node string `json:"node"`
	Vmid int32  `json:"vmid"`
}

func (q *Queries) UpdateInventoryItemNameByProxmoxVM(ctx context.Context, arg UpdateInventoryItemNameByProxmoxVMParams) error {
	_, err := q.db.Exec(ctx, updateInventoryItemNameByProxmoxVM, arg.Name, arg.Node, arg.Vmid)
	return err
}

const updateInventoryItemParent = `-- name: UpdateInventoryItemParent :exec
UPDATE inventory_items
SET parent_id = $1
WHERE id = $2
`

type UpdateInventoryItemParentParams struct {
	ParentID *uuid.UUID `json:"parent_id"`
	ID       uuid.UUID  `json:"id"`
}

func (q *Queries) UpdateInventoryItemParent(ctx context.Context, arg UpdateInventoryItemParentParams) error {
	_, err := q.db.Exec(ctx, updateInventoryItemParent, arg.ParentID, arg.ID)
	return err
}

const updateProxmoxVM = `-- name: UpdateProxmoxVM :exec
UPDATE proxmox_vms
SET is_template = $1, cpu_count = $2, memory_mb = $3, disk_gb = $4
WHERE node = $5 AND vmid = $6
`

type UpdateProxmoxVMParams struct {
	IsTemplate bool     `json:"is_template"`
	CpuCount   *int32   `json:"cpu_count"`
	MemoryMb   *int32   `json:"memory_mb"`
	DiskGb     *float64 `json:"disk_gb"`
	Node       string   `json:"node"`
	Vmid       int32    `json:"vmid"`
}

func (q *Queries) UpdateProxmoxVM(ctx context.Context, arg UpdateProxmoxVMParams) error {
	_, err := q.db.Exec(ctx, updateProxmoxVM,
		arg.IsTemplate,
		arg.CpuCount,
		arg.MemoryMb,
		arg.DiskGb,
		arg.Node,
		arg.Vmid,
	)
	return err
}

const updateProxmoxVMIsTemplate = `-- name: UpdateProxmoxVMIsTemplate :exec
UPDATE proxmox_vms SET is_template = true WHERE node = $1 AND vmid = $2
`

type UpdateProxmoxVMIsTemplateParams struct {
	Node string `json:"node"`
	Vmid int32  `json:"vmid"`
}

func (q *Queries) UpdateProxmoxVMIsTemplate(ctx context.Context, arg UpdateProxmoxVMIsTemplateParams) error {
	_, err := q.db.Exec(ctx, updateProxmoxVMIsTemplate, arg.Node, arg.Vmid)
	return err
}

const updateProxmoxVMNotesByNodeVMID = `-- name: UpdateProxmoxVMNotesByNodeVMID :exec
UPDATE proxmox_vms
SET notes = $1
WHERE node = $2 AND vmid = $3
`

type UpdateProxmoxVMNotesByNodeVMIDParams struct {
	Notes *string `json:"notes"`
	Node  string  `json:"node"`
	Vmid  int32   `json:"vmid"`
}

func (q *Queries) UpdateProxmoxVMNotesByNodeVMID(ctx context.Context, arg UpdateProxmoxVMNotesByNodeVMIDParams) error {
	_, err := q.db.Exec(ctx, updateProxmoxVMNotesByNodeVMID, arg.Notes, arg.Node, arg.Vmid)
	return err
}
