// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: personal_pods.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getPersonalPodByUser = `-- name: GetPersonalPodByUser :one
SELECT
    id,
    user_principal_id,
    folder_id,
    network_number,
    clone_target_key,
    created_at,
    updated_at
FROM personal_pods
WHERE user_principal_id = $1
`

func (q *Queries) GetPersonalPodByUser(ctx context.Context, userPrincipalID uuid.UUID) (PersonalPods, error) {
	row := q.db.QueryRow(ctx, getPersonalPodByUser, userPrincipalID)
	var i PersonalPods
	err := row.Scan(
		&i.ID,
		&i.UserPrincipalID,
		&i.FolderID,
		&i.NetworkNumber,
		&i.CloneTargetKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPersonalPodForInventoryItem = `-- name: GetPersonalPodForInventoryItem :one
WITH RECURSIVE ancestors AS (
    SELECT inventory_items.id, inventory_items.parent_id
    FROM inventory_items
    WHERE inventory_items.id = $1
    UNION ALL
    SELECT ii.id, ii.parent_id
    FROM inventory_items ii
    JOIN ancestors a ON ii.id = a.parent_id
)
SELECT pp.id, pp.user_principal_id, pp.folder_id, pp.network_number
FROM personal_pods pp
JOIN ancestors a ON pp.folder_id = a.id
LIMIT 1
`

type GetPersonalPodForInventoryItemRow struct {
	ID              uuid.UUID `json:"id"`
	UserPrincipalID uuid.UUID `json:"user_principal_id"`
	FolderID        uuid.UUID `json:"folder_id"`
	NetworkNumber   int32     `json:"network_number"`
}

func (q *Queries) GetPersonalPodForInventoryItem(ctx context.Context, id uuid.UUID) (GetPersonalPodForInventoryItemRow, error) {
	row := q.db.QueryRow(ctx, getPersonalPodForInventoryItem, id)
	var i GetPersonalPodForInventoryItemRow
	err := row.Scan(
		&i.ID,
		&i.UserPrincipalID,
		&i.FolderID,
		&i.NetworkNumber,
	)
	return i, err
}

const insertPersonalPod = `-- name: InsertPersonalPod :one
WITH candidate AS (
    SELECT n::INTEGER AS network_number
    FROM generate_series($1::INTEGER, $2::INTEGER) AS n
    WHERE NOT EXISTS (
        SELECT 1
        FROM pod_network_allocations pna
        WHERE pna.network_number = n
    )
    ORDER BY n
    LIMIT 1
),
allocation AS (
    INSERT INTO pod_network_allocations (
        network_number,
        kind,
        network_profile_key,
        clone_target_key,
        folder_id
    )
    SELECT
        candidate.network_number,
        'personal_pod',
        'lan-router-v1',
        $3,
        $4
    FROM candidate
    RETURNING id, network_number
),
inserted AS (
    INSERT INTO personal_pods (
        id,
        user_principal_id,
        folder_id,
        network_number,
        clone_target_key
    )
    SELECT
        $5,
        $6,
        $4,
        allocation.network_number,
        $3
    FROM allocation
    RETURNING
        id,
        user_principal_id,
        folder_id,
        network_number,
        clone_target_key,
        created_at,
        updated_at
)
SELECT
    inserted.id,
    inserted.user_principal_id,
    inserted.folder_id,
    inserted.network_number,
    inserted.clone_target_key,
    inserted.created_at,
    inserted.updated_at,
    allocation.id AS allocation_id
FROM inserted
JOIN allocation
  ON allocation.network_number = inserted.network_number
`

type InsertPersonalPodParams struct {
	MinNetworkNumber int32     `json:"min_network_number"`
	MaxNetworkNumber int32     `json:"max_network_number"`
	CloneTargetKey   string    `json:"clone_target_key"`
	FolderID         uuid.UUID `json:"folder_id"`
	ID               uuid.UUID `json:"id"`
	UserPrincipalID  uuid.UUID `json:"user_principal_id"`
}

type InsertPersonalPodRow struct {
	ID              uuid.UUID          `json:"id"`
	UserPrincipalID uuid.UUID          `json:"user_principal_id"`
	FolderID        uuid.UUID          `json:"folder_id"`
	NetworkNumber   int32              `json:"network_number"`
	CloneTargetKey  string             `json:"clone_target_key"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	AllocationID    uuid.UUID          `json:"allocation_id"`
}

func (q *Queries) InsertPersonalPod(ctx context.Context, arg InsertPersonalPodParams) (InsertPersonalPodRow, error) {
	row := q.db.QueryRow(ctx, insertPersonalPod,
		arg.MinNetworkNumber,
		arg.MaxNetworkNumber,
		arg.CloneTargetKey,
		arg.FolderID,
		arg.ID,
		arg.UserPrincipalID,
	)
	var i InsertPersonalPodRow
	err := row.Scan(
		&i.ID,
		&i.UserPrincipalID,
		&i.FolderID,
		&i.NetworkNumber,
		&i.CloneTargetKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AllocationID,
	)
	return i, err
}

const linkPersonalPodNetworkAllocation = `-- name: LinkPersonalPodNetworkAllocation :execrows
UPDATE pod_network_allocations
SET personal_pod_id = $1
WHERE id = $2
  AND folder_id = $3
  AND kind = 'personal_pod'
  AND personal_pod_id IS NULL
`

type LinkPersonalPodNetworkAllocationParams struct {
	PersonalPodID *uuid.UUID `json:"personal_pod_id"`
	AllocationID  uuid.UUID  `json:"allocation_id"`
	FolderID      uuid.UUID  `json:"folder_id"`
}

func (q *Queries) LinkPersonalPodNetworkAllocation(ctx context.Context, arg LinkPersonalPodNetworkAllocationParams) (int64, error) {
	result, err := q.db.Exec(ctx, linkPersonalPodNetworkAllocation, arg.PersonalPodID, arg.AllocationID, arg.FolderID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setPersonalPodRouterInventoryItem = `-- name: SetPersonalPodRouterInventoryItem :execrows
UPDATE pod_network_allocations
SET inventory_item_id = $1
WHERE personal_pod_id = $2
  AND kind = 'personal_pod'
`

type SetPersonalPodRouterInventoryItemParams struct {
	InventoryItemID *uuid.UUID `json:"inventory_item_id"`
	PersonalPodID   *uuid.UUID `json:"personal_pod_id"`
}

func (q *Queries) SetPersonalPodRouterInventoryItem(ctx context.Context, arg SetPersonalPodRouterInventoryItemParams) (int64, error) {
	result, err := q.db.Exec(ctx, setPersonalPodRouterInventoryItem, arg.InventoryItemID, arg.PersonalPodID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
