// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: personal_pods.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getPersonalPodByUser = `-- name: GetPersonalPodByUser :one
SELECT
    id,
    user_principal_id,
    folder_id,
    network_number,
    created_at,
    updated_at
FROM personal_pods
WHERE user_principal_id = $1
`

func (q *Queries) GetPersonalPodByUser(ctx context.Context, userPrincipalID uuid.UUID) (PersonalPods, error) {
	row := q.db.QueryRow(ctx, getPersonalPodByUser, userPrincipalID)
	var i PersonalPods
	err := row.Scan(
		&i.ID,
		&i.UserPrincipalID,
		&i.FolderID,
		&i.NetworkNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPersonalPodForInventoryItem = `-- name: GetPersonalPodForInventoryItem :one
WITH RECURSIVE ancestors AS (
    SELECT inventory_items.id, inventory_items.parent_id
    FROM inventory_items
    WHERE inventory_items.id = $1
    UNION ALL
    SELECT ii.id, ii.parent_id
    FROM inventory_items ii
    JOIN ancestors a ON ii.id = a.parent_id
)
SELECT pp.id, pp.user_principal_id, pp.folder_id, pp.network_number
FROM personal_pods pp
JOIN ancestors a ON pp.folder_id = a.id
LIMIT 1
`

type GetPersonalPodForInventoryItemRow struct {
	ID              uuid.UUID `json:"id"`
	UserPrincipalID uuid.UUID `json:"user_principal_id"`
	FolderID        uuid.UUID `json:"folder_id"`
	NetworkNumber   int32     `json:"network_number"`
}

func (q *Queries) GetPersonalPodForInventoryItem(ctx context.Context, id uuid.UUID) (GetPersonalPodForInventoryItemRow, error) {
	row := q.db.QueryRow(ctx, getPersonalPodForInventoryItem, id)
	var i GetPersonalPodForInventoryItemRow
	err := row.Scan(
		&i.ID,
		&i.UserPrincipalID,
		&i.FolderID,
		&i.NetworkNumber,
	)
	return i, err
}

const insertPersonalPod = `-- name: InsertPersonalPod :one
WITH allocation_lock AS (
    SELECT pg_advisory_xact_lock(740020001)
),
candidate AS (
    SELECT n::INTEGER AS network_number
    FROM allocation_lock,
         generate_series($1::INTEGER, $2::INTEGER) AS n
    WHERE NOT EXISTS (
        SELECT 1
        FROM pod_network_allocations pna
        WHERE pna.network_number = n
    )
    ORDER BY n
    LIMIT 1
),
allocation AS (
    INSERT INTO pod_network_allocations (
        network_number,
        kind,
        folder_id
    )
    SELECT
        candidate.network_number,
        'personal_pod',
        $3
    FROM candidate
    RETURNING id, network_number
),
inserted AS (
    INSERT INTO personal_pods (
        id,
        user_principal_id,
        folder_id,
        network_number
    )
    SELECT
        $4,
        $5,
        $3,
        allocation.network_number
    FROM allocation
    RETURNING
        id,
        user_principal_id,
        folder_id,
        network_number,
        created_at,
        updated_at
),
_link AS (
    UPDATE pod_network_allocations AS pna
    SET personal_pod_id = inserted.id
    FROM inserted, allocation
    WHERE pna.id = allocation.id
)
SELECT
    id,
    user_principal_id,
    folder_id,
    network_number,
    created_at,
    updated_at
FROM inserted
`

type InsertPersonalPodParams struct {
	MinNetworkNumber int32     `json:"min_network_number"`
	MaxNetworkNumber int32     `json:"max_network_number"`
	FolderID         uuid.UUID `json:"folder_id"`
	ID               uuid.UUID `json:"id"`
	UserPrincipalID  uuid.UUID `json:"user_principal_id"`
}

type InsertPersonalPodRow struct {
	ID              uuid.UUID          `json:"id"`
	UserPrincipalID uuid.UUID          `json:"user_principal_id"`
	FolderID        uuid.UUID          `json:"folder_id"`
	NetworkNumber   int32              `json:"network_number"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) InsertPersonalPod(ctx context.Context, arg InsertPersonalPodParams) (InsertPersonalPodRow, error) {
	row := q.db.QueryRow(ctx, insertPersonalPod,
		arg.MinNetworkNumber,
		arg.MaxNetworkNumber,
		arg.FolderID,
		arg.ID,
		arg.UserPrincipalID,
	)
	var i InsertPersonalPodRow
	err := row.Scan(
		&i.ID,
		&i.UserPrincipalID,
		&i.FolderID,
		&i.NetworkNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
