// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pod_network_allocations.sql

package database

import (
	"context"
)

const acquirePodNetworkAllocationLock = `-- name: AcquirePodNetworkAllocationLock :exec
SELECT pg_advisory_xact_lock(740020001)
`

func (q *Queries) AcquirePodNetworkAllocationLock(ctx context.Context) error {
	_, err := q.db.Exec(ctx, acquirePodNetworkAllocationLock)
	return err
}
