// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pod_clones.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getAccessibleClonedPodByID = `-- name: GetAccessibleClonedPodByID :one
SELECT
    cp.id,
    cp.pod_id,
    cp.user_principal_id,
    cp.folder_id,
    cp.network_number,
    cp.network_profile_key,
    cp.created_at,
    cp.updated_at
FROM cloned_pods cp
WHERE cp.id = $1
  AND cp.user_principal_id IN (
      SELECT ep.principal_id::UUID
      FROM get_user_effective_principals($2) AS ep(principal_id)
  )
`

type GetAccessibleClonedPodByIDParams struct {
	ID          uuid.UUID `json:"id"`
	PrincipalID uuid.UUID `json:"principal_id"`
}

func (q *Queries) GetAccessibleClonedPodByID(ctx context.Context, arg GetAccessibleClonedPodByIDParams) (ClonedPods, error) {
	row := q.db.QueryRow(ctx, getAccessibleClonedPodByID, arg.ID, arg.PrincipalID)
	var i ClonedPods
	err := row.Scan(
		&i.ID,
		&i.PodID,
		&i.UserPrincipalID,
		&i.FolderID,
		&i.NetworkNumber,
		&i.NetworkProfileKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccessibleClonedPodByPodID = `-- name: GetAccessibleClonedPodByPodID :one
SELECT
    cp.id,
    cp.pod_id,
    cp.user_principal_id,
    cp.folder_id,
    cp.network_number,
    cp.network_profile_key,
    cp.created_at,
    cp.updated_at
FROM cloned_pods cp
WHERE cp.pod_id = $1
  AND cp.user_principal_id IN (
      SELECT ep.principal_id::UUID
      FROM get_user_effective_principals($2) AS ep(principal_id)
  )
ORDER BY
    CASE WHEN cp.user_principal_id = $2 THEN 0 ELSE 1 END,
    cp.created_at DESC
LIMIT 1
`

type GetAccessibleClonedPodByPodIDParams struct {
	PodID       uuid.UUID `json:"pod_id"`
	PrincipalID uuid.UUID `json:"principal_id"`
}

func (q *Queries) GetAccessibleClonedPodByPodID(ctx context.Context, arg GetAccessibleClonedPodByPodIDParams) (ClonedPods, error) {
	row := q.db.QueryRow(ctx, getAccessibleClonedPodByPodID, arg.PodID, arg.PrincipalID)
	var i ClonedPods
	err := row.Scan(
		&i.ID,
		&i.PodID,
		&i.UserPrincipalID,
		&i.FolderID,
		&i.NetworkNumber,
		&i.NetworkProfileKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getClonedPodByID = `-- name: GetClonedPodByID :one
SELECT
    id,
    pod_id,
    user_principal_id,
    folder_id,
    network_number,
    network_profile_key,
    created_at,
    updated_at
FROM cloned_pods
WHERE id = $1
`

func (q *Queries) GetClonedPodByID(ctx context.Context, id uuid.UUID) (ClonedPods, error) {
	row := q.db.QueryRow(ctx, getClonedPodByID, id)
	var i ClonedPods
	err := row.Scan(
		&i.ID,
		&i.PodID,
		&i.UserPrincipalID,
		&i.FolderID,
		&i.NetworkNumber,
		&i.NetworkProfileKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getClonedPodForPrincipalByPodID = `-- name: GetClonedPodForPrincipalByPodID :one
SELECT
    id,
    pod_id,
    user_principal_id,
    folder_id,
    network_number,
    network_profile_key,
    created_at,
    updated_at
FROM cloned_pods
WHERE pod_id = $1
  AND user_principal_id = $2
`

type GetClonedPodForPrincipalByPodIDParams struct {
	PodID           uuid.UUID `json:"pod_id"`
	UserPrincipalID uuid.UUID `json:"user_principal_id"`
}

func (q *Queries) GetClonedPodForPrincipalByPodID(ctx context.Context, arg GetClonedPodForPrincipalByPodIDParams) (ClonedPods, error) {
	row := q.db.QueryRow(ctx, getClonedPodForPrincipalByPodID, arg.PodID, arg.UserPrincipalID)
	var i ClonedPods
	err := row.Scan(
		&i.ID,
		&i.PodID,
		&i.UserPrincipalID,
		&i.FolderID,
		&i.NetworkNumber,
		&i.NetworkProfileKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertClonedPod = `-- name: InsertClonedPod :one
WITH allocation_lock AS (
    SELECT pg_advisory_xact_lock(740020001)
),
candidate AS (
    SELECT n::INTEGER AS network_number
    FROM allocation_lock,
         generate_series($1::INTEGER, $2::INTEGER) AS n
    WHERE NOT EXISTS (
        SELECT 1
        FROM pod_network_allocations pna
        WHERE pna.network_number = n
    )
    ORDER BY n
    LIMIT 1
),
allocation AS (
    INSERT INTO pod_network_allocations (
        network_number,
        kind,
        network_profile_key,
        folder_id
    )
    SELECT
        candidate.network_number,
        'published_clone',
        $3,
        $4
    FROM candidate
    RETURNING id, network_number
),
inserted AS (
    INSERT INTO cloned_pods (
        id,
        pod_id,
        user_principal_id,
        folder_id,
        network_number,
        network_profile_key
    )
    SELECT
        $5,
        $6,
        $7,
        $4,
        allocation.network_number,
        $3
    FROM allocation
    RETURNING
        id,
        pod_id,
        user_principal_id,
        folder_id,
        network_number,
        network_profile_key,
        created_at,
        updated_at
),
_link AS (
    UPDATE pod_network_allocations AS pna
    SET cloned_pod_id = inserted.id
    FROM inserted, allocation
    WHERE pna.id = allocation.id
)
SELECT
    id,
    pod_id,
    user_principal_id,
    folder_id,
    network_number,
    network_profile_key,
    created_at,
    updated_at
FROM inserted
`

type InsertClonedPodParams struct {
	MinNetworkNumber  int32     `json:"min_network_number"`
	MaxNetworkNumber  int32     `json:"max_network_number"`
	NetworkProfileKey *string   `json:"network_profile_key"`
	FolderID          uuid.UUID `json:"folder_id"`
	ID                uuid.UUID `json:"id"`
	PodID             uuid.UUID `json:"pod_id"`
	UserPrincipalID   uuid.UUID `json:"user_principal_id"`
}

type InsertClonedPodRow struct {
	ID                uuid.UUID          `json:"id"`
	PodID             uuid.UUID          `json:"pod_id"`
	UserPrincipalID   uuid.UUID          `json:"user_principal_id"`
	FolderID          uuid.UUID          `json:"folder_id"`
	NetworkNumber     int32              `json:"network_number"`
	NetworkProfileKey string             `json:"network_profile_key"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) InsertClonedPod(ctx context.Context, arg InsertClonedPodParams) (InsertClonedPodRow, error) {
	row := q.db.QueryRow(ctx, insertClonedPod,
		arg.MinNetworkNumber,
		arg.MaxNetworkNumber,
		arg.NetworkProfileKey,
		arg.FolderID,
		arg.ID,
		arg.PodID,
		arg.UserPrincipalID,
	)
	var i InsertClonedPodRow
	err := row.Scan(
		&i.ID,
		&i.PodID,
		&i.UserPrincipalID,
		&i.FolderID,
		&i.NetworkNumber,
		&i.NetworkProfileKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAccessibleClonedPodSummariesByPodIDs = `-- name: ListAccessibleClonedPodSummariesByPodIDs :many
SELECT DISTINCT ON (cp.pod_id)
    cp.id,
    cp.pod_id,
    cp.user_principal_id,
    cp.created_at,
    COUNT(DISTINCT task.id)::int AS task_total,
    COUNT(DISTINCT state.task_id) FILTER (WHERE state.completed)::int AS task_completed
FROM cloned_pods cp
LEFT JOIN published_pod_tasks task
  ON task.pod_id = cp.pod_id
LEFT JOIN cloned_pod_task_states state
  ON state.cloned_pod_id = cp.id
 AND state.task_id = task.id
WHERE cp.pod_id = ANY($1::UUID[])
  AND cp.user_principal_id IN (
      SELECT ep.principal_id::UUID
      FROM get_user_effective_principals($2) AS ep(principal_id)
  )
GROUP BY
    cp.id,
    cp.pod_id,
    cp.user_principal_id,
    cp.created_at
ORDER BY
    cp.pod_id,
    CASE WHEN cp.user_principal_id = $2 THEN 0 ELSE 1 END,
    cp.created_at DESC
`

type ListAccessibleClonedPodSummariesByPodIDsParams struct {
	Column1     []uuid.UUID `json:"column_1"`
	PrincipalID uuid.UUID   `json:"principal_id"`
}

type ListAccessibleClonedPodSummariesByPodIDsRow struct {
	ID              uuid.UUID          `json:"id"`
	PodID           uuid.UUID          `json:"pod_id"`
	UserPrincipalID uuid.UUID          `json:"user_principal_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	TaskTotal       int32              `json:"task_total"`
	TaskCompleted   int32              `json:"task_completed"`
}

func (q *Queries) ListAccessibleClonedPodSummariesByPodIDs(ctx context.Context, arg ListAccessibleClonedPodSummariesByPodIDsParams) ([]ListAccessibleClonedPodSummariesByPodIDsRow, error) {
	rows, err := q.db.Query(ctx, listAccessibleClonedPodSummariesByPodIDs, arg.Column1, arg.PrincipalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAccessibleClonedPodSummariesByPodIDsRow
	for rows.Next() {
		var i ListAccessibleClonedPodSummariesByPodIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.PodID,
			&i.UserPrincipalID,
			&i.CreatedAt,
			&i.TaskTotal,
			&i.TaskCompleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClonedPodRuntimeVMsByCloneIDs = `-- name: ListClonedPodRuntimeVMsByCloneIDs :many
SELECT
    cpv.cloned_pod_id,
    cpv.inventory_item_id,
    ii.name,
    pv.node,
    pv.vmid,
    cpv.sort_order
FROM cloned_pod_vms cpv
JOIN inventory_items ii
  ON ii.id = cpv.inventory_item_id
LEFT JOIN proxmox_vms pv
  ON pv.inventory_item_id = cpv.inventory_item_id
WHERE cpv.cloned_pod_id = ANY($1::UUID[])
ORDER BY cpv.cloned_pod_id, cpv.sort_order ASC
`

type ListClonedPodRuntimeVMsByCloneIDsRow struct {
	ClonedPodID     uuid.UUID `json:"cloned_pod_id"`
	InventoryItemID uuid.UUID `json:"inventory_item_id"`
	Name            string    `json:"name"`
	Node            *string   `json:"node"`
	Vmid            *int32    `json:"vmid"`
	SortOrder       int32     `json:"sort_order"`
}

func (q *Queries) ListClonedPodRuntimeVMsByCloneIDs(ctx context.Context, cloneIds []uuid.UUID) ([]ListClonedPodRuntimeVMsByCloneIDsRow, error) {
	rows, err := q.db.Query(ctx, listClonedPodRuntimeVMsByCloneIDs, cloneIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListClonedPodRuntimeVMsByCloneIDsRow
	for rows.Next() {
		var i ListClonedPodRuntimeVMsByCloneIDsRow
		if err := rows.Scan(
			&i.ClonedPodID,
			&i.InventoryItemID,
			&i.Name,
			&i.Node,
			&i.Vmid,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClonedPodSummariesByPodID = `-- name: ListClonedPodSummariesByPodID :many
SELECT
    cp.id,
    cp.pod_id,
    cp.user_principal_id,
    p.principal_type,
    (
    CASE
        WHEN p.full_name IS NULL OR lower(trim(p.full_name)) = lower(COALESCE(NULLIF(trim(p.name), ''), p.external_id))
            THEN COALESCE(NULLIF(trim(p.name), ''), p.external_id)
        ELSE COALESCE(NULLIF(trim(p.name), ''), p.external_id) || ' (' || trim(p.full_name) || ')'
    END
    )::TEXT AS user_label,
    COALESCE(p.description, '') AS user_description,
    cp.folder_id,
    cp.network_number,
    cp.network_profile_key,
    cp.created_at,
    cp.updated_at,
    COUNT(DISTINCT cpv.inventory_item_id)::int AS vm_count,
    COUNT(DISTINCT task.id)::int AS task_total,
    COUNT(DISTINCT state.task_id) FILTER (WHERE state.completed)::int AS task_completed
FROM cloned_pods cp
JOIN principals p
  ON p.id = cp.user_principal_id
LEFT JOIN cloned_pod_vms cpv
  ON cpv.cloned_pod_id = cp.id
LEFT JOIN published_pod_tasks task
  ON task.pod_id = cp.pod_id
LEFT JOIN cloned_pod_task_states state
  ON state.cloned_pod_id = cp.id
 AND state.task_id = task.id
WHERE cp.pod_id = $1
GROUP BY
    cp.id,
    cp.pod_id,
    cp.user_principal_id,
    p.principal_type,
    p.name,
    p.full_name,
    p.external_id,
    p.description,
    cp.folder_id,
    cp.network_number,
    cp.created_at,
    cp.updated_at
ORDER BY cp.created_at DESC
`

type ListClonedPodSummariesByPodIDRow struct {
	ID                uuid.UUID          `json:"id"`
	PodID             uuid.UUID          `json:"pod_id"`
	UserPrincipalID   uuid.UUID          `json:"user_principal_id"`
	PrincipalType     PrincipalType      `json:"principal_type"`
	UserLabel         string             `json:"user_label"`
	UserDescription   string             `json:"user_description"`
	FolderID          uuid.UUID          `json:"folder_id"`
	NetworkNumber     int32              `json:"network_number"`
	NetworkProfileKey string             `json:"network_profile_key"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	VmCount           int32              `json:"vm_count"`
	TaskTotal         int32              `json:"task_total"`
	TaskCompleted     int32              `json:"task_completed"`
}

func (q *Queries) ListClonedPodSummariesByPodID(ctx context.Context, podID uuid.UUID) ([]ListClonedPodSummariesByPodIDRow, error) {
	rows, err := q.db.Query(ctx, listClonedPodSummariesByPodID, podID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListClonedPodSummariesByPodIDRow
	for rows.Next() {
		var i ListClonedPodSummariesByPodIDRow
		if err := rows.Scan(
			&i.ID,
			&i.PodID,
			&i.UserPrincipalID,
			&i.PrincipalType,
			&i.UserLabel,
			&i.UserDescription,
			&i.FolderID,
			&i.NetworkNumber,
			&i.NetworkProfileKey,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.VmCount,
			&i.TaskTotal,
			&i.TaskCompleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClonedPodsByPodID = `-- name: ListClonedPodsByPodID :many
SELECT
    id,
    pod_id,
    user_principal_id,
    folder_id,
    network_number,
    network_profile_key,
    created_at,
    updated_at
FROM cloned_pods
WHERE pod_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListClonedPodsByPodID(ctx context.Context, podID uuid.UUID) ([]ClonedPods, error) {
	rows, err := q.db.Query(ctx, listClonedPodsByPodID, podID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClonedPods
	for rows.Next() {
		var i ClonedPods
		if err := rows.Scan(
			&i.ID,
			&i.PodID,
			&i.UserPrincipalID,
			&i.FolderID,
			&i.NetworkNumber,
			&i.NetworkProfileKey,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedPodVMsForClone = `-- name: ListPublishedPodVMsForClone :many
SELECT
    id,
    pod_id,
    source_inventory_item_id,
    name,
    cpu_count,
    memory_mb,
    disk_gb,
    allow_mask,
    deny_mask,
    is_router,
    segment_key,
    sort_order
FROM published_pod_vms
WHERE pod_id = $1
ORDER BY sort_order ASC
`

type ListPublishedPodVMsForCloneRow struct {
	ID                    uuid.UUID `json:"id"`
	PodID                 uuid.UUID `json:"pod_id"`
	SourceInventoryItemID uuid.UUID `json:"source_inventory_item_id"`
	Name                  string    `json:"name"`
	CpuCount              int32     `json:"cpu_count"`
	MemoryMb              int32     `json:"memory_mb"`
	DiskGb                float64   `json:"disk_gb"`
	AllowMask             int64     `json:"allow_mask"`
	DenyMask              int64     `json:"deny_mask"`
	IsRouter              bool      `json:"is_router"`
	SegmentKey            *string   `json:"segment_key"`
	SortOrder             int32     `json:"sort_order"`
}

func (q *Queries) ListPublishedPodVMsForClone(ctx context.Context, podID uuid.UUID) ([]ListPublishedPodVMsForCloneRow, error) {
	rows, err := q.db.Query(ctx, listPublishedPodVMsForClone, podID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublishedPodVMsForCloneRow
	for rows.Next() {
		var i ListPublishedPodVMsForCloneRow
		if err := rows.Scan(
			&i.ID,
			&i.PodID,
			&i.SourceInventoryItemID,
			&i.Name,
			&i.CpuCount,
			&i.MemoryMb,
			&i.DiskGb,
			&i.AllowMask,
			&i.DenyMask,
			&i.IsRouter,
			&i.SegmentKey,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
