// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pod_clone_claims.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimPodClone = `-- name: ClaimPodClone :one

WITH pod_lock AS MATERIALIZED (
    SELECT pg_advisory_xact_lock(hashtextextended($1::UUID::TEXT, 740020004))
),
conflicting_claim AS (
    SELECT 1
    FROM pod_clone_claims existing
    CROSS JOIN pod_lock
    WHERE existing.pod_id = $1
      AND (
          existing.user_principal_id IN (
              SELECT ep.principal_id::UUID
              FROM get_user_effective_principals($2) AS ep(principal_id)
          )
          OR $2 IN (
              SELECT ep.principal_id::UUID
              FROM get_user_effective_principals(existing.user_principal_id) AS ep(principal_id)
          )
      )
)
INSERT INTO pod_clone_claims (pod_id, user_principal_id, action, actor_principal_id)
SELECT $1, $2, $3, $4
FROM pod_lock
WHERE NOT EXISTS (SELECT 1 FROM conflicting_claim)
RETURNING pod_id, user_principal_id, action, actor_principal_id, claimed_at
`

type ClaimPodCloneParams struct {
	PodID            uuid.UUID `json:"pod_id"`
	UserPrincipalID  uuid.UUID `json:"user_principal_id"`
	Action           string    `json:"action"`
	ActorPrincipalID uuid.UUID `json:"actor_principal_id"`
}

// ----------------------------------------------------------------------------
// Pod clone claims
// Durable serialization boundary for pod clone/reclone/delete operations.
// ----------------------------------------------------------------------------
func (q *Queries) ClaimPodClone(ctx context.Context, arg ClaimPodCloneParams) (PodCloneClaims, error) {
	row := q.db.QueryRow(ctx, claimPodClone,
		arg.PodID,
		arg.UserPrincipalID,
		arg.Action,
		arg.ActorPrincipalID,
	)
	var i PodCloneClaims
	err := row.Scan(
		&i.PodID,
		&i.UserPrincipalID,
		&i.Action,
		&i.ActorPrincipalID,
		&i.ClaimedAt,
	)
	return i, err
}

const deleteAllPodCloneClaims = `-- name: DeleteAllPodCloneClaims :execrows
DELETE FROM pod_clone_claims
`

func (q *Queries) DeleteAllPodCloneClaims(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAllPodCloneClaims)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getConflictingClonedPodForPrincipalByPodID = `-- name: GetConflictingClonedPodForPrincipalByPodID :one
SELECT
    cp.id,
    cp.pod_id,
    cp.user_principal_id,
    cp.folder_id,
    cp.network_number,
    cp.created_at,
    cp.updated_at
FROM cloned_pods cp
WHERE cp.pod_id = $1
  AND (
      cp.user_principal_id IN (
          SELECT ep.principal_id::UUID
          FROM get_user_effective_principals($2) AS ep(principal_id)
      )
      OR $2 IN (
          SELECT ep.principal_id::UUID
          FROM get_user_effective_principals(cp.user_principal_id) AS ep(principal_id)
      )
  )
ORDER BY
    CASE WHEN cp.user_principal_id = $2 THEN 0 ELSE 1 END,
    cp.created_at DESC
LIMIT 1
`

type GetConflictingClonedPodForPrincipalByPodIDParams struct {
	PodID           uuid.UUID `json:"pod_id"`
	UserPrincipalID uuid.UUID `json:"user_principal_id"`
}

type GetConflictingClonedPodForPrincipalByPodIDRow struct {
	ID              uuid.UUID          `json:"id"`
	PodID           uuid.UUID          `json:"pod_id"`
	UserPrincipalID uuid.UUID          `json:"user_principal_id"`
	FolderID        uuid.UUID          `json:"folder_id"`
	NetworkNumber   int32              `json:"network_number"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetConflictingClonedPodForPrincipalByPodID(ctx context.Context, arg GetConflictingClonedPodForPrincipalByPodIDParams) (GetConflictingClonedPodForPrincipalByPodIDRow, error) {
	row := q.db.QueryRow(ctx, getConflictingClonedPodForPrincipalByPodID, arg.PodID, arg.UserPrincipalID)
	var i GetConflictingClonedPodForPrincipalByPodIDRow
	err := row.Scan(
		&i.ID,
		&i.PodID,
		&i.UserPrincipalID,
		&i.FolderID,
		&i.NetworkNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const releasePodClone = `-- name: ReleasePodClone :exec
DELETE FROM pod_clone_claims
WHERE pod_id = $1
  AND user_principal_id = $2
`

type ReleasePodCloneParams struct {
	PodID           uuid.UUID `json:"pod_id"`
	UserPrincipalID uuid.UUID `json:"user_principal_id"`
}

func (q *Queries) ReleasePodClone(ctx context.Context, arg ReleasePodCloneParams) error {
	_, err := q.db.Exec(ctx, releasePodClone, arg.PodID, arg.UserPrincipalID)
	return err
}
