// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pod_clone_targets.sql

package database

import (
	"context"
)

const countPodCloneTargetReferences = `-- name: CountPodCloneTargetReferences :one
SELECT
    (SELECT count(*) FROM published_pods pp WHERE pp.clone_target_key = $1) AS published_pod_count,
    (SELECT count(*) FROM cloned_pods cp WHERE cp.clone_target_key = $1) AS cloned_pod_count,
    (SELECT count(*) FROM pod_network_allocations pna WHERE pna.clone_target_key = $1) AS allocation_count
`

type CountPodCloneTargetReferencesRow struct {
	PublishedPodCount int64 `json:"published_pod_count"`
	ClonedPodCount    int64 `json:"cloned_pod_count"`
	AllocationCount   int64 `json:"allocation_count"`
}

func (q *Queries) CountPodCloneTargetReferences(ctx context.Context, targetKey string) (CountPodCloneTargetReferencesRow, error) {
	row := q.db.QueryRow(ctx, countPodCloneTargetReferences, targetKey)
	var i CountPodCloneTargetReferencesRow
	err := row.Scan(&i.PublishedPodCount, &i.ClonedPodCount, &i.AllocationCount)
	return i, err
}

const countPodCloneTargets = `-- name: CountPodCloneTargets :one
SELECT count(*) FROM pod_clone_targets
`

func (q *Queries) CountPodCloneTargets(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPodCloneTargets)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPodCloneTarget = `-- name: CreatePodCloneTarget :one
INSERT INTO pod_clone_targets (
    key,
    label,
    lan_vnet,
    dmz_vnet,
    wan_bridge,
    wan_subnet,
    cloud_init_storage,
    cloud_init_user_file_pattern,
    cloud_init_network_file,
    lan_dmz_user_file_pattern,
    lan_dmz_network_file
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
RETURNING
    key,
    label,
    lan_vnet,
    dmz_vnet,
    wan_bridge,
    wan_subnet,
    cloud_init_storage,
    cloud_init_user_file_pattern,
    cloud_init_network_file,
    lan_dmz_user_file_pattern,
    lan_dmz_network_file,
    is_default,
    created_at,
    updated_at
`

type CreatePodCloneTargetParams struct {
	Key                      string `json:"key"`
	Label                    string `json:"label"`
	LanVnet                  string `json:"lan_vnet"`
	DmzVnet                  string `json:"dmz_vnet"`
	WanBridge                string `json:"wan_bridge"`
	WanSubnet                string `json:"wan_subnet"`
	CloudInitStorage         string `json:"cloud_init_storage"`
	CloudInitUserFilePattern string `json:"cloud_init_user_file_pattern"`
	CloudInitNetworkFile     string `json:"cloud_init_network_file"`
	LanDmzUserFilePattern    string `json:"lan_dmz_user_file_pattern"`
	LanDmzNetworkFile        string `json:"lan_dmz_network_file"`
}

func (q *Queries) CreatePodCloneTarget(ctx context.Context, arg CreatePodCloneTargetParams) (PodCloneTargets, error) {
	row := q.db.QueryRow(ctx, createPodCloneTarget,
		arg.Key,
		arg.Label,
		arg.LanVnet,
		arg.DmzVnet,
		arg.WanBridge,
		arg.WanSubnet,
		arg.CloudInitStorage,
		arg.CloudInitUserFilePattern,
		arg.CloudInitNetworkFile,
		arg.LanDmzUserFilePattern,
		arg.LanDmzNetworkFile,
	)
	var i PodCloneTargets
	err := row.Scan(
		&i.Key,
		&i.Label,
		&i.LanVnet,
		&i.DmzVnet,
		&i.WanBridge,
		&i.WanSubnet,
		&i.CloudInitStorage,
		&i.CloudInitUserFilePattern,
		&i.CloudInitNetworkFile,
		&i.LanDmzUserFilePattern,
		&i.LanDmzNetworkFile,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePodCloneTarget = `-- name: DeletePodCloneTarget :execrows
DELETE FROM pod_clone_targets
WHERE key = $1
  AND NOT is_default
`

func (q *Queries) DeletePodCloneTarget(ctx context.Context, key string) (int64, error) {
	result, err := q.db.Exec(ctx, deletePodCloneTarget, key)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getDefaultPodCloneTarget = `-- name: GetDefaultPodCloneTarget :one
SELECT
    key,
    label,
    lan_vnet,
    dmz_vnet,
    wan_bridge,
    wan_subnet,
    cloud_init_storage,
    cloud_init_user_file_pattern,
    cloud_init_network_file,
    lan_dmz_user_file_pattern,
    lan_dmz_network_file,
    is_default,
    created_at,
    updated_at
FROM pod_clone_targets
WHERE is_default
`

func (q *Queries) GetDefaultPodCloneTarget(ctx context.Context) (PodCloneTargets, error) {
	row := q.db.QueryRow(ctx, getDefaultPodCloneTarget)
	var i PodCloneTargets
	err := row.Scan(
		&i.Key,
		&i.Label,
		&i.LanVnet,
		&i.DmzVnet,
		&i.WanBridge,
		&i.WanSubnet,
		&i.CloudInitStorage,
		&i.CloudInitUserFilePattern,
		&i.CloudInitNetworkFile,
		&i.LanDmzUserFilePattern,
		&i.LanDmzNetworkFile,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPodCloneTarget = `-- name: GetPodCloneTarget :one
SELECT
    key,
    label,
    lan_vnet,
    dmz_vnet,
    wan_bridge,
    wan_subnet,
    cloud_init_storage,
    cloud_init_user_file_pattern,
    cloud_init_network_file,
    lan_dmz_user_file_pattern,
    lan_dmz_network_file,
    is_default,
    created_at,
    updated_at
FROM pod_clone_targets
WHERE key = $1
`

func (q *Queries) GetPodCloneTarget(ctx context.Context, key string) (PodCloneTargets, error) {
	row := q.db.QueryRow(ctx, getPodCloneTarget, key)
	var i PodCloneTargets
	err := row.Scan(
		&i.Key,
		&i.Label,
		&i.LanVnet,
		&i.DmzVnet,
		&i.WanBridge,
		&i.WanSubnet,
		&i.CloudInitStorage,
		&i.CloudInitUserFilePattern,
		&i.CloudInitNetworkFile,
		&i.LanDmzUserFilePattern,
		&i.LanDmzNetworkFile,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertDefaultPodCloneTarget = `-- name: InsertDefaultPodCloneTarget :exec
INSERT INTO pod_clone_targets (
    key,
    label,
    lan_vnet,
    dmz_vnet,
    wan_bridge,
    wan_subnet,
    cloud_init_storage,
    cloud_init_user_file_pattern,
    cloud_init_network_file,
    lan_dmz_user_file_pattern,
    lan_dmz_network_file,
    is_default
)
SELECT
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    true
WHERE NOT EXISTS (SELECT 1 FROM pod_clone_targets)
`

type InsertDefaultPodCloneTargetParams struct {
	Key                      string `json:"key"`
	Label                    string `json:"label"`
	LanVnet                  string `json:"lan_vnet"`
	DmzVnet                  string `json:"dmz_vnet"`
	WanBridge                string `json:"wan_bridge"`
	WanSubnet                string `json:"wan_subnet"`
	CloudInitStorage         string `json:"cloud_init_storage"`
	CloudInitUserFilePattern string `json:"cloud_init_user_file_pattern"`
	CloudInitNetworkFile     string `json:"cloud_init_network_file"`
	LanDmzUserFilePattern    string `json:"lan_dmz_user_file_pattern"`
	LanDmzNetworkFile        string `json:"lan_dmz_network_file"`
}

func (q *Queries) InsertDefaultPodCloneTarget(ctx context.Context, arg InsertDefaultPodCloneTargetParams) error {
	_, err := q.db.Exec(ctx, insertDefaultPodCloneTarget,
		arg.Key,
		arg.Label,
		arg.LanVnet,
		arg.DmzVnet,
		arg.WanBridge,
		arg.WanSubnet,
		arg.CloudInitStorage,
		arg.CloudInitUserFilePattern,
		arg.CloudInitNetworkFile,
		arg.LanDmzUserFilePattern,
		arg.LanDmzNetworkFile,
	)
	return err
}

const listPodCloneTargets = `-- name: ListPodCloneTargets :many
SELECT
    key,
    label,
    lan_vnet,
    dmz_vnet,
    wan_bridge,
    wan_subnet,
    cloud_init_storage,
    cloud_init_user_file_pattern,
    cloud_init_network_file,
    lan_dmz_user_file_pattern,
    lan_dmz_network_file,
    is_default,
    created_at,
    updated_at
FROM pod_clone_targets
ORDER BY is_default DESC, lower(label) ASC, key ASC
`

func (q *Queries) ListPodCloneTargets(ctx context.Context) ([]PodCloneTargets, error) {
	rows, err := q.db.Query(ctx, listPodCloneTargets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PodCloneTargets
	for rows.Next() {
		var i PodCloneTargets
		if err := rows.Scan(
			&i.Key,
			&i.Label,
			&i.LanVnet,
			&i.DmzVnet,
			&i.WanBridge,
			&i.WanSubnet,
			&i.CloudInitStorage,
			&i.CloudInitUserFilePattern,
			&i.CloudInitNetworkFile,
			&i.LanDmzUserFilePattern,
			&i.LanDmzNetworkFile,
			&i.IsDefault,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePodCloneTarget = `-- name: UpdatePodCloneTarget :one
UPDATE pod_clone_targets
   SET label                        = $1,
       lan_vnet                     = $2,
       dmz_vnet                     = $3,
       wan_bridge                   = $4,
       wan_subnet                   = $5,
       cloud_init_storage           = $6,
       cloud_init_user_file_pattern = $7,
       cloud_init_network_file      = $8,
       lan_dmz_user_file_pattern    = $9,
       lan_dmz_network_file         = $10
 WHERE key = $11
RETURNING
    key,
    label,
    lan_vnet,
    dmz_vnet,
    wan_bridge,
    wan_subnet,
    cloud_init_storage,
    cloud_init_user_file_pattern,
    cloud_init_network_file,
    lan_dmz_user_file_pattern,
    lan_dmz_network_file,
    is_default,
    created_at,
    updated_at
`

type UpdatePodCloneTargetParams struct {
	Label                    string `json:"label"`
	LanVnet                  string `json:"lan_vnet"`
	DmzVnet                  string `json:"dmz_vnet"`
	WanBridge                string `json:"wan_bridge"`
	WanSubnet                string `json:"wan_subnet"`
	CloudInitStorage         string `json:"cloud_init_storage"`
	CloudInitUserFilePattern string `json:"cloud_init_user_file_pattern"`
	CloudInitNetworkFile     string `json:"cloud_init_network_file"`
	LanDmzUserFilePattern    string `json:"lan_dmz_user_file_pattern"`
	LanDmzNetworkFile        string `json:"lan_dmz_network_file"`
	Key                      string `json:"key"`
}

func (q *Queries) UpdatePodCloneTarget(ctx context.Context, arg UpdatePodCloneTargetParams) (PodCloneTargets, error) {
	row := q.db.QueryRow(ctx, updatePodCloneTarget,
		arg.Label,
		arg.LanVnet,
		arg.DmzVnet,
		arg.WanBridge,
		arg.WanSubnet,
		arg.CloudInitStorage,
		arg.CloudInitUserFilePattern,
		arg.CloudInitNetworkFile,
		arg.LanDmzUserFilePattern,
		arg.LanDmzNetworkFile,
		arg.Key,
	)
	var i PodCloneTargets
	err := row.Scan(
		&i.Key,
		&i.Label,
		&i.LanVnet,
		&i.DmzVnet,
		&i.WanBridge,
		&i.WanSubnet,
		&i.CloudInitStorage,
		&i.CloudInitUserFilePattern,
		&i.CloudInitNetworkFile,
		&i.LanDmzUserFilePattern,
		&i.LanDmzNetworkFile,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
