// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pod_networks.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const deletePodDevVMNetworkAssignments = `-- name: DeletePodDevVMNetworkAssignments :exec
DELETE FROM pod_dev_vm_network_assignments
WHERE pod_folder_id = $1
`

func (q *Queries) DeletePodDevVMNetworkAssignments(ctx context.Context, podFolderID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePodDevVMNetworkAssignments, podFolderID)
	return err
}

const getPodDevNetworkAllocation = `-- name: GetPodDevNetworkAllocation :one
SELECT
    pod_folder_id,
    network_number,
    network_profile_key,
    created_at,
    updated_at
FROM pod_dev_network_allocations
WHERE pod_folder_id = $1
`

func (q *Queries) GetPodDevNetworkAllocation(ctx context.Context, podFolderID uuid.UUID) (PodDevNetworkAllocations, error) {
	row := q.db.QueryRow(ctx, getPodDevNetworkAllocation, podFolderID)
	var i PodDevNetworkAllocations
	err := row.Scan(
		&i.PodFolderID,
		&i.NetworkNumber,
		&i.NetworkProfileKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertPodDevNetworkAllocation = `-- name: InsertPodDevNetworkAllocation :one
WITH allocation_lock AS (
    SELECT pg_advisory_xact_lock(740020002)
),
candidate AS (
    SELECT n::INTEGER AS network_number
    FROM allocation_lock,
         generate_series($3::INTEGER, $4::INTEGER) AS n
    WHERE NOT EXISTS (
        SELECT 1
        FROM cloned_pods cp
        WHERE cp.network_number = n
    )
      AND NOT EXISTS (
        SELECT 1
        FROM pod_dev_network_allocations pdna
        WHERE pdna.network_number = n
    )
    ORDER BY n
    LIMIT 1
)
INSERT INTO pod_dev_network_allocations (
    pod_folder_id,
    network_number,
    network_profile_key
)
SELECT
    $1,
    candidate.network_number,
    $2
FROM candidate
RETURNING
    pod_folder_id,
    network_number,
    network_profile_key,
    created_at,
    updated_at
`

type InsertPodDevNetworkAllocationParams struct {
	PodFolderID       uuid.UUID `json:"pod_folder_id"`
	NetworkProfileKey string    `json:"network_profile_key"`
	MinNetworkNumber  int32     `json:"min_network_number"`
	MaxNetworkNumber  int32     `json:"max_network_number"`
}

func (q *Queries) InsertPodDevNetworkAllocation(ctx context.Context, arg InsertPodDevNetworkAllocationParams) (PodDevNetworkAllocations, error) {
	row := q.db.QueryRow(ctx, insertPodDevNetworkAllocation,
		arg.PodFolderID,
		arg.NetworkProfileKey,
		arg.MinNetworkNumber,
		arg.MaxNetworkNumber,
	)
	var i PodDevNetworkAllocations
	err := row.Scan(
		&i.PodFolderID,
		&i.NetworkNumber,
		&i.NetworkProfileKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertPodDevVMNetworkAssignment = `-- name: InsertPodDevVMNetworkAssignment :exec
INSERT INTO pod_dev_vm_network_assignments (
    inventory_item_id,
    pod_folder_id,
    is_router,
    segment_key
) VALUES ($1, $2, $3, $4)
`

type InsertPodDevVMNetworkAssignmentParams struct {
	InventoryItemID uuid.UUID `json:"inventory_item_id"`
	PodFolderID     uuid.UUID `json:"pod_folder_id"`
	IsRouter        bool      `json:"is_router"`
	SegmentKey      *string   `json:"segment_key"`
}

func (q *Queries) InsertPodDevVMNetworkAssignment(ctx context.Context, arg InsertPodDevVMNetworkAssignmentParams) error {
	_, err := q.db.Exec(ctx, insertPodDevVMNetworkAssignment,
		arg.InventoryItemID,
		arg.PodFolderID,
		arg.IsRouter,
		arg.SegmentKey,
	)
	return err
}

const listPodDevVMNetworkAssignments = `-- name: ListPodDevVMNetworkAssignments :many
SELECT
    inventory_item_id,
    pod_folder_id,
    is_router,
    segment_key,
    created_at,
    updated_at
FROM pod_dev_vm_network_assignments
WHERE pod_folder_id = $1
ORDER BY is_router DESC, created_at ASC
`

func (q *Queries) ListPodDevVMNetworkAssignments(ctx context.Context, podFolderID uuid.UUID) ([]PodDevVmNetworkAssignments, error) {
	rows, err := q.db.Query(ctx, listPodDevVMNetworkAssignments, podFolderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PodDevVmNetworkAssignments
	for rows.Next() {
		var i PodDevVmNetworkAssignments
		if err := rows.Scan(
			&i.InventoryItemID,
			&i.PodFolderID,
			&i.IsRouter,
			&i.SegmentKey,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
