// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pod_clone_targets.sql

package database

import (
	"context"
)

const clearDefaultPodCloneTarget = `-- name: ClearDefaultPodCloneTarget :exec
UPDATE pod_clone_targets
SET is_default = false
WHERE is_default
`

func (q *Queries) ClearDefaultPodCloneTarget(ctx context.Context) error {
	_, err := q.db.Exec(ctx, clearDefaultPodCloneTarget)
	return err
}

const clearPersonalPodCloneTarget = `-- name: ClearPersonalPodCloneTarget :exec
UPDATE pod_clone_targets
SET is_personal = false
WHERE is_personal
`

func (q *Queries) ClearPersonalPodCloneTarget(ctx context.Context) error {
	_, err := q.db.Exec(ctx, clearPersonalPodCloneTarget)
	return err
}

const countPodCloneTargetReferences = `-- name: CountPodCloneTargetReferences :one
SELECT
    (SELECT count(*) FROM published_pods pp WHERE pp.clone_target_key = $1) AS published_pod_count,
    (SELECT count(*) FROM cloned_pods cp WHERE cp.clone_target_key = $1) AS cloned_pod_count,
    (SELECT count(*) FROM pod_network_allocations pna WHERE pna.clone_target_key = $1) AS allocation_count,
    (SELECT count(*) FROM personal_pods pp2 WHERE pp2.clone_target_key = $1) AS personal_pod_count
`

type CountPodCloneTargetReferencesRow struct {
	PublishedPodCount int64 `json:"published_pod_count"`
	ClonedPodCount    int64 `json:"cloned_pod_count"`
	AllocationCount   int64 `json:"allocation_count"`
	PersonalPodCount  int64 `json:"personal_pod_count"`
}

func (q *Queries) CountPodCloneTargetReferences(ctx context.Context, targetKey string) (CountPodCloneTargetReferencesRow, error) {
	row := q.db.QueryRow(ctx, countPodCloneTargetReferences, targetKey)
	var i CountPodCloneTargetReferencesRow
	err := row.Scan(
		&i.PublishedPodCount,
		&i.ClonedPodCount,
		&i.AllocationCount,
		&i.PersonalPodCount,
	)
	return i, err
}

const createPodCloneTarget = `-- name: CreatePodCloneTarget :one
INSERT INTO pod_clone_targets (
    key,
    label,
    network_profile_key,
    lan_vnet,
    dmz_vnet,
    wan_bridge,
    wan_subnet,
    network_min,
    network_max,
    cloud_init_storage,
    is_default,
    is_personal
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
RETURNING
    key,
    label,
    network_profile_key,
    lan_vnet,
    dmz_vnet,
    wan_bridge,
    wan_subnet,
    network_min,
    network_max,
    cloud_init_storage,
    is_default,
    is_personal,
    created_at,
    updated_at
`

type CreatePodCloneTargetParams struct {
	Key               string  `json:"key"`
	Label             string  `json:"label"`
	NetworkProfileKey string  `json:"network_profile_key"`
	LanVnet           string  `json:"lan_vnet"`
	DmzVnet           *string `json:"dmz_vnet"`
	WanBridge         string  `json:"wan_bridge"`
	WanSubnet         string  `json:"wan_subnet"`
	NetworkMin        int32   `json:"network_min"`
	NetworkMax        int32   `json:"network_max"`
	CloudInitStorage  string  `json:"cloud_init_storage"`
	IsDefault         bool    `json:"is_default"`
	IsPersonal        bool    `json:"is_personal"`
}

func (q *Queries) CreatePodCloneTarget(ctx context.Context, arg CreatePodCloneTargetParams) (PodCloneTargets, error) {
	row := q.db.QueryRow(ctx, createPodCloneTarget,
		arg.Key,
		arg.Label,
		arg.NetworkProfileKey,
		arg.LanVnet,
		arg.DmzVnet,
		arg.WanBridge,
		arg.WanSubnet,
		arg.NetworkMin,
		arg.NetworkMax,
		arg.CloudInitStorage,
		arg.IsDefault,
		arg.IsPersonal,
	)
	var i PodCloneTargets
	err := row.Scan(
		&i.Key,
		&i.Label,
		&i.NetworkProfileKey,
		&i.LanVnet,
		&i.DmzVnet,
		&i.WanBridge,
		&i.WanSubnet,
		&i.NetworkMin,
		&i.NetworkMax,
		&i.CloudInitStorage,
		&i.IsDefault,
		&i.IsPersonal,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePodCloneTarget = `-- name: DeletePodCloneTarget :execrows
DELETE FROM pod_clone_targets
WHERE key = $1
  AND NOT is_default
  AND NOT is_personal
`

func (q *Queries) DeletePodCloneTarget(ctx context.Context, key string) (int64, error) {
	result, err := q.db.Exec(ctx, deletePodCloneTarget, key)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getDefaultPodCloneTarget = `-- name: GetDefaultPodCloneTarget :one
SELECT
    key,
    label,
    network_profile_key,
    lan_vnet,
    dmz_vnet,
    wan_bridge,
    wan_subnet,
    network_min,
    network_max,
    cloud_init_storage,
    is_default,
    is_personal,
    created_at,
    updated_at
FROM pod_clone_targets
WHERE is_default
`

func (q *Queries) GetDefaultPodCloneTarget(ctx context.Context) (PodCloneTargets, error) {
	row := q.db.QueryRow(ctx, getDefaultPodCloneTarget)
	var i PodCloneTargets
	err := row.Scan(
		&i.Key,
		&i.Label,
		&i.NetworkProfileKey,
		&i.LanVnet,
		&i.DmzVnet,
		&i.WanBridge,
		&i.WanSubnet,
		&i.NetworkMin,
		&i.NetworkMax,
		&i.CloudInitStorage,
		&i.IsDefault,
		&i.IsPersonal,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPersonalPodCloneTarget = `-- name: GetPersonalPodCloneTarget :one
SELECT
    key,
    label,
    network_profile_key,
    lan_vnet,
    dmz_vnet,
    wan_bridge,
    wan_subnet,
    network_min,
    network_max,
    cloud_init_storage,
    is_default,
    is_personal,
    created_at,
    updated_at
FROM pod_clone_targets
WHERE is_personal
`

func (q *Queries) GetPersonalPodCloneTarget(ctx context.Context) (PodCloneTargets, error) {
	row := q.db.QueryRow(ctx, getPersonalPodCloneTarget)
	var i PodCloneTargets
	err := row.Scan(
		&i.Key,
		&i.Label,
		&i.NetworkProfileKey,
		&i.LanVnet,
		&i.DmzVnet,
		&i.WanBridge,
		&i.WanSubnet,
		&i.NetworkMin,
		&i.NetworkMax,
		&i.CloudInitStorage,
		&i.IsDefault,
		&i.IsPersonal,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPodCloneTarget = `-- name: GetPodCloneTarget :one
SELECT
    key,
    label,
    network_profile_key,
    lan_vnet,
    dmz_vnet,
    wan_bridge,
    wan_subnet,
    network_min,
    network_max,
    cloud_init_storage,
    is_default,
    is_personal,
    created_at,
    updated_at
FROM pod_clone_targets
WHERE key = $1
`

func (q *Queries) GetPodCloneTarget(ctx context.Context, key string) (PodCloneTargets, error) {
	row := q.db.QueryRow(ctx, getPodCloneTarget, key)
	var i PodCloneTargets
	err := row.Scan(
		&i.Key,
		&i.Label,
		&i.NetworkProfileKey,
		&i.LanVnet,
		&i.DmzVnet,
		&i.WanBridge,
		&i.WanSubnet,
		&i.NetworkMin,
		&i.NetworkMax,
		&i.CloudInitStorage,
		&i.IsDefault,
		&i.IsPersonal,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPodCloneTargets = `-- name: ListPodCloneTargets :many
SELECT
    key,
    label,
    network_profile_key,
    lan_vnet,
    dmz_vnet,
    wan_bridge,
    wan_subnet,
    network_min,
    network_max,
    cloud_init_storage,
    is_default,
    is_personal,
    created_at,
    updated_at
FROM pod_clone_targets
ORDER BY is_default DESC, lower(label) ASC, key ASC
`

func (q *Queries) ListPodCloneTargets(ctx context.Context) ([]PodCloneTargets, error) {
	rows, err := q.db.Query(ctx, listPodCloneTargets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PodCloneTargets
	for rows.Next() {
		var i PodCloneTargets
		if err := rows.Scan(
			&i.Key,
			&i.Label,
			&i.NetworkProfileKey,
			&i.LanVnet,
			&i.DmzVnet,
			&i.WanBridge,
			&i.WanSubnet,
			&i.NetworkMin,
			&i.NetworkMax,
			&i.CloudInitStorage,
			&i.IsDefault,
			&i.IsPersonal,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockPodCloneTargetRoles = `-- name: LockPodCloneTargetRoles :exec
LOCK TABLE pod_clone_targets IN SHARE ROW EXCLUSIVE MODE
`

// Role changes take this lock inside a transaction so two administrators cannot
// assign different targets to the same singleton role concurrently.
func (q *Queries) LockPodCloneTargetRoles(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockPodCloneTargetRoles)
	return err
}

const updatePodCloneTarget = `-- name: UpdatePodCloneTarget :one
UPDATE pod_clone_targets
   SET label                        = $1,
       network_profile_key          = $2,
       lan_vnet                     = $3,
       dmz_vnet                     = $4,
       wan_bridge                   = $5,
       wan_subnet                   = $6,
       network_min                  = $7,
       network_max                  = $8,
       cloud_init_storage           = $9,
       is_default                   = $10,
       is_personal                  = $11
 WHERE key = $12
RETURNING
    key,
    label,
    network_profile_key,
    lan_vnet,
    dmz_vnet,
    wan_bridge,
    wan_subnet,
    network_min,
    network_max,
    cloud_init_storage,
    is_default,
    is_personal,
    created_at,
    updated_at
`

type UpdatePodCloneTargetParams struct {
	Label             string  `json:"label"`
	NetworkProfileKey string  `json:"network_profile_key"`
	LanVnet           string  `json:"lan_vnet"`
	DmzVnet           *string `json:"dmz_vnet"`
	WanBridge         string  `json:"wan_bridge"`
	WanSubnet         string  `json:"wan_subnet"`
	NetworkMin        int32   `json:"network_min"`
	NetworkMax        int32   `json:"network_max"`
	CloudInitStorage  string  `json:"cloud_init_storage"`
	IsDefault         bool    `json:"is_default"`
	IsPersonal        bool    `json:"is_personal"`
	Key               string  `json:"key"`
}

func (q *Queries) UpdatePodCloneTarget(ctx context.Context, arg UpdatePodCloneTargetParams) (PodCloneTargets, error) {
	row := q.db.QueryRow(ctx, updatePodCloneTarget,
		arg.Label,
		arg.NetworkProfileKey,
		arg.LanVnet,
		arg.DmzVnet,
		arg.WanBridge,
		arg.WanSubnet,
		arg.NetworkMin,
		arg.NetworkMax,
		arg.CloudInitStorage,
		arg.IsDefault,
		arg.IsPersonal,
		arg.Key,
	)
	var i PodCloneTargets
	err := row.Scan(
		&i.Key,
		&i.Label,
		&i.NetworkProfileKey,
		&i.LanVnet,
		&i.DmzVnet,
		&i.WanBridge,
		&i.WanSubnet,
		&i.NetworkMin,
		&i.NetworkMax,
		&i.CloudInitStorage,
		&i.IsDefault,
		&i.IsPersonal,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
