// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pod_clone_targets.sql

package database

import (
	"context"
)

const countPodCloneTargetReferences = `-- name: CountPodCloneTargetReferences :one
SELECT
    (SELECT count(*) FROM published_pods pp WHERE pp.clone_target_key = $1) AS published_pod_count,
    (SELECT count(*) FROM cloned_pods cp WHERE cp.clone_target_key = $1) AS cloned_pod_count,
    (SELECT count(*) FROM pod_network_allocations pna WHERE pna.clone_target_key = $1) AS allocation_count,
    (SELECT count(*) FROM personal_pods pp2 WHERE pp2.clone_target_key = $1) AS personal_pod_count
`

type CountPodCloneTargetReferencesRow struct {
	PublishedPodCount int64 `json:"published_pod_count"`
	ClonedPodCount    int64 `json:"cloned_pod_count"`
	AllocationCount   int64 `json:"allocation_count"`
	PersonalPodCount  int64 `json:"personal_pod_count"`
}

func (q *Queries) CountPodCloneTargetReferences(ctx context.Context, targetKey string) (CountPodCloneTargetReferencesRow, error) {
	row := q.db.QueryRow(ctx, countPodCloneTargetReferences, targetKey)
	var i CountPodCloneTargetReferencesRow
	err := row.Scan(
		&i.PublishedPodCount,
		&i.ClonedPodCount,
		&i.AllocationCount,
		&i.PersonalPodCount,
	)
	return i, err
}

const countPodCloneTargets = `-- name: CountPodCloneTargets :one
SELECT count(*) FROM pod_clone_targets
`

func (q *Queries) CountPodCloneTargets(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPodCloneTargets)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPodCloneTarget = `-- name: CreatePodCloneTarget :one
INSERT INTO pod_clone_targets (
    key,
    label,
    network_profile_key,
    lan_vnet,
    dmz_vnet,
    wan_bridge,
    wan_subnet,
    network_min,
    network_max,
    cloud_init_storage
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING
    key,
    label,
    network_profile_key,
    lan_vnet,
    dmz_vnet,
    wan_bridge,
    wan_subnet,
    network_min,
    network_max,
    cloud_init_storage,
    is_default,
    is_personal,
    created_at,
    updated_at
`

type CreatePodCloneTargetParams struct {
	Key               string  `json:"key"`
	Label             string  `json:"label"`
	NetworkProfileKey string  `json:"network_profile_key"`
	LanVnet           string  `json:"lan_vnet"`
	DmzVnet           *string `json:"dmz_vnet"`
	WanBridge         string  `json:"wan_bridge"`
	WanSubnet         string  `json:"wan_subnet"`
	NetworkMin        int32   `json:"network_min"`
	NetworkMax        int32   `json:"network_max"`
	CloudInitStorage  string  `json:"cloud_init_storage"`
}

func (q *Queries) CreatePodCloneTarget(ctx context.Context, arg CreatePodCloneTargetParams) (PodCloneTargets, error) {
	row := q.db.QueryRow(ctx, createPodCloneTarget,
		arg.Key,
		arg.Label,
		arg.NetworkProfileKey,
		arg.LanVnet,
		arg.DmzVnet,
		arg.WanBridge,
		arg.WanSubnet,
		arg.NetworkMin,
		arg.NetworkMax,
		arg.CloudInitStorage,
	)
	var i PodCloneTargets
	err := row.Scan(
		&i.Key,
		&i.Label,
		&i.NetworkProfileKey,
		&i.LanVnet,
		&i.DmzVnet,
		&i.WanBridge,
		&i.WanSubnet,
		&i.NetworkMin,
		&i.NetworkMax,
		&i.CloudInitStorage,
		&i.IsDefault,
		&i.IsPersonal,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePodCloneTarget = `-- name: DeletePodCloneTarget :execrows
DELETE FROM pod_clone_targets
WHERE key = $1
  AND NOT is_default
`

func (q *Queries) DeletePodCloneTarget(ctx context.Context, key string) (int64, error) {
	result, err := q.db.Exec(ctx, deletePodCloneTarget, key)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getDefaultPodCloneTarget = `-- name: GetDefaultPodCloneTarget :one
SELECT
    key,
    label,
    network_profile_key,
    lan_vnet,
    dmz_vnet,
    wan_bridge,
    wan_subnet,
    network_min,
    network_max,
    cloud_init_storage,
    is_default,
    is_personal,
    created_at,
    updated_at
FROM pod_clone_targets
WHERE is_default
`

func (q *Queries) GetDefaultPodCloneTarget(ctx context.Context) (PodCloneTargets, error) {
	row := q.db.QueryRow(ctx, getDefaultPodCloneTarget)
	var i PodCloneTargets
	err := row.Scan(
		&i.Key,
		&i.Label,
		&i.NetworkProfileKey,
		&i.LanVnet,
		&i.DmzVnet,
		&i.WanBridge,
		&i.WanSubnet,
		&i.NetworkMin,
		&i.NetworkMax,
		&i.CloudInitStorage,
		&i.IsDefault,
		&i.IsPersonal,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPersonalPodCloneTarget = `-- name: GetPersonalPodCloneTarget :one
SELECT
    key,
    label,
    network_profile_key,
    lan_vnet,
    dmz_vnet,
    wan_bridge,
    wan_subnet,
    network_min,
    network_max,
    cloud_init_storage,
    is_default,
    is_personal,
    created_at,
    updated_at
FROM pod_clone_targets
WHERE is_personal
`

func (q *Queries) GetPersonalPodCloneTarget(ctx context.Context) (PodCloneTargets, error) {
	row := q.db.QueryRow(ctx, getPersonalPodCloneTarget)
	var i PodCloneTargets
	err := row.Scan(
		&i.Key,
		&i.Label,
		&i.NetworkProfileKey,
		&i.LanVnet,
		&i.DmzVnet,
		&i.WanBridge,
		&i.WanSubnet,
		&i.NetworkMin,
		&i.NetworkMax,
		&i.CloudInitStorage,
		&i.IsDefault,
		&i.IsPersonal,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPodCloneTarget = `-- name: GetPodCloneTarget :one
SELECT
    key,
    label,
    network_profile_key,
    lan_vnet,
    dmz_vnet,
    wan_bridge,
    wan_subnet,
    network_min,
    network_max,
    cloud_init_storage,
    is_default,
    is_personal,
    created_at,
    updated_at
FROM pod_clone_targets
WHERE key = $1
`

func (q *Queries) GetPodCloneTarget(ctx context.Context, key string) (PodCloneTargets, error) {
	row := q.db.QueryRow(ctx, getPodCloneTarget, key)
	var i PodCloneTargets
	err := row.Scan(
		&i.Key,
		&i.Label,
		&i.NetworkProfileKey,
		&i.LanVnet,
		&i.DmzVnet,
		&i.WanBridge,
		&i.WanSubnet,
		&i.NetworkMin,
		&i.NetworkMax,
		&i.CloudInitStorage,
		&i.IsDefault,
		&i.IsPersonal,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertDefaultPodCloneTarget = `-- name: InsertDefaultPodCloneTarget :exec
INSERT INTO pod_clone_targets (
    key,
    label,
    network_profile_key,
    lan_vnet,
    dmz_vnet,
    wan_bridge,
    wan_subnet,
    network_min,
    network_max,
    cloud_init_storage,
    is_default
)
SELECT
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    true
WHERE NOT EXISTS (SELECT 1 FROM pod_clone_targets)
`

type InsertDefaultPodCloneTargetParams struct {
	Key               string  `json:"key"`
	Label             string  `json:"label"`
	NetworkProfileKey string  `json:"network_profile_key"`
	LanVnet           string  `json:"lan_vnet"`
	DmzVnet           *string `json:"dmz_vnet"`
	WanBridge         string  `json:"wan_bridge"`
	WanSubnet         string  `json:"wan_subnet"`
	NetworkMin        int32   `json:"network_min"`
	NetworkMax        int32   `json:"network_max"`
	CloudInitStorage  string  `json:"cloud_init_storage"`
}

func (q *Queries) InsertDefaultPodCloneTarget(ctx context.Context, arg InsertDefaultPodCloneTargetParams) error {
	_, err := q.db.Exec(ctx, insertDefaultPodCloneTarget,
		arg.Key,
		arg.Label,
		arg.NetworkProfileKey,
		arg.LanVnet,
		arg.DmzVnet,
		arg.WanBridge,
		arg.WanSubnet,
		arg.NetworkMin,
		arg.NetworkMax,
		arg.CloudInitStorage,
	)
	return err
}

const insertPersonalPodCloneTarget = `-- name: InsertPersonalPodCloneTarget :exec
INSERT INTO pod_clone_targets (
    key,
    label,
    network_profile_key,
    lan_vnet,
    wan_bridge,
    wan_subnet,
    network_min,
    network_max,
    cloud_init_storage,
    is_personal
)
SELECT
    $1,
    $2,
    'lan-router-v1',
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    true
WHERE NOT EXISTS (SELECT 1 FROM pod_clone_targets WHERE is_personal)
`

type InsertPersonalPodCloneTargetParams struct {
	Key              string `json:"key"`
	Label            string `json:"label"`
	LanVnet          string `json:"lan_vnet"`
	WanBridge        string `json:"wan_bridge"`
	WanSubnet        string `json:"wan_subnet"`
	NetworkMin       int32  `json:"network_min"`
	NetworkMax       int32  `json:"network_max"`
	CloudInitStorage string `json:"cloud_init_storage"`
}

func (q *Queries) InsertPersonalPodCloneTarget(ctx context.Context, arg InsertPersonalPodCloneTargetParams) error {
	_, err := q.db.Exec(ctx, insertPersonalPodCloneTarget,
		arg.Key,
		arg.Label,
		arg.LanVnet,
		arg.WanBridge,
		arg.WanSubnet,
		arg.NetworkMin,
		arg.NetworkMax,
		arg.CloudInitStorage,
	)
	return err
}

const listPodCloneTargets = `-- name: ListPodCloneTargets :many
SELECT
    key,
    label,
    network_profile_key,
    lan_vnet,
    dmz_vnet,
    wan_bridge,
    wan_subnet,
    network_min,
    network_max,
    cloud_init_storage,
    is_default,
    is_personal,
    created_at,
    updated_at
FROM pod_clone_targets
ORDER BY is_default DESC, lower(label) ASC, key ASC
`

func (q *Queries) ListPodCloneTargets(ctx context.Context) ([]PodCloneTargets, error) {
	rows, err := q.db.Query(ctx, listPodCloneTargets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PodCloneTargets
	for rows.Next() {
		var i PodCloneTargets
		if err := rows.Scan(
			&i.Key,
			&i.Label,
			&i.NetworkProfileKey,
			&i.LanVnet,
			&i.DmzVnet,
			&i.WanBridge,
			&i.WanSubnet,
			&i.NetworkMin,
			&i.NetworkMax,
			&i.CloudInitStorage,
			&i.IsDefault,
			&i.IsPersonal,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePodCloneTarget = `-- name: UpdatePodCloneTarget :one
UPDATE pod_clone_targets
   SET label                        = $1,
       network_profile_key          = $2,
       lan_vnet                     = $3,
       dmz_vnet                     = $4,
       wan_bridge                   = $5,
       wan_subnet                   = $6,
       network_min                  = $7,
       network_max                  = $8,
       cloud_init_storage           = $9
 WHERE key = $10
RETURNING
    key,
    label,
    network_profile_key,
    lan_vnet,
    dmz_vnet,
    wan_bridge,
    wan_subnet,
    network_min,
    network_max,
    cloud_init_storage,
    is_default,
    is_personal,
    created_at,
    updated_at
`

type UpdatePodCloneTargetParams struct {
	Label             string  `json:"label"`
	NetworkProfileKey string  `json:"network_profile_key"`
	LanVnet           string  `json:"lan_vnet"`
	DmzVnet           *string `json:"dmz_vnet"`
	WanBridge         string  `json:"wan_bridge"`
	WanSubnet         string  `json:"wan_subnet"`
	NetworkMin        int32   `json:"network_min"`
	NetworkMax        int32   `json:"network_max"`
	CloudInitStorage  string  `json:"cloud_init_storage"`
	Key               string  `json:"key"`
}

func (q *Queries) UpdatePodCloneTarget(ctx context.Context, arg UpdatePodCloneTargetParams) (PodCloneTargets, error) {
	row := q.db.QueryRow(ctx, updatePodCloneTarget,
		arg.Label,
		arg.NetworkProfileKey,
		arg.LanVnet,
		arg.DmzVnet,
		arg.WanBridge,
		arg.WanSubnet,
		arg.NetworkMin,
		arg.NetworkMax,
		arg.CloudInitStorage,
		arg.Key,
	)
	var i PodCloneTargets
	err := row.Scan(
		&i.Key,
		&i.Label,
		&i.NetworkProfileKey,
		&i.LanVnet,
		&i.DmzVnet,
		&i.WanBridge,
		&i.WanSubnet,
		&i.NetworkMin,
		&i.NetworkMax,
		&i.CloudInitStorage,
		&i.IsDefault,
		&i.IsPersonal,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
