// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pods_published.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPublishedPod = `-- name: CreatePublishedPod :one
INSERT INTO published_pods (
    id,
    title,
    slug,
    description,
    image_url,
    status,
    source_folder_id,
    publisher_principal_id,
    network_profile_key
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING
    id,
    title,
    slug,
    description,
    image_url,
    status,
    source_folder_id,
    publisher_principal_id,
    network_profile_key,
    clone_count,
    created_at,
    updated_at
`

type CreatePublishedPodParams struct {
	ID                   uuid.UUID          `json:"id"`
	Title                string             `json:"title"`
	Slug                 string             `json:"slug"`
	Description          string             `json:"description"`
	ImageUrl             string             `json:"image_url"`
	Status               PublishedPodStatus `json:"status"`
	SourceFolderID       uuid.UUID          `json:"source_folder_id"`
	PublisherPrincipalID uuid.UUID          `json:"publisher_principal_id"`
	NetworkProfileKey    string             `json:"network_profile_key"`
}

func (q *Queries) CreatePublishedPod(ctx context.Context, arg CreatePublishedPodParams) (PublishedPods, error) {
	row := q.db.QueryRow(ctx, createPublishedPod,
		arg.ID,
		arg.Title,
		arg.Slug,
		arg.Description,
		arg.ImageUrl,
		arg.Status,
		arg.SourceFolderID,
		arg.PublisherPrincipalID,
		arg.NetworkProfileKey,
	)
	var i PublishedPods
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.ImageUrl,
		&i.Status,
		&i.SourceFolderID,
		&i.PublisherPrincipalID,
		&i.NetworkProfileKey,
		&i.CloneCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteClonedPodQuestionAnswersByQuestionID = `-- name: DeleteClonedPodQuestionAnswersByQuestionID :exec
DELETE FROM cloned_pod_question_answers
WHERE question_id = $1
`

func (q *Queries) DeleteClonedPodQuestionAnswersByQuestionID(ctx context.Context, questionID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteClonedPodQuestionAnswersByQuestionID, questionID)
	return err
}

const deletePublishedPod = `-- name: DeletePublishedPod :execrows
DELETE FROM published_pods
WHERE id = $1
`

func (q *Queries) DeletePublishedPod(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deletePublishedPod, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deletePublishedPodAudience = `-- name: DeletePublishedPodAudience :exec
DELETE FROM published_pod_audience
WHERE pod_id = $1
`

func (q *Queries) DeletePublishedPodAudience(ctx context.Context, podID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePublishedPodAudience, podID)
	return err
}

const deletePublishedPodCreators = `-- name: DeletePublishedPodCreators :exec
DELETE FROM published_pod_creators
WHERE pod_id = $1
`

func (q *Queries) DeletePublishedPodCreators(ctx context.Context, podID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePublishedPodCreators, podID)
	return err
}

const deletePublishedPodQuestionsExcept = `-- name: DeletePublishedPodQuestionsExcept :exec
DELETE FROM published_pod_task_questions q
USING published_pod_tasks t
WHERE q.task_id = t.id
  AND t.pod_id = $1
  AND NOT (q.id = ANY($2::UUID[]))
`

type DeletePublishedPodQuestionsExceptParams struct {
	PodID   uuid.UUID   `json:"pod_id"`
	KeepIds []uuid.UUID `json:"keep_ids"`
}

func (q *Queries) DeletePublishedPodQuestionsExcept(ctx context.Context, arg DeletePublishedPodQuestionsExceptParams) error {
	_, err := q.db.Exec(ctx, deletePublishedPodQuestionsExcept, arg.PodID, arg.KeepIds)
	return err
}

const deletePublishedPodTasksExcept = `-- name: DeletePublishedPodTasksExcept :exec
DELETE FROM published_pod_tasks
WHERE pod_id = $1
  AND NOT (id = ANY($2::UUID[]))
`

type DeletePublishedPodTasksExceptParams struct {
	PodID   uuid.UUID   `json:"pod_id"`
	KeepIds []uuid.UUID `json:"keep_ids"`
}

func (q *Queries) DeletePublishedPodTasksExcept(ctx context.Context, arg DeletePublishedPodTasksExceptParams) error {
	_, err := q.db.Exec(ctx, deletePublishedPodTasksExcept, arg.PodID, arg.KeepIds)
	return err
}

const deletePublishedPodVMs = `-- name: DeletePublishedPodVMs :exec
DELETE FROM published_pod_vms
WHERE pod_id = $1
`

func (q *Queries) DeletePublishedPodVMs(ctx context.Context, podID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePublishedPodVMs, podID)
	return err
}

const deletePublishedPodVMsExcept = `-- name: DeletePublishedPodVMsExcept :exec
DELETE FROM published_pod_vms
WHERE pod_id = $1
  AND NOT (id = ANY($2::UUID[]))
`

type DeletePublishedPodVMsExceptParams struct {
	PodID   uuid.UUID   `json:"pod_id"`
	KeepIds []uuid.UUID `json:"keep_ids"`
}

func (q *Queries) DeletePublishedPodVMsExcept(ctx context.Context, arg DeletePublishedPodVMsExceptParams) error {
	_, err := q.db.Exec(ctx, deletePublishedPodVMsExcept, arg.PodID, arg.KeepIds)
	return err
}

const getPublishedPodByID = `-- name: GetPublishedPodByID :one
SELECT
    pp.id,
    pp.title,
    pp.slug,
    pp.description,
    pp.image_url,
    pp.status,
    pp.source_folder_id,
    source_folder.name AS source_folder_name,
    pp.publisher_principal_id,
    pp.network_profile_key,
    pp.clone_count,
    pp.created_at,
    pp.updated_at
FROM published_pods pp
JOIN inventory_items source_folder
  ON source_folder.id = pp.source_folder_id
WHERE pp.id = $1
`

type GetPublishedPodByIDRow struct {
	ID                   uuid.UUID          `json:"id"`
	Title                string             `json:"title"`
	Slug                 string             `json:"slug"`
	Description          string             `json:"description"`
	ImageUrl             string             `json:"image_url"`
	Status               PublishedPodStatus `json:"status"`
	SourceFolderID       uuid.UUID          `json:"source_folder_id"`
	SourceFolderName     string             `json:"source_folder_name"`
	PublisherPrincipalID uuid.UUID          `json:"publisher_principal_id"`
	NetworkProfileKey    string             `json:"network_profile_key"`
	CloneCount           int32              `json:"clone_count"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetPublishedPodByID(ctx context.Context, id uuid.UUID) (GetPublishedPodByIDRow, error) {
	row := q.db.QueryRow(ctx, getPublishedPodByID, id)
	var i GetPublishedPodByIDRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.ImageUrl,
		&i.Status,
		&i.SourceFolderID,
		&i.SourceFolderName,
		&i.PublisherPrincipalID,
		&i.NetworkProfileKey,
		&i.CloneCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPublishedPodSlugConflict = `-- name: GetPublishedPodSlugConflict :one
SELECT id
FROM published_pods
WHERE slug = $1
  AND id <> $2
LIMIT 1
`

type GetPublishedPodSlugConflictParams struct {
	Slug string    `json:"slug"`
	ID   uuid.UUID `json:"id"`
}

func (q *Queries) GetPublishedPodSlugConflict(ctx context.Context, arg GetPublishedPodSlugConflictParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getPublishedPodSlugConflict, arg.Slug, arg.ID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getVisiblePublishedPodBySlug = `-- name: GetVisiblePublishedPodBySlug :one
SELECT
    pp.id,
    pp.title,
    pp.slug,
    pp.description,
    pp.image_url,
    pp.status,
    pp.source_folder_id,
    source_folder.name AS source_folder_name,
    pp.publisher_principal_id,
    pp.network_profile_key,
    pp.clone_count,
    pp.created_at,
    pp.updated_at
FROM published_pods pp
JOIN inventory_items source_folder
  ON source_folder.id = pp.source_folder_id
WHERE pp.slug = $1
  AND pp.status = 'listed'
  AND (
      NOT EXISTS (
          SELECT 1
          FROM published_pod_audience audience
          WHERE audience.pod_id = pp.id
      )
      OR EXISTS (
          SELECT 1
          FROM published_pod_audience audience
          WHERE audience.pod_id = pp.id
            AND audience.principal_id IN (
                SELECT ep.principal_id::UUID
                FROM get_user_effective_principals($2) AS ep(principal_id)
            )
      )
  )
`

type GetVisiblePublishedPodBySlugParams struct {
	Slug        string    `json:"slug"`
	PrincipalID uuid.UUID `json:"principal_id"`
}

type GetVisiblePublishedPodBySlugRow struct {
	ID                   uuid.UUID          `json:"id"`
	Title                string             `json:"title"`
	Slug                 string             `json:"slug"`
	Description          string             `json:"description"`
	ImageUrl             string             `json:"image_url"`
	Status               PublishedPodStatus `json:"status"`
	SourceFolderID       uuid.UUID          `json:"source_folder_id"`
	SourceFolderName     string             `json:"source_folder_name"`
	PublisherPrincipalID uuid.UUID          `json:"publisher_principal_id"`
	NetworkProfileKey    string             `json:"network_profile_key"`
	CloneCount           int32              `json:"clone_count"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetVisiblePublishedPodBySlug(ctx context.Context, arg GetVisiblePublishedPodBySlugParams) (GetVisiblePublishedPodBySlugRow, error) {
	row := q.db.QueryRow(ctx, getVisiblePublishedPodBySlug, arg.Slug, arg.PrincipalID)
	var i GetVisiblePublishedPodBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.ImageUrl,
		&i.Status,
		&i.SourceFolderID,
		&i.SourceFolderName,
		&i.PublisherPrincipalID,
		&i.NetworkProfileKey,
		&i.CloneCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertPublishedPodAudience = `-- name: InsertPublishedPodAudience :exec
INSERT INTO published_pod_audience (pod_id, principal_id, sort_order)
VALUES ($1, $2, $3)
`

type InsertPublishedPodAudienceParams struct {
	PodID       uuid.UUID `json:"pod_id"`
	PrincipalID uuid.UUID `json:"principal_id"`
	SortOrder   int32     `json:"sort_order"`
}

func (q *Queries) InsertPublishedPodAudience(ctx context.Context, arg InsertPublishedPodAudienceParams) error {
	_, err := q.db.Exec(ctx, insertPublishedPodAudience, arg.PodID, arg.PrincipalID, arg.SortOrder)
	return err
}

const insertPublishedPodCreator = `-- name: InsertPublishedPodCreator :exec
INSERT INTO published_pod_creators (pod_id, principal_id, sort_order)
VALUES ($1, $2, $3)
`

type InsertPublishedPodCreatorParams struct {
	PodID       uuid.UUID `json:"pod_id"`
	PrincipalID uuid.UUID `json:"principal_id"`
	SortOrder   int32     `json:"sort_order"`
}

func (q *Queries) InsertPublishedPodCreator(ctx context.Context, arg InsertPublishedPodCreatorParams) error {
	_, err := q.db.Exec(ctx, insertPublishedPodCreator, arg.PodID, arg.PrincipalID, arg.SortOrder)
	return err
}

const insertPublishedPodTask = `-- name: InsertPublishedPodTask :one
INSERT INTO published_pod_tasks (id, pod_id, title, content, sort_order)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type InsertPublishedPodTaskParams struct {
	ID        uuid.UUID `json:"id"`
	PodID     uuid.UUID `json:"pod_id"`
	Title     string    `json:"title"`
	Content   string    `json:"content"`
	SortOrder int32     `json:"sort_order"`
}

func (q *Queries) InsertPublishedPodTask(ctx context.Context, arg InsertPublishedPodTaskParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertPublishedPodTask,
		arg.ID,
		arg.PodID,
		arg.Title,
		arg.Content,
		arg.SortOrder,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertPublishedPodTaskQuestion = `-- name: InsertPublishedPodTaskQuestion :exec
INSERT INTO published_pod_task_questions (
    id,
    task_id,
    title,
    answer_outline,
    description,
    hint,
    sort_order
) VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertPublishedPodTaskQuestionParams struct {
	ID            uuid.UUID `json:"id"`
	TaskID        uuid.UUID `json:"task_id"`
	Title         string    `json:"title"`
	AnswerOutline string    `json:"answer_outline"`
	Description   *string   `json:"description"`
	Hint          *string   `json:"hint"`
	SortOrder     int32     `json:"sort_order"`
}

func (q *Queries) InsertPublishedPodTaskQuestion(ctx context.Context, arg InsertPublishedPodTaskQuestionParams) error {
	_, err := q.db.Exec(ctx, insertPublishedPodTaskQuestion,
		arg.ID,
		arg.TaskID,
		arg.Title,
		arg.AnswerOutline,
		arg.Description,
		arg.Hint,
		arg.SortOrder,
	)
	return err
}

const insertPublishedPodVM = `-- name: InsertPublishedPodVM :exec
INSERT INTO published_pod_vms (
    id,
    pod_id,
    source_inventory_item_id,
    name,
    cpu_count,
    memory_mb,
    disk_gb,
    allow_mask,
    deny_mask,
    is_router,
    segment_key,
    sort_order
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
`

type InsertPublishedPodVMParams struct {
	ID                    uuid.UUID `json:"id"`
	PodID                 uuid.UUID `json:"pod_id"`
	SourceInventoryItemID uuid.UUID `json:"source_inventory_item_id"`
	Name                  string    `json:"name"`
	CpuCount              int32     `json:"cpu_count"`
	MemoryMb              int32     `json:"memory_mb"`
	DiskGb                float64   `json:"disk_gb"`
	AllowMask             int64     `json:"allow_mask"`
	DenyMask              int64     `json:"deny_mask"`
	IsRouter              bool      `json:"is_router"`
	SegmentKey            *string   `json:"segment_key"`
	SortOrder             int32     `json:"sort_order"`
}

func (q *Queries) InsertPublishedPodVM(ctx context.Context, arg InsertPublishedPodVMParams) error {
	_, err := q.db.Exec(ctx, insertPublishedPodVM,
		arg.ID,
		arg.PodID,
		arg.SourceInventoryItemID,
		arg.Name,
		arg.CpuCount,
		arg.MemoryMb,
		arg.DiskGb,
		arg.AllowMask,
		arg.DenyMask,
		arg.IsRouter,
		arg.SegmentKey,
		arg.SortOrder,
	)
	return err
}

const listPublishedPodAudienceByPodIDs = `-- name: ListPublishedPodAudienceByPodIDs :many
SELECT
    audience.pod_id,
    p.id,
    p.principal_type,
    p.external_id,
    p.name,
    p.full_name,
    p.description,
    audience.sort_order
FROM published_pod_audience audience
JOIN principals p
  ON p.id = audience.principal_id
WHERE audience.pod_id = ANY($1::UUID[])
ORDER BY audience.pod_id, audience.sort_order ASC
`

type ListPublishedPodAudienceByPodIDsRow struct {
	PodID         uuid.UUID     `json:"pod_id"`
	ID            uuid.UUID     `json:"id"`
	PrincipalType PrincipalType `json:"principal_type"`
	ExternalID    string        `json:"external_id"`
	Name          *string       `json:"name"`
	FullName      *string       `json:"full_name"`
	Description   *string       `json:"description"`
	SortOrder     int32         `json:"sort_order"`
}

func (q *Queries) ListPublishedPodAudienceByPodIDs(ctx context.Context, podIds []uuid.UUID) ([]ListPublishedPodAudienceByPodIDsRow, error) {
	rows, err := q.db.Query(ctx, listPublishedPodAudienceByPodIDs, podIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublishedPodAudienceByPodIDsRow
	for rows.Next() {
		var i ListPublishedPodAudienceByPodIDsRow
		if err := rows.Scan(
			&i.PodID,
			&i.ID,
			&i.PrincipalType,
			&i.ExternalID,
			&i.Name,
			&i.FullName,
			&i.Description,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedPodCreatorsByPodIDs = `-- name: ListPublishedPodCreatorsByPodIDs :many
SELECT
    creator.pod_id,
    p.id,
    p.principal_type,
    p.external_id,
    p.name,
    p.full_name,
    p.description,
    creator.sort_order
FROM published_pod_creators creator
JOIN principals p
  ON p.id = creator.principal_id
WHERE creator.pod_id = ANY($1::UUID[])
ORDER BY creator.pod_id, creator.sort_order ASC
`

type ListPublishedPodCreatorsByPodIDsRow struct {
	PodID         uuid.UUID     `json:"pod_id"`
	ID            uuid.UUID     `json:"id"`
	PrincipalType PrincipalType `json:"principal_type"`
	ExternalID    string        `json:"external_id"`
	Name          *string       `json:"name"`
	FullName      *string       `json:"full_name"`
	Description   *string       `json:"description"`
	SortOrder     int32         `json:"sort_order"`
}

func (q *Queries) ListPublishedPodCreatorsByPodIDs(ctx context.Context, podIds []uuid.UUID) ([]ListPublishedPodCreatorsByPodIDsRow, error) {
	rows, err := q.db.Query(ctx, listPublishedPodCreatorsByPodIDs, podIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublishedPodCreatorsByPodIDsRow
	for rows.Next() {
		var i ListPublishedPodCreatorsByPodIDsRow
		if err := rows.Scan(
			&i.PodID,
			&i.ID,
			&i.PrincipalType,
			&i.ExternalID,
			&i.Name,
			&i.FullName,
			&i.Description,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedPodQuestionsByTaskIDs = `-- name: ListPublishedPodQuestionsByTaskIDs :many
SELECT
    id,
    task_id,
    title,
    answer_outline,
    description,
    hint,
    sort_order
FROM published_pod_task_questions
WHERE task_id = ANY($1::UUID[])
ORDER BY task_id, sort_order ASC
`

type ListPublishedPodQuestionsByTaskIDsRow struct {
	ID            uuid.UUID `json:"id"`
	TaskID        uuid.UUID `json:"task_id"`
	Title         string    `json:"title"`
	AnswerOutline string    `json:"answer_outline"`
	Description   *string   `json:"description"`
	Hint          *string   `json:"hint"`
	SortOrder     int32     `json:"sort_order"`
}

func (q *Queries) ListPublishedPodQuestionsByTaskIDs(ctx context.Context, taskIds []uuid.UUID) ([]ListPublishedPodQuestionsByTaskIDsRow, error) {
	rows, err := q.db.Query(ctx, listPublishedPodQuestionsByTaskIDs, taskIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublishedPodQuestionsByTaskIDsRow
	for rows.Next() {
		var i ListPublishedPodQuestionsByTaskIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.Title,
			&i.AnswerOutline,
			&i.Description,
			&i.Hint,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedPodTasksByPodIDs = `-- name: ListPublishedPodTasksByPodIDs :many
SELECT
    id,
    pod_id,
    title,
    content,
    sort_order
FROM published_pod_tasks
WHERE pod_id = ANY($1::UUID[])
ORDER BY pod_id, sort_order ASC
`

type ListPublishedPodTasksByPodIDsRow struct {
	ID        uuid.UUID `json:"id"`
	PodID     uuid.UUID `json:"pod_id"`
	Title     string    `json:"title"`
	Content   string    `json:"content"`
	SortOrder int32     `json:"sort_order"`
}

func (q *Queries) ListPublishedPodTasksByPodIDs(ctx context.Context, podIds []uuid.UUID) ([]ListPublishedPodTasksByPodIDsRow, error) {
	rows, err := q.db.Query(ctx, listPublishedPodTasksByPodIDs, podIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublishedPodTasksByPodIDsRow
	for rows.Next() {
		var i ListPublishedPodTasksByPodIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.PodID,
			&i.Title,
			&i.Content,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedPodVMsByPodIDs = `-- name: ListPublishedPodVMsByPodIDs :many
SELECT
    id,
    pod_id,
    source_inventory_item_id,
    name,
    cpu_count,
    memory_mb,
    disk_gb,
    allow_mask,
    deny_mask,
    is_router,
    segment_key,
    sort_order
FROM published_pod_vms
WHERE pod_id = ANY($1::UUID[])
ORDER BY pod_id, sort_order ASC
`

type ListPublishedPodVMsByPodIDsRow struct {
	ID                    uuid.UUID `json:"id"`
	PodID                 uuid.UUID `json:"pod_id"`
	SourceInventoryItemID uuid.UUID `json:"source_inventory_item_id"`
	Name                  string    `json:"name"`
	CpuCount              int32     `json:"cpu_count"`
	MemoryMb              int32     `json:"memory_mb"`
	DiskGb                float64   `json:"disk_gb"`
	AllowMask             int64     `json:"allow_mask"`
	DenyMask              int64     `json:"deny_mask"`
	IsRouter              bool      `json:"is_router"`
	SegmentKey            *string   `json:"segment_key"`
	SortOrder             int32     `json:"sort_order"`
}

func (q *Queries) ListPublishedPodVMsByPodIDs(ctx context.Context, podIds []uuid.UUID) ([]ListPublishedPodVMsByPodIDsRow, error) {
	rows, err := q.db.Query(ctx, listPublishedPodVMsByPodIDs, podIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublishedPodVMsByPodIDsRow
	for rows.Next() {
		var i ListPublishedPodVMsByPodIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.PodID,
			&i.SourceInventoryItemID,
			&i.Name,
			&i.CpuCount,
			&i.MemoryMb,
			&i.DiskGb,
			&i.AllowMask,
			&i.DenyMask,
			&i.IsRouter,
			&i.SegmentKey,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedPods = `-- name: ListPublishedPods :many
SELECT
    pp.id,
    pp.title,
    pp.slug,
    pp.description,
    pp.image_url,
    pp.status,
    pp.source_folder_id,
    source_folder.name AS source_folder_name,
    pp.publisher_principal_id,
    pp.network_profile_key,
    pp.clone_count,
    pp.created_at,
    pp.updated_at
FROM published_pods pp
JOIN inventory_items source_folder
  ON source_folder.id = pp.source_folder_id
ORDER BY pp.created_at DESC, lower(pp.title) ASC, pp.title ASC
`

type ListPublishedPodsRow struct {
	ID                   uuid.UUID          `json:"id"`
	Title                string             `json:"title"`
	Slug                 string             `json:"slug"`
	Description          string             `json:"description"`
	ImageUrl             string             `json:"image_url"`
	Status               PublishedPodStatus `json:"status"`
	SourceFolderID       uuid.UUID          `json:"source_folder_id"`
	SourceFolderName     string             `json:"source_folder_name"`
	PublisherPrincipalID uuid.UUID          `json:"publisher_principal_id"`
	NetworkProfileKey    string             `json:"network_profile_key"`
	CloneCount           int32              `json:"clone_count"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListPublishedPods(ctx context.Context) ([]ListPublishedPodsRow, error) {
	rows, err := q.db.Query(ctx, listPublishedPods)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublishedPodsRow
	for rows.Next() {
		var i ListPublishedPodsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.ImageUrl,
			&i.Status,
			&i.SourceFolderID,
			&i.SourceFolderName,
			&i.PublisherPrincipalID,
			&i.NetworkProfileKey,
			&i.CloneCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVisiblePublishedPodsForPrincipal = `-- name: ListVisiblePublishedPodsForPrincipal :many
SELECT
    pp.id,
    pp.title,
    pp.slug,
    pp.description,
    pp.image_url,
    pp.status,
    pp.source_folder_id,
    source_folder.name AS source_folder_name,
    pp.publisher_principal_id,
    pp.network_profile_key,
    pp.clone_count,
    pp.created_at,
    pp.updated_at
FROM published_pods pp
JOIN inventory_items source_folder
  ON source_folder.id = pp.source_folder_id
WHERE pp.status = 'listed'
  AND (
      NOT EXISTS (
          SELECT 1
          FROM published_pod_audience audience
          WHERE audience.pod_id = pp.id
      )
      OR EXISTS (
          SELECT 1
          FROM published_pod_audience audience
          WHERE audience.pod_id = pp.id
            AND audience.principal_id IN (
                SELECT ep.principal_id::UUID
                FROM get_user_effective_principals($1) AS ep(principal_id)
            )
      )
  )
ORDER BY pp.created_at DESC, lower(pp.title) ASC, pp.title ASC
`

type ListVisiblePublishedPodsForPrincipalRow struct {
	ID                   uuid.UUID          `json:"id"`
	Title                string             `json:"title"`
	Slug                 string             `json:"slug"`
	Description          string             `json:"description"`
	ImageUrl             string             `json:"image_url"`
	Status               PublishedPodStatus `json:"status"`
	SourceFolderID       uuid.UUID          `json:"source_folder_id"`
	SourceFolderName     string             `json:"source_folder_name"`
	PublisherPrincipalID uuid.UUID          `json:"publisher_principal_id"`
	NetworkProfileKey    string             `json:"network_profile_key"`
	CloneCount           int32              `json:"clone_count"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListVisiblePublishedPodsForPrincipal(ctx context.Context, principalID uuid.UUID) ([]ListVisiblePublishedPodsForPrincipalRow, error) {
	rows, err := q.db.Query(ctx, listVisiblePublishedPodsForPrincipal, principalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVisiblePublishedPodsForPrincipalRow
	for rows.Next() {
		var i ListVisiblePublishedPodsForPrincipalRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.ImageUrl,
			&i.Status,
			&i.SourceFolderID,
			&i.SourceFolderName,
			&i.PublisherPrincipalID,
			&i.NetworkProfileKey,
			&i.CloneCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const offsetPublishedPodQuestionSortOrders = `-- name: OffsetPublishedPodQuestionSortOrders :exec
UPDATE published_pod_task_questions q
SET sort_order = q.sort_order + $1
FROM published_pod_tasks t
WHERE q.task_id = t.id
  AND t.pod_id = $2
`

type OffsetPublishedPodQuestionSortOrdersParams struct {
	SortOffset int32     `json:"sort_offset"`
	PodID      uuid.UUID `json:"pod_id"`
}

func (q *Queries) OffsetPublishedPodQuestionSortOrders(ctx context.Context, arg OffsetPublishedPodQuestionSortOrdersParams) error {
	_, err := q.db.Exec(ctx, offsetPublishedPodQuestionSortOrders, arg.SortOffset, arg.PodID)
	return err
}

const offsetPublishedPodTaskSortOrders = `-- name: OffsetPublishedPodTaskSortOrders :exec
UPDATE published_pod_tasks
SET sort_order = sort_order + $1
WHERE pod_id = $2
`

type OffsetPublishedPodTaskSortOrdersParams struct {
	SortOffset int32     `json:"sort_offset"`
	PodID      uuid.UUID `json:"pod_id"`
}

func (q *Queries) OffsetPublishedPodTaskSortOrders(ctx context.Context, arg OffsetPublishedPodTaskSortOrdersParams) error {
	_, err := q.db.Exec(ctx, offsetPublishedPodTaskSortOrders, arg.SortOffset, arg.PodID)
	return err
}

const updatePublishedPod = `-- name: UpdatePublishedPod :one
UPDATE published_pods
SET title = $2,
    slug = $3,
    description = $4,
    image_url = $5,
    status = $6,
    source_folder_id = $7
WHERE id = $1
RETURNING
    id,
    title,
    slug,
    description,
    image_url,
    status,
    source_folder_id,
    publisher_principal_id,
    network_profile_key,
    clone_count,
    created_at,
    updated_at
`

type UpdatePublishedPodParams struct {
	ID             uuid.UUID          `json:"id"`
	Title          string             `json:"title"`
	Slug           string             `json:"slug"`
	Description    string             `json:"description"`
	ImageUrl       string             `json:"image_url"`
	Status         PublishedPodStatus `json:"status"`
	SourceFolderID uuid.UUID          `json:"source_folder_id"`
}

func (q *Queries) UpdatePublishedPod(ctx context.Context, arg UpdatePublishedPodParams) (PublishedPods, error) {
	row := q.db.QueryRow(ctx, updatePublishedPod,
		arg.ID,
		arg.Title,
		arg.Slug,
		arg.Description,
		arg.ImageUrl,
		arg.Status,
		arg.SourceFolderID,
	)
	var i PublishedPods
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.ImageUrl,
		&i.Status,
		&i.SourceFolderID,
		&i.PublisherPrincipalID,
		&i.NetworkProfileKey,
		&i.CloneCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePublishedPodStatus = `-- name: UpdatePublishedPodStatus :exec
UPDATE published_pods
SET status = $2
WHERE id = $1
`

type UpdatePublishedPodStatusParams struct {
	ID     uuid.UUID          `json:"id"`
	Status PublishedPodStatus `json:"status"`
}

func (q *Queries) UpdatePublishedPodStatus(ctx context.Context, arg UpdatePublishedPodStatusParams) error {
	_, err := q.db.Exec(ctx, updatePublishedPodStatus, arg.ID, arg.Status)
	return err
}

const updatePublishedPodTask = `-- name: UpdatePublishedPodTask :exec
UPDATE published_pod_tasks
SET
    title = $3,
    content = $4,
    sort_order = $5
WHERE id = $1
  AND pod_id = $2
`

type UpdatePublishedPodTaskParams struct {
	ID        uuid.UUID `json:"id"`
	PodID     uuid.UUID `json:"pod_id"`
	Title     string    `json:"title"`
	Content   string    `json:"content"`
	SortOrder int32     `json:"sort_order"`
}

func (q *Queries) UpdatePublishedPodTask(ctx context.Context, arg UpdatePublishedPodTaskParams) error {
	_, err := q.db.Exec(ctx, updatePublishedPodTask,
		arg.ID,
		arg.PodID,
		arg.Title,
		arg.Content,
		arg.SortOrder,
	)
	return err
}

const updatePublishedPodTaskQuestion = `-- name: UpdatePublishedPodTaskQuestion :exec
UPDATE published_pod_task_questions
SET
    task_id = $2,
    title = $3,
    answer_outline = $4,
    description = $5,
    hint = $6,
    sort_order = $7
WHERE id = $1
`

type UpdatePublishedPodTaskQuestionParams struct {
	ID            uuid.UUID `json:"id"`
	TaskID        uuid.UUID `json:"task_id"`
	Title         string    `json:"title"`
	AnswerOutline string    `json:"answer_outline"`
	Description   *string   `json:"description"`
	Hint          *string   `json:"hint"`
	SortOrder     int32     `json:"sort_order"`
}

func (q *Queries) UpdatePublishedPodTaskQuestion(ctx context.Context, arg UpdatePublishedPodTaskQuestionParams) error {
	_, err := q.db.Exec(ctx, updatePublishedPodTaskQuestion,
		arg.ID,
		arg.TaskID,
		arg.Title,
		arg.AnswerOutline,
		arg.Description,
		arg.Hint,
		arg.SortOrder,
	)
	return err
}

const updatePublishedPodVM = `-- name: UpdatePublishedPodVM :exec
UPDATE published_pod_vms
SET
    source_inventory_item_id = $3,
    name = $4,
    cpu_count = $5,
    memory_mb = $6,
    disk_gb = $7,
    allow_mask = $8,
    deny_mask = $9,
    is_router = $10,
    segment_key = $11,
    sort_order = $12
WHERE id = $1
  AND pod_id = $2
`

type UpdatePublishedPodVMParams struct {
	ID                    uuid.UUID `json:"id"`
	PodID                 uuid.UUID `json:"pod_id"`
	SourceInventoryItemID uuid.UUID `json:"source_inventory_item_id"`
	Name                  string    `json:"name"`
	CpuCount              int32     `json:"cpu_count"`
	MemoryMb              int32     `json:"memory_mb"`
	DiskGb                float64   `json:"disk_gb"`
	AllowMask             int64     `json:"allow_mask"`
	DenyMask              int64     `json:"deny_mask"`
	IsRouter              bool      `json:"is_router"`
	SegmentKey            *string   `json:"segment_key"`
	SortOrder             int32     `json:"sort_order"`
}

func (q *Queries) UpdatePublishedPodVM(ctx context.Context, arg UpdatePublishedPodVMParams) error {
	_, err := q.db.Exec(ctx, updatePublishedPodVM,
		arg.ID,
		arg.PodID,
		arg.SourceInventoryItemID,
		arg.Name,
		arg.CpuCount,
		arg.MemoryMb,
		arg.DiskGb,
		arg.AllowMask,
		arg.DenyMask,
		arg.IsRouter,
		arg.SegmentKey,
		arg.SortOrder,
	)
	return err
}
