// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pods.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countIncorrectOrUnansweredTaskQuestions = `-- name: CountIncorrectOrUnansweredTaskQuestions :one
SELECT COUNT(*)::BIGINT
FROM published_pod_task_questions q
WHERE q.task_id = $2
  AND NOT EXISTS (
      SELECT 1
      FROM cloned_pod_question_answers answer
      WHERE answer.cloned_pod_id = $1
        AND answer.question_id = q.id
        AND answer.is_correct = true
  )
`

type CountIncorrectOrUnansweredTaskQuestionsParams struct {
	ClonedPodID uuid.UUID `json:"cloned_pod_id"`
	TaskID      uuid.UUID `json:"task_id"`
}

func (q *Queries) CountIncorrectOrUnansweredTaskQuestions(ctx context.Context, arg CountIncorrectOrUnansweredTaskQuestionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countIncorrectOrUnansweredTaskQuestions, arg.ClonedPodID, arg.TaskID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createPublishedPod = `-- name: CreatePublishedPod :one
INSERT INTO published_pods (
    id,
    title,
    slug,
    description,
    image_url,
    status,
    source_folder_id,
    publisher_principal_id
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING
    id,
    title,
    slug,
    description,
    image_url,
    status,
    source_folder_id,
    publisher_principal_id,
    clone_count,
    created_at,
    updated_at
`

type CreatePublishedPodParams struct {
	ID                   uuid.UUID          `json:"id"`
	Title                string             `json:"title"`
	Slug                 string             `json:"slug"`
	Description          string             `json:"description"`
	ImageUrl             string             `json:"image_url"`
	Status               PublishedPodStatus `json:"status"`
	SourceFolderID       uuid.UUID          `json:"source_folder_id"`
	PublisherPrincipalID uuid.UUID          `json:"publisher_principal_id"`
}

func (q *Queries) CreatePublishedPod(ctx context.Context, arg CreatePublishedPodParams) (PublishedPods, error) {
	row := q.db.QueryRow(ctx, createPublishedPod,
		arg.ID,
		arg.Title,
		arg.Slug,
		arg.Description,
		arg.ImageUrl,
		arg.Status,
		arg.SourceFolderID,
		arg.PublisherPrincipalID,
	)
	var i PublishedPods
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.ImageUrl,
		&i.Status,
		&i.SourceFolderID,
		&i.PublisherPrincipalID,
		&i.CloneCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteClonedPodQuestionAnswersByQuestionID = `-- name: DeleteClonedPodQuestionAnswersByQuestionID :exec
DELETE FROM cloned_pod_question_answers
WHERE question_id = $1
`

func (q *Queries) DeleteClonedPodQuestionAnswersByQuestionID(ctx context.Context, questionID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteClonedPodQuestionAnswersByQuestionID, questionID)
	return err
}

const deleteClonedPodVMs = `-- name: DeleteClonedPodVMs :exec
DELETE FROM cloned_pod_vms
WHERE cloned_pod_id = $1
`

func (q *Queries) DeleteClonedPodVMs(ctx context.Context, clonedPodID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteClonedPodVMs, clonedPodID)
	return err
}

const deletePublishedPod = `-- name: DeletePublishedPod :execrows
DELETE FROM published_pods
WHERE id = $1
`

func (q *Queries) DeletePublishedPod(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deletePublishedPod, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deletePublishedPodAudience = `-- name: DeletePublishedPodAudience :exec
DELETE FROM published_pod_audience
WHERE pod_id = $1
`

func (q *Queries) DeletePublishedPodAudience(ctx context.Context, podID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePublishedPodAudience, podID)
	return err
}

const deletePublishedPodCreators = `-- name: DeletePublishedPodCreators :exec
DELETE FROM published_pod_creators
WHERE pod_id = $1
`

func (q *Queries) DeletePublishedPodCreators(ctx context.Context, podID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePublishedPodCreators, podID)
	return err
}

const deletePublishedPodQuestionsExcept = `-- name: DeletePublishedPodQuestionsExcept :exec
DELETE FROM published_pod_task_questions q
USING published_pod_tasks t
WHERE q.task_id = t.id
  AND t.pod_id = $1
  AND NOT (q.id = ANY($2::UUID[]))
`

type DeletePublishedPodQuestionsExceptParams struct {
	PodID   uuid.UUID   `json:"pod_id"`
	KeepIds []uuid.UUID `json:"keep_ids"`
}

func (q *Queries) DeletePublishedPodQuestionsExcept(ctx context.Context, arg DeletePublishedPodQuestionsExceptParams) error {
	_, err := q.db.Exec(ctx, deletePublishedPodQuestionsExcept, arg.PodID, arg.KeepIds)
	return err
}

const deletePublishedPodTasksExcept = `-- name: DeletePublishedPodTasksExcept :exec
DELETE FROM published_pod_tasks
WHERE pod_id = $1
  AND NOT (id = ANY($2::UUID[]))
`

type DeletePublishedPodTasksExceptParams struct {
	PodID   uuid.UUID   `json:"pod_id"`
	KeepIds []uuid.UUID `json:"keep_ids"`
}

func (q *Queries) DeletePublishedPodTasksExcept(ctx context.Context, arg DeletePublishedPodTasksExceptParams) error {
	_, err := q.db.Exec(ctx, deletePublishedPodTasksExcept, arg.PodID, arg.KeepIds)
	return err
}

const deletePublishedPodVMs = `-- name: DeletePublishedPodVMs :exec
DELETE FROM published_pod_vms
WHERE pod_id = $1
`

func (q *Queries) DeletePublishedPodVMs(ctx context.Context, podID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePublishedPodVMs, podID)
	return err
}

const deletePublishedPodVMsExcept = `-- name: DeletePublishedPodVMsExcept :exec
DELETE FROM published_pod_vms
WHERE pod_id = $1
  AND NOT (id = ANY($2::UUID[]))
`

type DeletePublishedPodVMsExceptParams struct {
	PodID   uuid.UUID   `json:"pod_id"`
	KeepIds []uuid.UUID `json:"keep_ids"`
}

func (q *Queries) DeletePublishedPodVMsExcept(ctx context.Context, arg DeletePublishedPodVMsExceptParams) error {
	_, err := q.db.Exec(ctx, deletePublishedPodVMsExcept, arg.PodID, arg.KeepIds)
	return err
}

const getAccessibleClonedPodByID = `-- name: GetAccessibleClonedPodByID :one
SELECT
    cp.id,
    cp.pod_id,
    cp.user_principal_id,
    cp.folder_id,
    cp.network_number,
    cp.created_at,
    cp.updated_at
FROM cloned_pods cp
WHERE cp.id = $1
  AND cp.user_principal_id IN (
      SELECT ep.principal_id::UUID
      FROM get_user_effective_principals($2) AS ep(principal_id)
  )
`

type GetAccessibleClonedPodByIDParams struct {
	ID          uuid.UUID `json:"id"`
	PrincipalID uuid.UUID `json:"principal_id"`
}

func (q *Queries) GetAccessibleClonedPodByID(ctx context.Context, arg GetAccessibleClonedPodByIDParams) (ClonedPods, error) {
	row := q.db.QueryRow(ctx, getAccessibleClonedPodByID, arg.ID, arg.PrincipalID)
	var i ClonedPods
	err := row.Scan(
		&i.ID,
		&i.PodID,
		&i.UserPrincipalID,
		&i.FolderID,
		&i.NetworkNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccessibleClonedPodByPodID = `-- name: GetAccessibleClonedPodByPodID :one
SELECT
    cp.id,
    cp.pod_id,
    cp.user_principal_id,
    cp.folder_id,
    cp.network_number,
    cp.created_at,
    cp.updated_at
FROM cloned_pods cp
WHERE cp.pod_id = $1
  AND cp.user_principal_id IN (
      SELECT ep.principal_id::UUID
      FROM get_user_effective_principals($2) AS ep(principal_id)
  )
ORDER BY
    CASE WHEN cp.user_principal_id = $2 THEN 0 ELSE 1 END,
    cp.created_at DESC
LIMIT 1
`

type GetAccessibleClonedPodByPodIDParams struct {
	PodID       uuid.UUID `json:"pod_id"`
	PrincipalID uuid.UUID `json:"principal_id"`
}

func (q *Queries) GetAccessibleClonedPodByPodID(ctx context.Context, arg GetAccessibleClonedPodByPodIDParams) (ClonedPods, error) {
	row := q.db.QueryRow(ctx, getAccessibleClonedPodByPodID, arg.PodID, arg.PrincipalID)
	var i ClonedPods
	err := row.Scan(
		&i.ID,
		&i.PodID,
		&i.UserPrincipalID,
		&i.FolderID,
		&i.NetworkNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getClonedPodByID = `-- name: GetClonedPodByID :one
SELECT
    id,
    pod_id,
    user_principal_id,
    folder_id,
    network_number,
    created_at,
    updated_at
FROM cloned_pods
WHERE id = $1
`

func (q *Queries) GetClonedPodByID(ctx context.Context, id uuid.UUID) (ClonedPods, error) {
	row := q.db.QueryRow(ctx, getClonedPodByID, id)
	var i ClonedPods
	err := row.Scan(
		&i.ID,
		&i.PodID,
		&i.UserPrincipalID,
		&i.FolderID,
		&i.NetworkNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getClonedPodForPrincipalByID = `-- name: GetClonedPodForPrincipalByID :one
SELECT
    id,
    pod_id,
    user_principal_id,
    folder_id,
    network_number,
    created_at,
    updated_at
FROM cloned_pods
WHERE id = $1
  AND user_principal_id = $2
`

type GetClonedPodForPrincipalByIDParams struct {
	ID              uuid.UUID `json:"id"`
	UserPrincipalID uuid.UUID `json:"user_principal_id"`
}

func (q *Queries) GetClonedPodForPrincipalByID(ctx context.Context, arg GetClonedPodForPrincipalByIDParams) (ClonedPods, error) {
	row := q.db.QueryRow(ctx, getClonedPodForPrincipalByID, arg.ID, arg.UserPrincipalID)
	var i ClonedPods
	err := row.Scan(
		&i.ID,
		&i.PodID,
		&i.UserPrincipalID,
		&i.FolderID,
		&i.NetworkNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getClonedPodForPrincipalByPodID = `-- name: GetClonedPodForPrincipalByPodID :one
SELECT
    id,
    pod_id,
    user_principal_id,
    folder_id,
    network_number,
    created_at,
    updated_at
FROM cloned_pods
WHERE pod_id = $1
  AND user_principal_id = $2
`

type GetClonedPodForPrincipalByPodIDParams struct {
	PodID           uuid.UUID `json:"pod_id"`
	UserPrincipalID uuid.UUID `json:"user_principal_id"`
}

func (q *Queries) GetClonedPodForPrincipalByPodID(ctx context.Context, arg GetClonedPodForPrincipalByPodIDParams) (ClonedPods, error) {
	row := q.db.QueryRow(ctx, getClonedPodForPrincipalByPodID, arg.PodID, arg.UserPrincipalID)
	var i ClonedPods
	err := row.Scan(
		&i.ID,
		&i.PodID,
		&i.UserPrincipalID,
		&i.FolderID,
		&i.NetworkNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPublishedPodByID = `-- name: GetPublishedPodByID :one
SELECT
    pp.id,
    pp.title,
    pp.slug,
    pp.description,
    pp.image_url,
    pp.status,
    pp.source_folder_id,
    source_folder.name AS source_folder_name,
    pp.publisher_principal_id,
    pp.clone_count,
    pp.created_at,
    pp.updated_at
FROM published_pods pp
JOIN inventory_items source_folder
  ON source_folder.id = pp.source_folder_id
WHERE pp.id = $1
`

type GetPublishedPodByIDRow struct {
	ID                   uuid.UUID          `json:"id"`
	Title                string             `json:"title"`
	Slug                 string             `json:"slug"`
	Description          string             `json:"description"`
	ImageUrl             string             `json:"image_url"`
	Status               PublishedPodStatus `json:"status"`
	SourceFolderID       uuid.UUID          `json:"source_folder_id"`
	SourceFolderName     string             `json:"source_folder_name"`
	PublisherPrincipalID uuid.UUID          `json:"publisher_principal_id"`
	CloneCount           int32              `json:"clone_count"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetPublishedPodByID(ctx context.Context, id uuid.UUID) (GetPublishedPodByIDRow, error) {
	row := q.db.QueryRow(ctx, getPublishedPodByID, id)
	var i GetPublishedPodByIDRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.ImageUrl,
		&i.Status,
		&i.SourceFolderID,
		&i.SourceFolderName,
		&i.PublisherPrincipalID,
		&i.CloneCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPublishedPodSlugConflict = `-- name: GetPublishedPodSlugConflict :one
SELECT id
FROM published_pods
WHERE slug = $1
  AND id <> $2
LIMIT 1
`

type GetPublishedPodSlugConflictParams struct {
	Slug string    `json:"slug"`
	ID   uuid.UUID `json:"id"`
}

func (q *Queries) GetPublishedPodSlugConflict(ctx context.Context, arg GetPublishedPodSlugConflictParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getPublishedPodSlugConflict, arg.Slug, arg.ID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getQuestionForClonedPod = `-- name: GetQuestionForClonedPod :one
SELECT
    q.id,
    q.task_id,
    q.title,
    q.answer_outline,
    t.pod_id,
    t.title AS task_title,
    p.slug AS pod_slug,
    p.title AS pod_title
FROM published_pod_task_questions q
JOIN published_pod_tasks t
  ON t.id = q.task_id
JOIN published_pods p
  ON p.id = t.pod_id
JOIN cloned_pods cp
  ON cp.pod_id = t.pod_id
WHERE cp.id = $1
  AND q.id = $2
`

type GetQuestionForClonedPodParams struct {
	ClonedPodID uuid.UUID `json:"cloned_pod_id"`
	QuestionID  uuid.UUID `json:"question_id"`
}

type GetQuestionForClonedPodRow struct {
	ID            uuid.UUID `json:"id"`
	TaskID        uuid.UUID `json:"task_id"`
	Title         string    `json:"title"`
	AnswerOutline string    `json:"answer_outline"`
	PodID         uuid.UUID `json:"pod_id"`
	TaskTitle     string    `json:"task_title"`
	PodSlug       string    `json:"pod_slug"`
	PodTitle      string    `json:"pod_title"`
}

func (q *Queries) GetQuestionForClonedPod(ctx context.Context, arg GetQuestionForClonedPodParams) (GetQuestionForClonedPodRow, error) {
	row := q.db.QueryRow(ctx, getQuestionForClonedPod, arg.ClonedPodID, arg.QuestionID)
	var i GetQuestionForClonedPodRow
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Title,
		&i.AnswerOutline,
		&i.PodID,
		&i.TaskTitle,
		&i.PodSlug,
		&i.PodTitle,
	)
	return i, err
}

const getVisiblePublishedPodBySlug = `-- name: GetVisiblePublishedPodBySlug :one
SELECT
    pp.id,
    pp.title,
    pp.slug,
    pp.description,
    pp.image_url,
    pp.status,
    pp.source_folder_id,
    source_folder.name AS source_folder_name,
    pp.publisher_principal_id,
    pp.clone_count,
    pp.created_at,
    pp.updated_at
FROM published_pods pp
JOIN inventory_items source_folder
  ON source_folder.id = pp.source_folder_id
WHERE pp.slug = $1
  AND pp.status = 'listed'
  AND (
      NOT EXISTS (
          SELECT 1
          FROM published_pod_audience audience
          WHERE audience.pod_id = pp.id
      )
      OR EXISTS (
          SELECT 1
          FROM published_pod_audience audience
          WHERE audience.pod_id = pp.id
            AND audience.principal_id IN (
                SELECT ep.principal_id::UUID
                FROM get_user_effective_principals($2) AS ep(principal_id)
            )
      )
  )
`

type GetVisiblePublishedPodBySlugParams struct {
	Slug        string    `json:"slug"`
	PrincipalID uuid.UUID `json:"principal_id"`
}

type GetVisiblePublishedPodBySlugRow struct {
	ID                   uuid.UUID          `json:"id"`
	Title                string             `json:"title"`
	Slug                 string             `json:"slug"`
	Description          string             `json:"description"`
	ImageUrl             string             `json:"image_url"`
	Status               PublishedPodStatus `json:"status"`
	SourceFolderID       uuid.UUID          `json:"source_folder_id"`
	SourceFolderName     string             `json:"source_folder_name"`
	PublisherPrincipalID uuid.UUID          `json:"publisher_principal_id"`
	CloneCount           int32              `json:"clone_count"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetVisiblePublishedPodBySlug(ctx context.Context, arg GetVisiblePublishedPodBySlugParams) (GetVisiblePublishedPodBySlugRow, error) {
	row := q.db.QueryRow(ctx, getVisiblePublishedPodBySlug, arg.Slug, arg.PrincipalID)
	var i GetVisiblePublishedPodBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.ImageUrl,
		&i.Status,
		&i.SourceFolderID,
		&i.SourceFolderName,
		&i.PublisherPrincipalID,
		&i.CloneCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertClonedPod = `-- name: InsertClonedPod :one
WITH allocation_lock AS (
    SELECT pg_advisory_xact_lock(740020001)
),
candidate AS (
    SELECT n::INTEGER AS network_number
    FROM allocation_lock,
         generate_series($5::INTEGER, $6::INTEGER) AS n
    WHERE NOT EXISTS (
        SELECT 1
        FROM cloned_pods cp
        WHERE cp.network_number = n
    )
    ORDER BY n
    LIMIT 1
)
INSERT INTO cloned_pods (
    id,
    pod_id,
    user_principal_id,
    folder_id,
    network_number
)
SELECT
    $1,
    $2,
    $3,
    $4,
    candidate.network_number
FROM candidate
RETURNING
    id,
    pod_id,
    user_principal_id,
    folder_id,
    network_number,
    created_at,
    updated_at
`

type InsertClonedPodParams struct {
	ID               uuid.UUID `json:"id"`
	PodID            uuid.UUID `json:"pod_id"`
	UserPrincipalID  uuid.UUID `json:"user_principal_id"`
	FolderID         uuid.UUID `json:"folder_id"`
	MinNetworkNumber int32     `json:"min_network_number"`
	MaxNetworkNumber int32     `json:"max_network_number"`
}

func (q *Queries) InsertClonedPod(ctx context.Context, arg InsertClonedPodParams) (ClonedPods, error) {
	row := q.db.QueryRow(ctx, insertClonedPod,
		arg.ID,
		arg.PodID,
		arg.UserPrincipalID,
		arg.FolderID,
		arg.MinNetworkNumber,
		arg.MaxNetworkNumber,
	)
	var i ClonedPods
	err := row.Scan(
		&i.ID,
		&i.PodID,
		&i.UserPrincipalID,
		&i.FolderID,
		&i.NetworkNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertClonedPodTaskState = `-- name: InsertClonedPodTaskState :exec
INSERT INTO cloned_pod_task_states (
    cloned_pod_id,
    task_id,
    completed,
    completed_at
) VALUES (
    $1,
    $2,
    $3,
    CASE WHEN $3 THEN now() ELSE NULL END
)
ON CONFLICT (cloned_pod_id, task_id) DO NOTHING
`

type InsertClonedPodTaskStateParams struct {
	ClonedPodID uuid.UUID `json:"cloned_pod_id"`
	TaskID      uuid.UUID `json:"task_id"`
	Completed   bool      `json:"completed"`
}

func (q *Queries) InsertClonedPodTaskState(ctx context.Context, arg InsertClonedPodTaskStateParams) error {
	_, err := q.db.Exec(ctx, insertClonedPodTaskState, arg.ClonedPodID, arg.TaskID, arg.Completed)
	return err
}

const insertClonedPodVM = `-- name: InsertClonedPodVM :exec
INSERT INTO cloned_pod_vms (
    cloned_pod_id,
    published_pod_vm_id,
    inventory_item_id,
    sort_order
) VALUES ($1, $2, $3, $4)
`

type InsertClonedPodVMParams struct {
	ClonedPodID      uuid.UUID `json:"cloned_pod_id"`
	PublishedPodVmID uuid.UUID `json:"published_pod_vm_id"`
	InventoryItemID  uuid.UUID `json:"inventory_item_id"`
	SortOrder        int32     `json:"sort_order"`
}

func (q *Queries) InsertClonedPodVM(ctx context.Context, arg InsertClonedPodVMParams) error {
	_, err := q.db.Exec(ctx, insertClonedPodVM,
		arg.ClonedPodID,
		arg.PublishedPodVmID,
		arg.InventoryItemID,
		arg.SortOrder,
	)
	return err
}

const insertPodDevNetworkAllocation = `-- name: InsertPodDevNetworkAllocation :one
WITH allocation_lock AS (
    SELECT pg_advisory_xact_lock(740020002)
),
candidate AS (
    SELECT n::INTEGER AS network_number
    FROM allocation_lock,
         generate_series($2::INTEGER, $3::INTEGER) AS n
    WHERE NOT EXISTS (
        SELECT 1
        FROM cloned_pods cp
        WHERE cp.network_number = n
    )
      AND NOT EXISTS (
        SELECT 1
        FROM pod_dev_network_allocations pdna
        WHERE pdna.network_number = n
    )
    ORDER BY n
    LIMIT 1
)
INSERT INTO pod_dev_network_allocations (
    pod_folder_id,
    network_number
)
SELECT
    $1,
    candidate.network_number
FROM candidate
RETURNING
    pod_folder_id,
    network_number,
    created_at,
    updated_at
`

type InsertPodDevNetworkAllocationParams struct {
	PodFolderID      uuid.UUID `json:"pod_folder_id"`
	MinNetworkNumber int32     `json:"min_network_number"`
	MaxNetworkNumber int32     `json:"max_network_number"`
}

func (q *Queries) InsertPodDevNetworkAllocation(ctx context.Context, arg InsertPodDevNetworkAllocationParams) (PodDevNetworkAllocations, error) {
	row := q.db.QueryRow(ctx, insertPodDevNetworkAllocation, arg.PodFolderID, arg.MinNetworkNumber, arg.MaxNetworkNumber)
	var i PodDevNetworkAllocations
	err := row.Scan(
		&i.PodFolderID,
		&i.NetworkNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertPublishedPodAudience = `-- name: InsertPublishedPodAudience :exec
INSERT INTO published_pod_audience (pod_id, principal_id, sort_order)
VALUES ($1, $2, $3)
`

type InsertPublishedPodAudienceParams struct {
	PodID       uuid.UUID `json:"pod_id"`
	PrincipalID uuid.UUID `json:"principal_id"`
	SortOrder   int32     `json:"sort_order"`
}

func (q *Queries) InsertPublishedPodAudience(ctx context.Context, arg InsertPublishedPodAudienceParams) error {
	_, err := q.db.Exec(ctx, insertPublishedPodAudience, arg.PodID, arg.PrincipalID, arg.SortOrder)
	return err
}

const insertPublishedPodCreator = `-- name: InsertPublishedPodCreator :exec
INSERT INTO published_pod_creators (pod_id, principal_id, sort_order)
VALUES ($1, $2, $3)
`

type InsertPublishedPodCreatorParams struct {
	PodID       uuid.UUID `json:"pod_id"`
	PrincipalID uuid.UUID `json:"principal_id"`
	SortOrder   int32     `json:"sort_order"`
}

func (q *Queries) InsertPublishedPodCreator(ctx context.Context, arg InsertPublishedPodCreatorParams) error {
	_, err := q.db.Exec(ctx, insertPublishedPodCreator, arg.PodID, arg.PrincipalID, arg.SortOrder)
	return err
}

const insertPublishedPodTask = `-- name: InsertPublishedPodTask :one
INSERT INTO published_pod_tasks (id, pod_id, title, content, sort_order)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type InsertPublishedPodTaskParams struct {
	ID        uuid.UUID `json:"id"`
	PodID     uuid.UUID `json:"pod_id"`
	Title     string    `json:"title"`
	Content   string    `json:"content"`
	SortOrder int32     `json:"sort_order"`
}

func (q *Queries) InsertPublishedPodTask(ctx context.Context, arg InsertPublishedPodTaskParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertPublishedPodTask,
		arg.ID,
		arg.PodID,
		arg.Title,
		arg.Content,
		arg.SortOrder,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertPublishedPodTaskQuestion = `-- name: InsertPublishedPodTaskQuestion :exec
INSERT INTO published_pod_task_questions (
    id,
    task_id,
    title,
    answer_outline,
    description,
    hint,
    sort_order
) VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertPublishedPodTaskQuestionParams struct {
	ID            uuid.UUID `json:"id"`
	TaskID        uuid.UUID `json:"task_id"`
	Title         string    `json:"title"`
	AnswerOutline string    `json:"answer_outline"`
	Description   *string   `json:"description"`
	Hint          *string   `json:"hint"`
	SortOrder     int32     `json:"sort_order"`
}

func (q *Queries) InsertPublishedPodTaskQuestion(ctx context.Context, arg InsertPublishedPodTaskQuestionParams) error {
	_, err := q.db.Exec(ctx, insertPublishedPodTaskQuestion,
		arg.ID,
		arg.TaskID,
		arg.Title,
		arg.AnswerOutline,
		arg.Description,
		arg.Hint,
		arg.SortOrder,
	)
	return err
}

const insertPublishedPodVM = `-- name: InsertPublishedPodVM :exec
INSERT INTO published_pod_vms (
    id,
    pod_id,
    source_inventory_item_id,
    name,
    cpu_count,
    memory_mb,
    disk_gb,
    allow_mask,
    deny_mask,
    sort_order
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type InsertPublishedPodVMParams struct {
	ID                    uuid.UUID `json:"id"`
	PodID                 uuid.UUID `json:"pod_id"`
	SourceInventoryItemID uuid.UUID `json:"source_inventory_item_id"`
	Name                  string    `json:"name"`
	CpuCount              int32     `json:"cpu_count"`
	MemoryMb              int32     `json:"memory_mb"`
	DiskGb                float64   `json:"disk_gb"`
	AllowMask             int64     `json:"allow_mask"`
	DenyMask              int64     `json:"deny_mask"`
	SortOrder             int32     `json:"sort_order"`
}

func (q *Queries) InsertPublishedPodVM(ctx context.Context, arg InsertPublishedPodVMParams) error {
	_, err := q.db.Exec(ctx, insertPublishedPodVM,
		arg.ID,
		arg.PodID,
		arg.SourceInventoryItemID,
		arg.Name,
		arg.CpuCount,
		arg.MemoryMb,
		arg.DiskGb,
		arg.AllowMask,
		arg.DenyMask,
		arg.SortOrder,
	)
	return err
}

const listAccessibleClonedPodSummariesByPodIDs = `-- name: ListAccessibleClonedPodSummariesByPodIDs :many
SELECT DISTINCT ON (cp.pod_id)
    cp.id,
    cp.pod_id,
    cp.user_principal_id,
    cp.created_at,
    COUNT(DISTINCT task.id)::int AS task_total,
    COUNT(DISTINCT state.task_id) FILTER (WHERE state.completed)::int AS task_completed
FROM cloned_pods cp
LEFT JOIN published_pod_tasks task
  ON task.pod_id = cp.pod_id
LEFT JOIN cloned_pod_task_states state
  ON state.cloned_pod_id = cp.id
 AND state.task_id = task.id
WHERE cp.pod_id = ANY($1::UUID[])
  AND cp.user_principal_id IN (
      SELECT ep.principal_id::UUID
      FROM get_user_effective_principals($2) AS ep(principal_id)
  )
GROUP BY
    cp.id,
    cp.pod_id,
    cp.user_principal_id,
    cp.created_at
ORDER BY
    cp.pod_id,
    CASE WHEN cp.user_principal_id = $2 THEN 0 ELSE 1 END,
    cp.created_at DESC
`

type ListAccessibleClonedPodSummariesByPodIDsParams struct {
	Column1     []uuid.UUID `json:"column_1"`
	PrincipalID uuid.UUID   `json:"principal_id"`
}

type ListAccessibleClonedPodSummariesByPodIDsRow struct {
	ID              uuid.UUID          `json:"id"`
	PodID           uuid.UUID          `json:"pod_id"`
	UserPrincipalID uuid.UUID          `json:"user_principal_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	TaskTotal       int32              `json:"task_total"`
	TaskCompleted   int32              `json:"task_completed"`
}

func (q *Queries) ListAccessibleClonedPodSummariesByPodIDs(ctx context.Context, arg ListAccessibleClonedPodSummariesByPodIDsParams) ([]ListAccessibleClonedPodSummariesByPodIDsRow, error) {
	rows, err := q.db.Query(ctx, listAccessibleClonedPodSummariesByPodIDs, arg.Column1, arg.PrincipalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAccessibleClonedPodSummariesByPodIDsRow
	for rows.Next() {
		var i ListAccessibleClonedPodSummariesByPodIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.PodID,
			&i.UserPrincipalID,
			&i.CreatedAt,
			&i.TaskTotal,
			&i.TaskCompleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClonedPodQuestionAnswers = `-- name: ListClonedPodQuestionAnswers :many
SELECT
    question_id,
    answer,
    is_correct,
    answered_at
FROM cloned_pod_question_answers
WHERE cloned_pod_id = $1
ORDER BY answered_at ASC
`

type ListClonedPodQuestionAnswersRow struct {
	QuestionID uuid.UUID          `json:"question_id"`
	Answer     string             `json:"answer"`
	IsCorrect  bool               `json:"is_correct"`
	AnsweredAt pgtype.Timestamptz `json:"answered_at"`
}

func (q *Queries) ListClonedPodQuestionAnswers(ctx context.Context, clonedPodID uuid.UUID) ([]ListClonedPodQuestionAnswersRow, error) {
	rows, err := q.db.Query(ctx, listClonedPodQuestionAnswers, clonedPodID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListClonedPodQuestionAnswersRow
	for rows.Next() {
		var i ListClonedPodQuestionAnswersRow
		if err := rows.Scan(
			&i.QuestionID,
			&i.Answer,
			&i.IsCorrect,
			&i.AnsweredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClonedPodRuntimeVMsByCloneIDs = `-- name: ListClonedPodRuntimeVMsByCloneIDs :many
SELECT
    cpv.cloned_pod_id,
    cpv.inventory_item_id,
    ii.name,
    pv.node,
    pv.vmid,
    cpv.sort_order
FROM cloned_pod_vms cpv
JOIN inventory_items ii
  ON ii.id = cpv.inventory_item_id
LEFT JOIN proxmox_vms pv
  ON pv.inventory_item_id = cpv.inventory_item_id
WHERE cpv.cloned_pod_id = ANY($1::UUID[])
ORDER BY cpv.cloned_pod_id, cpv.sort_order ASC
`

type ListClonedPodRuntimeVMsByCloneIDsRow struct {
	ClonedPodID     uuid.UUID `json:"cloned_pod_id"`
	InventoryItemID uuid.UUID `json:"inventory_item_id"`
	Name            string    `json:"name"`
	Node            *string   `json:"node"`
	Vmid            *int32    `json:"vmid"`
	SortOrder       int32     `json:"sort_order"`
}

func (q *Queries) ListClonedPodRuntimeVMsByCloneIDs(ctx context.Context, cloneIds []uuid.UUID) ([]ListClonedPodRuntimeVMsByCloneIDsRow, error) {
	rows, err := q.db.Query(ctx, listClonedPodRuntimeVMsByCloneIDs, cloneIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListClonedPodRuntimeVMsByCloneIDsRow
	for rows.Next() {
		var i ListClonedPodRuntimeVMsByCloneIDsRow
		if err := rows.Scan(
			&i.ClonedPodID,
			&i.InventoryItemID,
			&i.Name,
			&i.Node,
			&i.Vmid,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClonedPodSummariesByPodID = `-- name: ListClonedPodSummariesByPodID :many
SELECT
    cp.id,
    cp.pod_id,
    cp.user_principal_id,
    p.principal_type,
    (
    CASE
        WHEN p.full_name IS NULL OR lower(trim(p.full_name)) = lower(COALESCE(NULLIF(trim(p.name), ''), p.external_id))
            THEN COALESCE(NULLIF(trim(p.name), ''), p.external_id)
        ELSE COALESCE(NULLIF(trim(p.name), ''), p.external_id) || ' (' || trim(p.full_name) || ')'
    END
    )::TEXT AS user_label,
    COALESCE(p.description, '') AS user_description,
    cp.folder_id,
    cp.network_number,
    cp.created_at,
    cp.updated_at,
    COUNT(DISTINCT cpv.inventory_item_id)::int AS vm_count,
    COUNT(DISTINCT task.id)::int AS task_total,
    COUNT(DISTINCT state.task_id) FILTER (WHERE state.completed)::int AS task_completed
FROM cloned_pods cp
JOIN principals p
  ON p.id = cp.user_principal_id
LEFT JOIN cloned_pod_vms cpv
  ON cpv.cloned_pod_id = cp.id
LEFT JOIN published_pod_tasks task
  ON task.pod_id = cp.pod_id
LEFT JOIN cloned_pod_task_states state
  ON state.cloned_pod_id = cp.id
 AND state.task_id = task.id
WHERE cp.pod_id = $1
GROUP BY
    cp.id,
    cp.pod_id,
    cp.user_principal_id,
    p.principal_type,
    p.name,
    p.full_name,
    p.external_id,
    p.description,
    cp.folder_id,
    cp.network_number,
    cp.created_at,
    cp.updated_at
ORDER BY cp.created_at DESC
`

type ListClonedPodSummariesByPodIDRow struct {
	ID              uuid.UUID          `json:"id"`
	PodID           uuid.UUID          `json:"pod_id"`
	UserPrincipalID uuid.UUID          `json:"user_principal_id"`
	PrincipalType   PrincipalType      `json:"principal_type"`
	UserLabel       string             `json:"user_label"`
	UserDescription string             `json:"user_description"`
	FolderID        uuid.UUID          `json:"folder_id"`
	NetworkNumber   int32              `json:"network_number"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	VmCount         int32              `json:"vm_count"`
	TaskTotal       int32              `json:"task_total"`
	TaskCompleted   int32              `json:"task_completed"`
}

func (q *Queries) ListClonedPodSummariesByPodID(ctx context.Context, podID uuid.UUID) ([]ListClonedPodSummariesByPodIDRow, error) {
	rows, err := q.db.Query(ctx, listClonedPodSummariesByPodID, podID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListClonedPodSummariesByPodIDRow
	for rows.Next() {
		var i ListClonedPodSummariesByPodIDRow
		if err := rows.Scan(
			&i.ID,
			&i.PodID,
			&i.UserPrincipalID,
			&i.PrincipalType,
			&i.UserLabel,
			&i.UserDescription,
			&i.FolderID,
			&i.NetworkNumber,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.VmCount,
			&i.TaskTotal,
			&i.TaskCompleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClonedPodTaskStates = `-- name: ListClonedPodTaskStates :many
SELECT
    state.task_id,
    state.completed,
    state.completed_at
FROM cloned_pod_task_states state
JOIN published_pod_tasks task
  ON task.id = state.task_id
WHERE state.cloned_pod_id = $1
ORDER BY task.sort_order ASC
`

type ListClonedPodTaskStatesRow struct {
	TaskID      uuid.UUID          `json:"task_id"`
	Completed   bool               `json:"completed"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) ListClonedPodTaskStates(ctx context.Context, clonedPodID uuid.UUID) ([]ListClonedPodTaskStatesRow, error) {
	rows, err := q.db.Query(ctx, listClonedPodTaskStates, clonedPodID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListClonedPodTaskStatesRow
	for rows.Next() {
		var i ListClonedPodTaskStatesRow
		if err := rows.Scan(&i.TaskID, &i.Completed, &i.CompletedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClonedPodVMs = `-- name: ListClonedPodVMs :many
SELECT
    cpv.cloned_pod_id,
    cpv.inventory_item_id,
    ii.name,
    pv.node,
    pv.vmid,
    cpv.sort_order
FROM cloned_pod_vms cpv
JOIN inventory_items ii
  ON ii.id = cpv.inventory_item_id
LEFT JOIN proxmox_vms pv
  ON pv.inventory_item_id = cpv.inventory_item_id
WHERE cpv.cloned_pod_id = $1
ORDER BY cpv.sort_order ASC
`

type ListClonedPodVMsRow struct {
	ClonedPodID     uuid.UUID `json:"cloned_pod_id"`
	InventoryItemID uuid.UUID `json:"inventory_item_id"`
	Name            string    `json:"name"`
	Node            *string   `json:"node"`
	Vmid            *int32    `json:"vmid"`
	SortOrder       int32     `json:"sort_order"`
}

func (q *Queries) ListClonedPodVMs(ctx context.Context, clonedPodID uuid.UUID) ([]ListClonedPodVMsRow, error) {
	rows, err := q.db.Query(ctx, listClonedPodVMs, clonedPodID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListClonedPodVMsRow
	for rows.Next() {
		var i ListClonedPodVMsRow
		if err := rows.Scan(
			&i.ClonedPodID,
			&i.InventoryItemID,
			&i.Name,
			&i.Node,
			&i.Vmid,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClonedPodsByPodID = `-- name: ListClonedPodsByPodID :many
SELECT
    id,
    pod_id,
    user_principal_id,
    folder_id,
    network_number,
    created_at,
    updated_at
FROM cloned_pods
WHERE pod_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListClonedPodsByPodID(ctx context.Context, podID uuid.UUID) ([]ClonedPods, error) {
	rows, err := q.db.Query(ctx, listClonedPodsByPodID, podID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClonedPods
	for rows.Next() {
		var i ClonedPods
		if err := rows.Scan(
			&i.ID,
			&i.PodID,
			&i.UserPrincipalID,
			&i.FolderID,
			&i.NetworkNumber,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrincipalCorrectPodQuestionAnswers = `-- name: ListPrincipalCorrectPodQuestionAnswers :many
SELECT
    source_pod_id,
    source_question_id,
    answered_at
FROM principal_pod_question_answers
WHERE principal_id = $1
  AND is_correct = true
ORDER BY answered_at ASC, source_pod_id ASC, source_question_id ASC
`

type ListPrincipalCorrectPodQuestionAnswersRow struct {
	SourcePodID      uuid.UUID          `json:"source_pod_id"`
	SourceQuestionID uuid.UUID          `json:"source_question_id"`
	AnsweredAt       pgtype.Timestamptz `json:"answered_at"`
}

func (q *Queries) ListPrincipalCorrectPodQuestionAnswers(ctx context.Context, principalID uuid.UUID) ([]ListPrincipalCorrectPodQuestionAnswersRow, error) {
	rows, err := q.db.Query(ctx, listPrincipalCorrectPodQuestionAnswers, principalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPrincipalCorrectPodQuestionAnswersRow
	for rows.Next() {
		var i ListPrincipalCorrectPodQuestionAnswersRow
		if err := rows.Scan(&i.SourcePodID, &i.SourceQuestionID, &i.AnsweredAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedPodAudienceByPodIDs = `-- name: ListPublishedPodAudienceByPodIDs :many
SELECT
    audience.pod_id,
    p.id,
    p.principal_type,
    p.external_id,
    p.name,
    p.full_name,
    p.description,
    audience.sort_order
FROM published_pod_audience audience
JOIN principals p
  ON p.id = audience.principal_id
WHERE audience.pod_id = ANY($1::UUID[])
ORDER BY audience.pod_id, audience.sort_order ASC
`

type ListPublishedPodAudienceByPodIDsRow struct {
	PodID         uuid.UUID     `json:"pod_id"`
	ID            uuid.UUID     `json:"id"`
	PrincipalType PrincipalType `json:"principal_type"`
	ExternalID    string        `json:"external_id"`
	Name          *string       `json:"name"`
	FullName      *string       `json:"full_name"`
	Description   *string       `json:"description"`
	SortOrder     int32         `json:"sort_order"`
}

func (q *Queries) ListPublishedPodAudienceByPodIDs(ctx context.Context, podIds []uuid.UUID) ([]ListPublishedPodAudienceByPodIDsRow, error) {
	rows, err := q.db.Query(ctx, listPublishedPodAudienceByPodIDs, podIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublishedPodAudienceByPodIDsRow
	for rows.Next() {
		var i ListPublishedPodAudienceByPodIDsRow
		if err := rows.Scan(
			&i.PodID,
			&i.ID,
			&i.PrincipalType,
			&i.ExternalID,
			&i.Name,
			&i.FullName,
			&i.Description,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedPodCreatorsByPodIDs = `-- name: ListPublishedPodCreatorsByPodIDs :many
SELECT
    creator.pod_id,
    p.id,
    p.principal_type,
    p.external_id,
    p.name,
    p.full_name,
    p.description,
    creator.sort_order
FROM published_pod_creators creator
JOIN principals p
  ON p.id = creator.principal_id
WHERE creator.pod_id = ANY($1::UUID[])
ORDER BY creator.pod_id, creator.sort_order ASC
`

type ListPublishedPodCreatorsByPodIDsRow struct {
	PodID         uuid.UUID     `json:"pod_id"`
	ID            uuid.UUID     `json:"id"`
	PrincipalType PrincipalType `json:"principal_type"`
	ExternalID    string        `json:"external_id"`
	Name          *string       `json:"name"`
	FullName      *string       `json:"full_name"`
	Description   *string       `json:"description"`
	SortOrder     int32         `json:"sort_order"`
}

func (q *Queries) ListPublishedPodCreatorsByPodIDs(ctx context.Context, podIds []uuid.UUID) ([]ListPublishedPodCreatorsByPodIDsRow, error) {
	rows, err := q.db.Query(ctx, listPublishedPodCreatorsByPodIDs, podIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublishedPodCreatorsByPodIDsRow
	for rows.Next() {
		var i ListPublishedPodCreatorsByPodIDsRow
		if err := rows.Scan(
			&i.PodID,
			&i.ID,
			&i.PrincipalType,
			&i.ExternalID,
			&i.Name,
			&i.FullName,
			&i.Description,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedPodQuestionsByTaskIDs = `-- name: ListPublishedPodQuestionsByTaskIDs :many
SELECT
    id,
    task_id,
    title,
    answer_outline,
    description,
    hint,
    sort_order
FROM published_pod_task_questions
WHERE task_id = ANY($1::UUID[])
ORDER BY task_id, sort_order ASC
`

type ListPublishedPodQuestionsByTaskIDsRow struct {
	ID            uuid.UUID `json:"id"`
	TaskID        uuid.UUID `json:"task_id"`
	Title         string    `json:"title"`
	AnswerOutline string    `json:"answer_outline"`
	Description   *string   `json:"description"`
	Hint          *string   `json:"hint"`
	SortOrder     int32     `json:"sort_order"`
}

func (q *Queries) ListPublishedPodQuestionsByTaskIDs(ctx context.Context, taskIds []uuid.UUID) ([]ListPublishedPodQuestionsByTaskIDsRow, error) {
	rows, err := q.db.Query(ctx, listPublishedPodQuestionsByTaskIDs, taskIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublishedPodQuestionsByTaskIDsRow
	for rows.Next() {
		var i ListPublishedPodQuestionsByTaskIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.Title,
			&i.AnswerOutline,
			&i.Description,
			&i.Hint,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedPodTasksByPodIDs = `-- name: ListPublishedPodTasksByPodIDs :many
SELECT
    id,
    pod_id,
    title,
    content,
    sort_order
FROM published_pod_tasks
WHERE pod_id = ANY($1::UUID[])
ORDER BY pod_id, sort_order ASC
`

type ListPublishedPodTasksByPodIDsRow struct {
	ID        uuid.UUID `json:"id"`
	PodID     uuid.UUID `json:"pod_id"`
	Title     string    `json:"title"`
	Content   string    `json:"content"`
	SortOrder int32     `json:"sort_order"`
}

func (q *Queries) ListPublishedPodTasksByPodIDs(ctx context.Context, podIds []uuid.UUID) ([]ListPublishedPodTasksByPodIDsRow, error) {
	rows, err := q.db.Query(ctx, listPublishedPodTasksByPodIDs, podIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublishedPodTasksByPodIDsRow
	for rows.Next() {
		var i ListPublishedPodTasksByPodIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.PodID,
			&i.Title,
			&i.Content,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedPodVMsByPodIDs = `-- name: ListPublishedPodVMsByPodIDs :many
SELECT
    id,
    pod_id,
    source_inventory_item_id,
    name,
    cpu_count,
    memory_mb,
    disk_gb,
    allow_mask,
    deny_mask,
    sort_order
FROM published_pod_vms
WHERE pod_id = ANY($1::UUID[])
ORDER BY pod_id, sort_order ASC
`

type ListPublishedPodVMsByPodIDsRow struct {
	ID                    uuid.UUID `json:"id"`
	PodID                 uuid.UUID `json:"pod_id"`
	SourceInventoryItemID uuid.UUID `json:"source_inventory_item_id"`
	Name                  string    `json:"name"`
	CpuCount              int32     `json:"cpu_count"`
	MemoryMb              int32     `json:"memory_mb"`
	DiskGb                float64   `json:"disk_gb"`
	AllowMask             int64     `json:"allow_mask"`
	DenyMask              int64     `json:"deny_mask"`
	SortOrder             int32     `json:"sort_order"`
}

func (q *Queries) ListPublishedPodVMsByPodIDs(ctx context.Context, podIds []uuid.UUID) ([]ListPublishedPodVMsByPodIDsRow, error) {
	rows, err := q.db.Query(ctx, listPublishedPodVMsByPodIDs, podIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublishedPodVMsByPodIDsRow
	for rows.Next() {
		var i ListPublishedPodVMsByPodIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.PodID,
			&i.SourceInventoryItemID,
			&i.Name,
			&i.CpuCount,
			&i.MemoryMb,
			&i.DiskGb,
			&i.AllowMask,
			&i.DenyMask,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedPodVMsForClone = `-- name: ListPublishedPodVMsForClone :many
SELECT
    id,
    pod_id,
    source_inventory_item_id,
    name,
    cpu_count,
    memory_mb,
    disk_gb,
    allow_mask,
    deny_mask,
    sort_order
FROM published_pod_vms
WHERE pod_id = $1
ORDER BY sort_order ASC
`

type ListPublishedPodVMsForCloneRow struct {
	ID                    uuid.UUID `json:"id"`
	PodID                 uuid.UUID `json:"pod_id"`
	SourceInventoryItemID uuid.UUID `json:"source_inventory_item_id"`
	Name                  string    `json:"name"`
	CpuCount              int32     `json:"cpu_count"`
	MemoryMb              int32     `json:"memory_mb"`
	DiskGb                float64   `json:"disk_gb"`
	AllowMask             int64     `json:"allow_mask"`
	DenyMask              int64     `json:"deny_mask"`
	SortOrder             int32     `json:"sort_order"`
}

func (q *Queries) ListPublishedPodVMsForClone(ctx context.Context, podID uuid.UUID) ([]ListPublishedPodVMsForCloneRow, error) {
	rows, err := q.db.Query(ctx, listPublishedPodVMsForClone, podID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublishedPodVMsForCloneRow
	for rows.Next() {
		var i ListPublishedPodVMsForCloneRow
		if err := rows.Scan(
			&i.ID,
			&i.PodID,
			&i.SourceInventoryItemID,
			&i.Name,
			&i.CpuCount,
			&i.MemoryMb,
			&i.DiskGb,
			&i.AllowMask,
			&i.DenyMask,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedPods = `-- name: ListPublishedPods :many
SELECT
    pp.id,
    pp.title,
    pp.slug,
    pp.description,
    pp.image_url,
    pp.status,
    pp.source_folder_id,
    source_folder.name AS source_folder_name,
    pp.publisher_principal_id,
    pp.clone_count,
    pp.created_at,
    pp.updated_at
FROM published_pods pp
JOIN inventory_items source_folder
  ON source_folder.id = pp.source_folder_id
ORDER BY pp.created_at DESC, lower(pp.title) ASC, pp.title ASC
`

type ListPublishedPodsRow struct {
	ID                   uuid.UUID          `json:"id"`
	Title                string             `json:"title"`
	Slug                 string             `json:"slug"`
	Description          string             `json:"description"`
	ImageUrl             string             `json:"image_url"`
	Status               PublishedPodStatus `json:"status"`
	SourceFolderID       uuid.UUID          `json:"source_folder_id"`
	SourceFolderName     string             `json:"source_folder_name"`
	PublisherPrincipalID uuid.UUID          `json:"publisher_principal_id"`
	CloneCount           int32              `json:"clone_count"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListPublishedPods(ctx context.Context) ([]ListPublishedPodsRow, error) {
	rows, err := q.db.Query(ctx, listPublishedPods)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublishedPodsRow
	for rows.Next() {
		var i ListPublishedPodsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.ImageUrl,
			&i.Status,
			&i.SourceFolderID,
			&i.SourceFolderName,
			&i.PublisherPrincipalID,
			&i.CloneCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVisiblePublishedPodsForPrincipal = `-- name: ListVisiblePublishedPodsForPrincipal :many
SELECT
    pp.id,
    pp.title,
    pp.slug,
    pp.description,
    pp.image_url,
    pp.status,
    pp.source_folder_id,
    source_folder.name AS source_folder_name,
    pp.publisher_principal_id,
    pp.clone_count,
    pp.created_at,
    pp.updated_at
FROM published_pods pp
JOIN inventory_items source_folder
  ON source_folder.id = pp.source_folder_id
WHERE pp.status = 'listed'
  AND (
      NOT EXISTS (
          SELECT 1
          FROM published_pod_audience audience
          WHERE audience.pod_id = pp.id
      )
      OR EXISTS (
          SELECT 1
          FROM published_pod_audience audience
          WHERE audience.pod_id = pp.id
            AND audience.principal_id IN (
                SELECT ep.principal_id::UUID
                FROM get_user_effective_principals($1) AS ep(principal_id)
            )
      )
  )
ORDER BY pp.created_at DESC, lower(pp.title) ASC, pp.title ASC
`

type ListVisiblePublishedPodsForPrincipalRow struct {
	ID                   uuid.UUID          `json:"id"`
	Title                string             `json:"title"`
	Slug                 string             `json:"slug"`
	Description          string             `json:"description"`
	ImageUrl             string             `json:"image_url"`
	Status               PublishedPodStatus `json:"status"`
	SourceFolderID       uuid.UUID          `json:"source_folder_id"`
	SourceFolderName     string             `json:"source_folder_name"`
	PublisherPrincipalID uuid.UUID          `json:"publisher_principal_id"`
	CloneCount           int32              `json:"clone_count"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListVisiblePublishedPodsForPrincipal(ctx context.Context, principalID uuid.UUID) ([]ListVisiblePublishedPodsForPrincipalRow, error) {
	rows, err := q.db.Query(ctx, listVisiblePublishedPodsForPrincipal, principalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVisiblePublishedPodsForPrincipalRow
	for rows.Next() {
		var i ListVisiblePublishedPodsForPrincipalRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.ImageUrl,
			&i.Status,
			&i.SourceFolderID,
			&i.SourceFolderName,
			&i.PublisherPrincipalID,
			&i.CloneCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const offsetPublishedPodQuestionSortOrders = `-- name: OffsetPublishedPodQuestionSortOrders :exec
UPDATE published_pod_task_questions q
SET sort_order = q.sort_order + $1
FROM published_pod_tasks t
WHERE q.task_id = t.id
  AND t.pod_id = $2
`

type OffsetPublishedPodQuestionSortOrdersParams struct {
	SortOffset int32     `json:"sort_offset"`
	PodID      uuid.UUID `json:"pod_id"`
}

func (q *Queries) OffsetPublishedPodQuestionSortOrders(ctx context.Context, arg OffsetPublishedPodQuestionSortOrdersParams) error {
	_, err := q.db.Exec(ctx, offsetPublishedPodQuestionSortOrders, arg.SortOffset, arg.PodID)
	return err
}

const offsetPublishedPodTaskSortOrders = `-- name: OffsetPublishedPodTaskSortOrders :exec
UPDATE published_pod_tasks
SET sort_order = sort_order + $1
WHERE pod_id = $2
`

type OffsetPublishedPodTaskSortOrdersParams struct {
	SortOffset int32     `json:"sort_offset"`
	PodID      uuid.UUID `json:"pod_id"`
}

func (q *Queries) OffsetPublishedPodTaskSortOrders(ctx context.Context, arg OffsetPublishedPodTaskSortOrdersParams) error {
	_, err := q.db.Exec(ctx, offsetPublishedPodTaskSortOrders, arg.SortOffset, arg.PodID)
	return err
}

const refreshClonedPodTaskStatesForPublishedPod = `-- name: RefreshClonedPodTaskStatesForPublishedPod :exec
WITH task_completion AS (
    SELECT
        cp.id AS cloned_pod_id,
        t.id AS task_id,
        NOT EXISTS (
            SELECT 1
            FROM published_pod_task_questions q
            WHERE q.task_id = t.id
              AND NOT EXISTS (
                  SELECT 1
                  FROM cloned_pod_question_answers answer
                  WHERE answer.cloned_pod_id = cp.id
                    AND answer.question_id = q.id
                    AND answer.is_correct = true
              )
        ) AS completed
    FROM cloned_pods cp
    JOIN published_pod_tasks t
      ON t.pod_id = cp.pod_id
    WHERE cp.pod_id = $1
)
INSERT INTO cloned_pod_task_states (
    cloned_pod_id,
    task_id,
    completed,
    completed_at
)
SELECT
    cloned_pod_id,
    task_id,
    completed,
    CASE WHEN completed THEN now() ELSE NULL END
FROM task_completion
ON CONFLICT (cloned_pod_id, task_id) DO UPDATE
SET completed = EXCLUDED.completed,
    completed_at = CASE
        WHEN EXCLUDED.completed AND cloned_pod_task_states.completed THEN cloned_pod_task_states.completed_at
        WHEN EXCLUDED.completed THEN now()
        ELSE NULL
    END
`

func (q *Queries) RefreshClonedPodTaskStatesForPublishedPod(ctx context.Context, podID uuid.UUID) error {
	_, err := q.db.Exec(ctx, refreshClonedPodTaskStatesForPublishedPod, podID)
	return err
}

const setClonedPodTaskCompleted = `-- name: SetClonedPodTaskCompleted :exec
INSERT INTO cloned_pod_task_states (
    cloned_pod_id,
    task_id,
    completed,
    completed_at
) VALUES (
    $1,
    $2,
    $3,
    CASE WHEN $3::BOOLEAN THEN now() ELSE NULL END
)
ON CONFLICT (cloned_pod_id, task_id) DO UPDATE
SET completed = EXCLUDED.completed,
    completed_at = CASE
        WHEN EXCLUDED.completed THEN COALESCE(cloned_pod_task_states.completed_at, now())
        ELSE NULL
    END
`

type SetClonedPodTaskCompletedParams struct {
	ClonedPodID uuid.UUID `json:"cloned_pod_id"`
	TaskID      uuid.UUID `json:"task_id"`
	Completed   bool      `json:"completed"`
}

func (q *Queries) SetClonedPodTaskCompleted(ctx context.Context, arg SetClonedPodTaskCompletedParams) error {
	_, err := q.db.Exec(ctx, setClonedPodTaskCompleted, arg.ClonedPodID, arg.TaskID, arg.Completed)
	return err
}

const updatePublishedPod = `-- name: UpdatePublishedPod :one
UPDATE published_pods
SET title = $2,
    slug = $3,
    description = $4,
    image_url = $5,
    status = $6,
    source_folder_id = $7
WHERE id = $1
RETURNING
    id,
    title,
    slug,
    description,
    image_url,
    status,
    source_folder_id,
    publisher_principal_id,
    clone_count,
    created_at,
    updated_at
`

type UpdatePublishedPodParams struct {
	ID             uuid.UUID          `json:"id"`
	Title          string             `json:"title"`
	Slug           string             `json:"slug"`
	Description    string             `json:"description"`
	ImageUrl       string             `json:"image_url"`
	Status         PublishedPodStatus `json:"status"`
	SourceFolderID uuid.UUID          `json:"source_folder_id"`
}

func (q *Queries) UpdatePublishedPod(ctx context.Context, arg UpdatePublishedPodParams) (PublishedPods, error) {
	row := q.db.QueryRow(ctx, updatePublishedPod,
		arg.ID,
		arg.Title,
		arg.Slug,
		arg.Description,
		arg.ImageUrl,
		arg.Status,
		arg.SourceFolderID,
	)
	var i PublishedPods
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.ImageUrl,
		&i.Status,
		&i.SourceFolderID,
		&i.PublisherPrincipalID,
		&i.CloneCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePublishedPodStatus = `-- name: UpdatePublishedPodStatus :exec
UPDATE published_pods
SET status = $2
WHERE id = $1
`

type UpdatePublishedPodStatusParams struct {
	ID     uuid.UUID          `json:"id"`
	Status PublishedPodStatus `json:"status"`
}

func (q *Queries) UpdatePublishedPodStatus(ctx context.Context, arg UpdatePublishedPodStatusParams) error {
	_, err := q.db.Exec(ctx, updatePublishedPodStatus, arg.ID, arg.Status)
	return err
}

const updatePublishedPodTask = `-- name: UpdatePublishedPodTask :exec
UPDATE published_pod_tasks
SET
    title = $3,
    content = $4,
    sort_order = $5
WHERE id = $1
  AND pod_id = $2
`

type UpdatePublishedPodTaskParams struct {
	ID        uuid.UUID `json:"id"`
	PodID     uuid.UUID `json:"pod_id"`
	Title     string    `json:"title"`
	Content   string    `json:"content"`
	SortOrder int32     `json:"sort_order"`
}

func (q *Queries) UpdatePublishedPodTask(ctx context.Context, arg UpdatePublishedPodTaskParams) error {
	_, err := q.db.Exec(ctx, updatePublishedPodTask,
		arg.ID,
		arg.PodID,
		arg.Title,
		arg.Content,
		arg.SortOrder,
	)
	return err
}

const updatePublishedPodTaskQuestion = `-- name: UpdatePublishedPodTaskQuestion :exec
UPDATE published_pod_task_questions
SET
    task_id = $2,
    title = $3,
    answer_outline = $4,
    description = $5,
    hint = $6,
    sort_order = $7
WHERE id = $1
`

type UpdatePublishedPodTaskQuestionParams struct {
	ID            uuid.UUID `json:"id"`
	TaskID        uuid.UUID `json:"task_id"`
	Title         string    `json:"title"`
	AnswerOutline string    `json:"answer_outline"`
	Description   *string   `json:"description"`
	Hint          *string   `json:"hint"`
	SortOrder     int32     `json:"sort_order"`
}

func (q *Queries) UpdatePublishedPodTaskQuestion(ctx context.Context, arg UpdatePublishedPodTaskQuestionParams) error {
	_, err := q.db.Exec(ctx, updatePublishedPodTaskQuestion,
		arg.ID,
		arg.TaskID,
		arg.Title,
		arg.AnswerOutline,
		arg.Description,
		arg.Hint,
		arg.SortOrder,
	)
	return err
}

const updatePublishedPodVM = `-- name: UpdatePublishedPodVM :exec
UPDATE published_pod_vms
SET
    source_inventory_item_id = $3,
    name = $4,
    cpu_count = $5,
    memory_mb = $6,
    disk_gb = $7,
    allow_mask = $8,
    deny_mask = $9,
    sort_order = $10
WHERE id = $1
  AND pod_id = $2
`

type UpdatePublishedPodVMParams struct {
	ID                    uuid.UUID `json:"id"`
	PodID                 uuid.UUID `json:"pod_id"`
	SourceInventoryItemID uuid.UUID `json:"source_inventory_item_id"`
	Name                  string    `json:"name"`
	CpuCount              int32     `json:"cpu_count"`
	MemoryMb              int32     `json:"memory_mb"`
	DiskGb                float64   `json:"disk_gb"`
	AllowMask             int64     `json:"allow_mask"`
	DenyMask              int64     `json:"deny_mask"`
	SortOrder             int32     `json:"sort_order"`
}

func (q *Queries) UpdatePublishedPodVM(ctx context.Context, arg UpdatePublishedPodVMParams) error {
	_, err := q.db.Exec(ctx, updatePublishedPodVM,
		arg.ID,
		arg.PodID,
		arg.SourceInventoryItemID,
		arg.Name,
		arg.CpuCount,
		arg.MemoryMb,
		arg.DiskGb,
		arg.AllowMask,
		arg.DenyMask,
		arg.SortOrder,
	)
	return err
}

const upsertClonedPodQuestionAnswer = `-- name: UpsertClonedPodQuestionAnswer :one
INSERT INTO cloned_pod_question_answers (
    cloned_pod_id,
    question_id,
    answer,
    is_correct
) VALUES ($1, $2, $3, $4)
ON CONFLICT (cloned_pod_id, question_id) DO UPDATE
SET answer = CASE
        WHEN cloned_pod_question_answers.is_correct THEN cloned_pod_question_answers.answer
        ELSE EXCLUDED.answer
    END,
    is_correct = cloned_pod_question_answers.is_correct OR EXCLUDED.is_correct,
    answered_at = CASE
        WHEN cloned_pod_question_answers.is_correct THEN cloned_pod_question_answers.answered_at
        ELSE now()
    END
RETURNING
    question_id,
    answer,
    is_correct,
    answered_at
`

type UpsertClonedPodQuestionAnswerParams struct {
	ClonedPodID uuid.UUID `json:"cloned_pod_id"`
	QuestionID  uuid.UUID `json:"question_id"`
	Answer      string    `json:"answer"`
	IsCorrect   bool      `json:"is_correct"`
}

type UpsertClonedPodQuestionAnswerRow struct {
	QuestionID uuid.UUID          `json:"question_id"`
	Answer     string             `json:"answer"`
	IsCorrect  bool               `json:"is_correct"`
	AnsweredAt pgtype.Timestamptz `json:"answered_at"`
}

func (q *Queries) UpsertClonedPodQuestionAnswer(ctx context.Context, arg UpsertClonedPodQuestionAnswerParams) (UpsertClonedPodQuestionAnswerRow, error) {
	row := q.db.QueryRow(ctx, upsertClonedPodQuestionAnswer,
		arg.ClonedPodID,
		arg.QuestionID,
		arg.Answer,
		arg.IsCorrect,
	)
	var i UpsertClonedPodQuestionAnswerRow
	err := row.Scan(
		&i.QuestionID,
		&i.Answer,
		&i.IsCorrect,
		&i.AnsweredAt,
	)
	return i, err
}

const upsertPrincipalPodQuestionAnswer = `-- name: UpsertPrincipalPodQuestionAnswer :one
INSERT INTO principal_pod_question_answers (
    principal_id,
    source_pod_id,
    source_task_id,
    source_question_id,
    last_cloned_pod_id,
    pod_slug,
    pod_title,
    task_title,
    question_title,
    answer,
    is_correct,
    answered_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12
)
ON CONFLICT (principal_id, source_pod_id, source_question_id) DO UPDATE
SET
    last_cloned_pod_id = EXCLUDED.last_cloned_pod_id,
    pod_slug = EXCLUDED.pod_slug,
    pod_title = EXCLUDED.pod_title,
    task_title = EXCLUDED.task_title,
    question_title = EXCLUDED.question_title,
    answer = CASE
        WHEN principal_pod_question_answers.is_correct THEN principal_pod_question_answers.answer
        ELSE EXCLUDED.answer
    END,
    is_correct = principal_pod_question_answers.is_correct OR EXCLUDED.is_correct,
    answered_at = CASE
        WHEN principal_pod_question_answers.is_correct THEN principal_pod_question_answers.answered_at
        ELSE EXCLUDED.answered_at
    END
RETURNING
    source_pod_id,
    source_question_id,
    is_correct,
    answered_at
`

type UpsertPrincipalPodQuestionAnswerParams struct {
	PrincipalID      uuid.UUID          `json:"principal_id"`
	SourcePodID      uuid.UUID          `json:"source_pod_id"`
	SourceTaskID     uuid.UUID          `json:"source_task_id"`
	SourceQuestionID uuid.UUID          `json:"source_question_id"`
	LastClonedPodID  *uuid.UUID         `json:"last_cloned_pod_id"`
	PodSlug          string             `json:"pod_slug"`
	PodTitle         string             `json:"pod_title"`
	TaskTitle        string             `json:"task_title"`
	QuestionTitle    string             `json:"question_title"`
	Answer           string             `json:"answer"`
	IsCorrect        bool               `json:"is_correct"`
	AnsweredAt       pgtype.Timestamptz `json:"answered_at"`
}

type UpsertPrincipalPodQuestionAnswerRow struct {
	SourcePodID      uuid.UUID          `json:"source_pod_id"`
	SourceQuestionID uuid.UUID          `json:"source_question_id"`
	IsCorrect        bool               `json:"is_correct"`
	AnsweredAt       pgtype.Timestamptz `json:"answered_at"`
}

func (q *Queries) UpsertPrincipalPodQuestionAnswer(ctx context.Context, arg UpsertPrincipalPodQuestionAnswerParams) (UpsertPrincipalPodQuestionAnswerRow, error) {
	row := q.db.QueryRow(ctx, upsertPrincipalPodQuestionAnswer,
		arg.PrincipalID,
		arg.SourcePodID,
		arg.SourceTaskID,
		arg.SourceQuestionID,
		arg.LastClonedPodID,
		arg.PodSlug,
		arg.PodTitle,
		arg.TaskTitle,
		arg.QuestionTitle,
		arg.Answer,
		arg.IsCorrect,
		arg.AnsweredAt,
	)
	var i UpsertPrincipalPodQuestionAnswerRow
	err := row.Scan(
		&i.SourcePodID,
		&i.SourceQuestionID,
		&i.IsCorrect,
		&i.AnsweredAt,
	)
	return i, err
}
