// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: requests_lists.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countCompletedRequestsForKindsFiltered = `-- name: CountCompletedRequestsForKindsFiltered :one
SELECT count(*)::int
FROM requests r
JOIN principals requester
  ON requester.id = r.requester_principal_id
LEFT JOIN principals reviewer
  ON reviewer.id = r.reviewer_principal_id
LEFT JOIN inventory_requests ir
  ON ir.request_id = r.id
LEFT JOIN inventory_items ii
  ON ii.id = ir.inventory_item_id
LEFT JOIN inventory_items parent
  ON parent.id = ii.parent_id
LEFT JOIN proxmox_vms pv
  ON pv.inventory_item_id = ir.inventory_item_id
WHERE r.status IN ('approved', 'executing', 'denied', 'executed', 'execution_failed')
  AND r.kind = ANY($1::TEXT[])
  AND (
      $2::TEXT = ''
      OR r.kind ILIKE '%' || $2::TEXT || '%'
      OR ir.power_action::TEXT ILIKE '%' || $2::TEXT || '%'
      OR ir.snapshot_name ILIKE '%' || $2::TEXT || '%'
      OR r.status::TEXT ILIKE '%' || $2::TEXT || '%'
      OR COALESCE(requester.name, requester.external_id) ILIKE '%' || $2::TEXT || '%'
      OR r.requester_principal_id::TEXT ILIKE '%' || $2::TEXT || '%'
      OR COALESCE(reviewer.name, reviewer.external_id, '') ILIKE '%' || $2::TEXT || '%'
      OR r.reviewer_principal_id::TEXT ILIKE '%' || $2::TEXT || '%'
      OR ii.name ILIKE '%' || $2::TEXT || '%'
      OR ir.inventory_item_id::TEXT ILIKE '%' || $2::TEXT || '%'
      OR parent.name ILIKE '%' || $2::TEXT || '%'
      OR get_inventory_item_path(ii.id) ILIKE '%' || $2::TEXT || '%'
      OR pv.node ILIKE '%' || $2::TEXT || '%'
      OR pv.vmid::TEXT ILIKE '%' || $2::TEXT || '%'
      OR r.execution_error ILIKE '%' || $2::TEXT || '%'
  )
`

type CountCompletedRequestsForKindsFilteredParams struct {
	Kinds  []string `json:"kinds"`
	Search string   `json:"search"`
}

func (q *Queries) CountCompletedRequestsForKindsFiltered(ctx context.Context, arg CountCompletedRequestsForKindsFilteredParams) (int32, error) {
	row := q.db.QueryRow(ctx, countCompletedRequestsForKindsFiltered, arg.Kinds, arg.Search)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countPendingRequestsByRequesterFiltered = `-- name: CountPendingRequestsByRequesterFiltered :one
SELECT count(*)::int
FROM requests r
JOIN principals requester
  ON requester.id = r.requester_principal_id
LEFT JOIN principals reviewer
  ON reviewer.id = r.reviewer_principal_id
LEFT JOIN inventory_requests ir
  ON ir.request_id = r.id
LEFT JOIN inventory_items ii
  ON ii.id = ir.inventory_item_id
LEFT JOIN inventory_items parent
  ON parent.id = ii.parent_id
LEFT JOIN proxmox_vms pv
  ON pv.inventory_item_id = ir.inventory_item_id
WHERE r.requester_principal_id = $1
  AND r.status = 'pending'
  AND (
      $2::TEXT = ''
      OR r.kind ILIKE '%' || $2::TEXT || '%'
      OR ir.power_action::TEXT ILIKE '%' || $2::TEXT || '%'
      OR ir.snapshot_name ILIKE '%' || $2::TEXT || '%'
      OR r.status::TEXT ILIKE '%' || $2::TEXT || '%'
      OR COALESCE(requester.name, requester.external_id) ILIKE '%' || $2::TEXT || '%'
      OR COALESCE(reviewer.name, reviewer.external_id, '') ILIKE '%' || $2::TEXT || '%'
      OR r.reviewer_principal_id::TEXT ILIKE '%' || $2::TEXT || '%'
      OR ii.name ILIKE '%' || $2::TEXT || '%'
      OR ir.inventory_item_id::TEXT ILIKE '%' || $2::TEXT || '%'
      OR parent.name ILIKE '%' || $2::TEXT || '%'
      OR get_inventory_item_path(ii.id) ILIKE '%' || $2::TEXT || '%'
      OR pv.node ILIKE '%' || $2::TEXT || '%'
      OR pv.vmid::TEXT ILIKE '%' || $2::TEXT || '%'
      OR r.execution_error ILIKE '%' || $2::TEXT || '%'
  )
`

type CountPendingRequestsByRequesterFilteredParams struct {
	RequesterPrincipalID uuid.UUID `json:"requester_principal_id"`
	Search               string    `json:"search"`
}

func (q *Queries) CountPendingRequestsByRequesterFiltered(ctx context.Context, arg CountPendingRequestsByRequesterFilteredParams) (int32, error) {
	row := q.db.QueryRow(ctx, countPendingRequestsByRequesterFiltered, arg.RequesterPrincipalID, arg.Search)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countPendingRequestsFiltered = `-- name: CountPendingRequestsFiltered :one
SELECT count(*)::int
FROM requests r
JOIN principals requester
  ON requester.id = r.requester_principal_id
LEFT JOIN principals reviewer
  ON reviewer.id = r.reviewer_principal_id
LEFT JOIN inventory_requests ir
  ON ir.request_id = r.id
LEFT JOIN inventory_items ii
  ON ii.id = ir.inventory_item_id
LEFT JOIN inventory_items parent
  ON parent.id = ii.parent_id
LEFT JOIN proxmox_vms pv
  ON pv.inventory_item_id = ir.inventory_item_id
WHERE r.status = 'pending'
  AND r.kind = ANY($1::TEXT[])
  AND (
      $2::TEXT = ''
      OR r.kind ILIKE '%' || $2::TEXT || '%'
      OR ir.power_action::TEXT ILIKE '%' || $2::TEXT || '%'
      OR ir.snapshot_name ILIKE '%' || $2::TEXT || '%'
      OR r.status::TEXT ILIKE '%' || $2::TEXT || '%'
      OR COALESCE(requester.name, requester.external_id) ILIKE '%' || $2::TEXT || '%'
      OR r.requester_principal_id::TEXT ILIKE '%' || $2::TEXT || '%'
      OR COALESCE(reviewer.name, reviewer.external_id, '') ILIKE '%' || $2::TEXT || '%'
      OR r.reviewer_principal_id::TEXT ILIKE '%' || $2::TEXT || '%'
      OR ii.name ILIKE '%' || $2::TEXT || '%'
      OR ir.inventory_item_id::TEXT ILIKE '%' || $2::TEXT || '%'
      OR parent.name ILIKE '%' || $2::TEXT || '%'
      OR get_inventory_item_path(ii.id) ILIKE '%' || $2::TEXT || '%'
      OR pv.node ILIKE '%' || $2::TEXT || '%'
      OR pv.vmid::TEXT ILIKE '%' || $2::TEXT || '%'
      OR r.execution_error ILIKE '%' || $2::TEXT || '%'
  )
`

type CountPendingRequestsFilteredParams struct {
	Kinds  []string `json:"kinds"`
	Search string   `json:"search"`
}

func (q *Queries) CountPendingRequestsFiltered(ctx context.Context, arg CountPendingRequestsFilteredParams) (int32, error) {
	row := q.db.QueryRow(ctx, countPendingRequestsFiltered, arg.Kinds, arg.Search)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countRequestHistoryByRequesterFiltered = `-- name: CountRequestHistoryByRequesterFiltered :one
SELECT count(*)::int
FROM requests r
JOIN principals requester
  ON requester.id = r.requester_principal_id
LEFT JOIN principals reviewer
  ON reviewer.id = r.reviewer_principal_id
LEFT JOIN inventory_requests ir
  ON ir.request_id = r.id
LEFT JOIN inventory_items ii
  ON ii.id = ir.inventory_item_id
LEFT JOIN inventory_items parent
  ON parent.id = ii.parent_id
LEFT JOIN proxmox_vms pv
  ON pv.inventory_item_id = ir.inventory_item_id
WHERE r.requester_principal_id = $1
  AND r.status IN ('approved', 'executing', 'denied', 'executed', 'execution_failed')
  AND (
      $2::TEXT = ''
      OR r.kind ILIKE '%' || $2::TEXT || '%'
      OR ir.power_action::TEXT ILIKE '%' || $2::TEXT || '%'
      OR ir.snapshot_name ILIKE '%' || $2::TEXT || '%'
      OR r.status::TEXT ILIKE '%' || $2::TEXT || '%'
      OR COALESCE(requester.name, requester.external_id) ILIKE '%' || $2::TEXT || '%'
      OR COALESCE(reviewer.name, reviewer.external_id, '') ILIKE '%' || $2::TEXT || '%'
      OR r.reviewer_principal_id::TEXT ILIKE '%' || $2::TEXT || '%'
      OR ii.name ILIKE '%' || $2::TEXT || '%'
      OR ir.inventory_item_id::TEXT ILIKE '%' || $2::TEXT || '%'
      OR parent.name ILIKE '%' || $2::TEXT || '%'
      OR get_inventory_item_path(ii.id) ILIKE '%' || $2::TEXT || '%'
      OR pv.node ILIKE '%' || $2::TEXT || '%'
      OR pv.vmid::TEXT ILIKE '%' || $2::TEXT || '%'
      OR r.execution_error ILIKE '%' || $2::TEXT || '%'
  )
`

type CountRequestHistoryByRequesterFilteredParams struct {
	RequesterPrincipalID uuid.UUID `json:"requester_principal_id"`
	Search               string    `json:"search"`
}

func (q *Queries) CountRequestHistoryByRequesterFiltered(ctx context.Context, arg CountRequestHistoryByRequesterFilteredParams) (int32, error) {
	row := q.db.QueryRow(ctx, countRequestHistoryByRequesterFiltered, arg.RequesterPrincipalID, arg.Search)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const listCompletedRequestsForKindsFiltered = `-- name: ListCompletedRequestsForKindsFiltered :many
SELECT
    r.id,
    r.family,
    r.kind,
    r.requester_principal_id,
    r.reviewer_principal_id,
    r.status,
    r.reviewed_at,
    r.executed_at,
    r.canceled_at,
    r.execution_error,
    r.created_at,
    r.updated_at,
    COALESCE(requester.name, requester.external_id) AS requester_username,
    COALESCE(reviewer.name, reviewer.external_id, '') AS reviewer_username,
    ir.inventory_item_id,
    ir.power_action,
    ir.snapshot_name,
    ii.kind AS inventory_item_kind,
    ii.name AS inventory_item_name,
    ii.parent_id AS inventory_item_parent_id,
    parent.name AS inventory_item_parent_name,
    get_inventory_item_path(ii.id) AS inventory_item_path,
    pv.node AS inventory_vm_node,
    pv.vmid AS inventory_vm_vmid,
    pv.is_template AS inventory_vm_is_template
FROM requests r
JOIN principals requester
  ON requester.id = r.requester_principal_id
LEFT JOIN principals reviewer
  ON reviewer.id = r.reviewer_principal_id
LEFT JOIN inventory_requests ir
  ON ir.request_id = r.id
LEFT JOIN inventory_items ii
  ON ii.id = ir.inventory_item_id
LEFT JOIN inventory_items parent
  ON parent.id = ii.parent_id
LEFT JOIN proxmox_vms pv
  ON pv.inventory_item_id = ir.inventory_item_id
WHERE r.status IN ('approved', 'executing', 'denied', 'executed', 'execution_failed')
  AND r.kind = ANY($1::TEXT[])
  AND (
      $2::TEXT = ''
      OR r.kind ILIKE '%' || $2::TEXT || '%'
      OR ir.power_action::TEXT ILIKE '%' || $2::TEXT || '%'
      OR ir.snapshot_name ILIKE '%' || $2::TEXT || '%'
      OR r.status::TEXT ILIKE '%' || $2::TEXT || '%'
      OR COALESCE(requester.name, requester.external_id) ILIKE '%' || $2::TEXT || '%'
      OR r.requester_principal_id::TEXT ILIKE '%' || $2::TEXT || '%'
      OR COALESCE(reviewer.name, reviewer.external_id, '') ILIKE '%' || $2::TEXT || '%'
      OR r.reviewer_principal_id::TEXT ILIKE '%' || $2::TEXT || '%'
      OR ii.name ILIKE '%' || $2::TEXT || '%'
      OR ir.inventory_item_id::TEXT ILIKE '%' || $2::TEXT || '%'
      OR parent.name ILIKE '%' || $2::TEXT || '%'
      OR get_inventory_item_path(ii.id) ILIKE '%' || $2::TEXT || '%'
      OR pv.node ILIKE '%' || $2::TEXT || '%'
      OR pv.vmid::TEXT ILIKE '%' || $2::TEXT || '%'
      OR r.execution_error ILIKE '%' || $2::TEXT || '%'
  )
ORDER BY r.updated_at DESC, r.created_at DESC, r.id DESC
LIMIT $4
OFFSET $3
`

type ListCompletedRequestsForKindsFilteredParams struct {
	Kinds     []string `json:"kinds"`
	Search    string   `json:"search"`
	RowOffset int32    `json:"row_offset"`
	Rows      int32    `json:"rows"`
}

type ListCompletedRequestsForKindsFilteredRow struct {
	ID                      uuid.UUID                       `json:"id"`
	Family                  RequestFamily                   `json:"family"`
	Kind                    string                          `json:"kind"`
	RequesterPrincipalID    uuid.UUID                       `json:"requester_principal_id"`
	ReviewerPrincipalID     *uuid.UUID                      `json:"reviewer_principal_id"`
	Status                  RequestStatus                   `json:"status"`
	ReviewedAt              pgtype.Timestamptz              `json:"reviewed_at"`
	ExecutedAt              pgtype.Timestamptz              `json:"executed_at"`
	CanceledAt              pgtype.Timestamptz              `json:"canceled_at"`
	ExecutionError          *string                         `json:"execution_error"`
	CreatedAt               pgtype.Timestamptz              `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz              `json:"updated_at"`
	RequesterUsername       string                          `json:"requester_username"`
	ReviewerUsername        string                          `json:"reviewer_username"`
	InventoryItemID         *uuid.UUID                      `json:"inventory_item_id"`
	PowerAction             NullInventoryRequestPowerAction `json:"power_action"`
	SnapshotName            *string                         `json:"snapshot_name"`
	InventoryItemKind       NullInventoryItemKind           `json:"inventory_item_kind"`
	InventoryItemName       *string                         `json:"inventory_item_name"`
	InventoryItemParentID   *uuid.UUID                      `json:"inventory_item_parent_id"`
	InventoryItemParentName *string                         `json:"inventory_item_parent_name"`
	InventoryItemPath       string                          `json:"inventory_item_path"`
	InventoryVmNode         *string                         `json:"inventory_vm_node"`
	InventoryVmVmid         *int32                          `json:"inventory_vm_vmid"`
	InventoryVmIsTemplate   *bool                           `json:"inventory_vm_is_template"`
}

func (q *Queries) ListCompletedRequestsForKindsFiltered(ctx context.Context, arg ListCompletedRequestsForKindsFilteredParams) ([]ListCompletedRequestsForKindsFilteredRow, error) {
	rows, err := q.db.Query(ctx, listCompletedRequestsForKindsFiltered,
		arg.Kinds,
		arg.Search,
		arg.RowOffset,
		arg.Rows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCompletedRequestsForKindsFilteredRow
	for rows.Next() {
		var i ListCompletedRequestsForKindsFilteredRow
		if err := rows.Scan(
			&i.ID,
			&i.Family,
			&i.Kind,
			&i.RequesterPrincipalID,
			&i.ReviewerPrincipalID,
			&i.Status,
			&i.ReviewedAt,
			&i.ExecutedAt,
			&i.CanceledAt,
			&i.ExecutionError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RequesterUsername,
			&i.ReviewerUsername,
			&i.InventoryItemID,
			&i.PowerAction,
			&i.SnapshotName,
			&i.InventoryItemKind,
			&i.InventoryItemName,
			&i.InventoryItemParentID,
			&i.InventoryItemParentName,
			&i.InventoryItemPath,
			&i.InventoryVmNode,
			&i.InventoryVmVmid,
			&i.InventoryVmIsTemplate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingRequestsByRequesterFiltered = `-- name: ListPendingRequestsByRequesterFiltered :many
SELECT
    r.id,
    r.family,
    r.kind,
    r.requester_principal_id,
    r.reviewer_principal_id,
    r.status,
    r.reviewed_at,
    r.executed_at,
    r.canceled_at,
    r.execution_error,
    r.created_at,
    r.updated_at,
    COALESCE(requester.name, requester.external_id) AS requester_username,
    COALESCE(reviewer.name, reviewer.external_id, '') AS reviewer_username,
    ir.inventory_item_id,
    ir.power_action,
    ir.snapshot_name,
    ii.kind AS inventory_item_kind,
    ii.name AS inventory_item_name,
    ii.parent_id AS inventory_item_parent_id,
    parent.name AS inventory_item_parent_name,
    get_inventory_item_path(ii.id) AS inventory_item_path,
    pv.node AS inventory_vm_node,
    pv.vmid AS inventory_vm_vmid,
    pv.is_template AS inventory_vm_is_template
FROM requests r
JOIN principals requester
  ON requester.id = r.requester_principal_id
LEFT JOIN principals reviewer
  ON reviewer.id = r.reviewer_principal_id
LEFT JOIN inventory_requests ir
  ON ir.request_id = r.id
LEFT JOIN inventory_items ii
  ON ii.id = ir.inventory_item_id
LEFT JOIN inventory_items parent
  ON parent.id = ii.parent_id
LEFT JOIN proxmox_vms pv
  ON pv.inventory_item_id = ir.inventory_item_id
WHERE r.requester_principal_id = $1
  AND r.status = 'pending'
  AND (
      $2::TEXT = ''
      OR r.kind ILIKE '%' || $2::TEXT || '%'
      OR ir.power_action::TEXT ILIKE '%' || $2::TEXT || '%'
      OR ir.snapshot_name ILIKE '%' || $2::TEXT || '%'
      OR r.status::TEXT ILIKE '%' || $2::TEXT || '%'
      OR COALESCE(requester.name, requester.external_id) ILIKE '%' || $2::TEXT || '%'
      OR COALESCE(reviewer.name, reviewer.external_id, '') ILIKE '%' || $2::TEXT || '%'
      OR r.reviewer_principal_id::TEXT ILIKE '%' || $2::TEXT || '%'
      OR ii.name ILIKE '%' || $2::TEXT || '%'
      OR ir.inventory_item_id::TEXT ILIKE '%' || $2::TEXT || '%'
      OR parent.name ILIKE '%' || $2::TEXT || '%'
      OR get_inventory_item_path(ii.id) ILIKE '%' || $2::TEXT || '%'
      OR pv.node ILIKE '%' || $2::TEXT || '%'
      OR pv.vmid::TEXT ILIKE '%' || $2::TEXT || '%'
      OR r.execution_error ILIKE '%' || $2::TEXT || '%'
  )
ORDER BY r.created_at DESC, r.id DESC
LIMIT $4
OFFSET $3
`

type ListPendingRequestsByRequesterFilteredParams struct {
	RequesterPrincipalID uuid.UUID `json:"requester_principal_id"`
	Search               string    `json:"search"`
	RowOffset            int32     `json:"row_offset"`
	Rows                 int32     `json:"rows"`
}

type ListPendingRequestsByRequesterFilteredRow struct {
	ID                      uuid.UUID                       `json:"id"`
	Family                  RequestFamily                   `json:"family"`
	Kind                    string                          `json:"kind"`
	RequesterPrincipalID    uuid.UUID                       `json:"requester_principal_id"`
	ReviewerPrincipalID     *uuid.UUID                      `json:"reviewer_principal_id"`
	Status                  RequestStatus                   `json:"status"`
	ReviewedAt              pgtype.Timestamptz              `json:"reviewed_at"`
	ExecutedAt              pgtype.Timestamptz              `json:"executed_at"`
	CanceledAt              pgtype.Timestamptz              `json:"canceled_at"`
	ExecutionError          *string                         `json:"execution_error"`
	CreatedAt               pgtype.Timestamptz              `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz              `json:"updated_at"`
	RequesterUsername       string                          `json:"requester_username"`
	ReviewerUsername        string                          `json:"reviewer_username"`
	InventoryItemID         *uuid.UUID                      `json:"inventory_item_id"`
	PowerAction             NullInventoryRequestPowerAction `json:"power_action"`
	SnapshotName            *string                         `json:"snapshot_name"`
	InventoryItemKind       NullInventoryItemKind           `json:"inventory_item_kind"`
	InventoryItemName       *string                         `json:"inventory_item_name"`
	InventoryItemParentID   *uuid.UUID                      `json:"inventory_item_parent_id"`
	InventoryItemParentName *string                         `json:"inventory_item_parent_name"`
	InventoryItemPath       string                          `json:"inventory_item_path"`
	InventoryVmNode         *string                         `json:"inventory_vm_node"`
	InventoryVmVmid         *int32                          `json:"inventory_vm_vmid"`
	InventoryVmIsTemplate   *bool                           `json:"inventory_vm_is_template"`
}

func (q *Queries) ListPendingRequestsByRequesterFiltered(ctx context.Context, arg ListPendingRequestsByRequesterFilteredParams) ([]ListPendingRequestsByRequesterFilteredRow, error) {
	rows, err := q.db.Query(ctx, listPendingRequestsByRequesterFiltered,
		arg.RequesterPrincipalID,
		arg.Search,
		arg.RowOffset,
		arg.Rows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingRequestsByRequesterFilteredRow
	for rows.Next() {
		var i ListPendingRequestsByRequesterFilteredRow
		if err := rows.Scan(
			&i.ID,
			&i.Family,
			&i.Kind,
			&i.RequesterPrincipalID,
			&i.ReviewerPrincipalID,
			&i.Status,
			&i.ReviewedAt,
			&i.ExecutedAt,
			&i.CanceledAt,
			&i.ExecutionError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RequesterUsername,
			&i.ReviewerUsername,
			&i.InventoryItemID,
			&i.PowerAction,
			&i.SnapshotName,
			&i.InventoryItemKind,
			&i.InventoryItemName,
			&i.InventoryItemParentID,
			&i.InventoryItemParentName,
			&i.InventoryItemPath,
			&i.InventoryVmNode,
			&i.InventoryVmVmid,
			&i.InventoryVmIsTemplate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingRequestsFiltered = `-- name: ListPendingRequestsFiltered :many
SELECT
    r.id,
    r.family,
    r.kind,
    r.requester_principal_id,
    r.reviewer_principal_id,
    r.status,
    r.reviewed_at,
    r.executed_at,
    r.canceled_at,
    r.execution_error,
    r.created_at,
    r.updated_at,
    COALESCE(requester.name, requester.external_id) AS requester_username,
    COALESCE(reviewer.name, reviewer.external_id, '') AS reviewer_username,
    ir.inventory_item_id,
    ir.power_action,
    ir.snapshot_name,
    ii.kind AS inventory_item_kind,
    ii.name AS inventory_item_name,
    ii.parent_id AS inventory_item_parent_id,
    parent.name AS inventory_item_parent_name,
    get_inventory_item_path(ii.id) AS inventory_item_path,
    pv.node AS inventory_vm_node,
    pv.vmid AS inventory_vm_vmid,
    pv.is_template AS inventory_vm_is_template
FROM requests r
JOIN principals requester
  ON requester.id = r.requester_principal_id
LEFT JOIN principals reviewer
  ON reviewer.id = r.reviewer_principal_id
LEFT JOIN inventory_requests ir
  ON ir.request_id = r.id
LEFT JOIN inventory_items ii
  ON ii.id = ir.inventory_item_id
LEFT JOIN inventory_items parent
  ON parent.id = ii.parent_id
LEFT JOIN proxmox_vms pv
  ON pv.inventory_item_id = ir.inventory_item_id
WHERE r.status = 'pending'
  AND r.kind = ANY($1::TEXT[])
  AND (
      $2::TEXT = ''
      OR r.kind ILIKE '%' || $2::TEXT || '%'
      OR ir.power_action::TEXT ILIKE '%' || $2::TEXT || '%'
      OR ir.snapshot_name ILIKE '%' || $2::TEXT || '%'
      OR r.status::TEXT ILIKE '%' || $2::TEXT || '%'
      OR COALESCE(requester.name, requester.external_id) ILIKE '%' || $2::TEXT || '%'
      OR r.requester_principal_id::TEXT ILIKE '%' || $2::TEXT || '%'
      OR COALESCE(reviewer.name, reviewer.external_id, '') ILIKE '%' || $2::TEXT || '%'
      OR r.reviewer_principal_id::TEXT ILIKE '%' || $2::TEXT || '%'
      OR ii.name ILIKE '%' || $2::TEXT || '%'
      OR ir.inventory_item_id::TEXT ILIKE '%' || $2::TEXT || '%'
      OR parent.name ILIKE '%' || $2::TEXT || '%'
      OR get_inventory_item_path(ii.id) ILIKE '%' || $2::TEXT || '%'
      OR pv.node ILIKE '%' || $2::TEXT || '%'
      OR pv.vmid::TEXT ILIKE '%' || $2::TEXT || '%'
      OR r.execution_error ILIKE '%' || $2::TEXT || '%'
  )
ORDER BY r.created_at ASC, r.id ASC
LIMIT $4
OFFSET $3
`

type ListPendingRequestsFilteredParams struct {
	Kinds     []string `json:"kinds"`
	Search    string   `json:"search"`
	RowOffset int32    `json:"row_offset"`
	Rows      int32    `json:"rows"`
}

type ListPendingRequestsFilteredRow struct {
	ID                      uuid.UUID                       `json:"id"`
	Family                  RequestFamily                   `json:"family"`
	Kind                    string                          `json:"kind"`
	RequesterPrincipalID    uuid.UUID                       `json:"requester_principal_id"`
	ReviewerPrincipalID     *uuid.UUID                      `json:"reviewer_principal_id"`
	Status                  RequestStatus                   `json:"status"`
	ReviewedAt              pgtype.Timestamptz              `json:"reviewed_at"`
	ExecutedAt              pgtype.Timestamptz              `json:"executed_at"`
	CanceledAt              pgtype.Timestamptz              `json:"canceled_at"`
	ExecutionError          *string                         `json:"execution_error"`
	CreatedAt               pgtype.Timestamptz              `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz              `json:"updated_at"`
	RequesterUsername       string                          `json:"requester_username"`
	ReviewerUsername        string                          `json:"reviewer_username"`
	InventoryItemID         *uuid.UUID                      `json:"inventory_item_id"`
	PowerAction             NullInventoryRequestPowerAction `json:"power_action"`
	SnapshotName            *string                         `json:"snapshot_name"`
	InventoryItemKind       NullInventoryItemKind           `json:"inventory_item_kind"`
	InventoryItemName       *string                         `json:"inventory_item_name"`
	InventoryItemParentID   *uuid.UUID                      `json:"inventory_item_parent_id"`
	InventoryItemParentName *string                         `json:"inventory_item_parent_name"`
	InventoryItemPath       string                          `json:"inventory_item_path"`
	InventoryVmNode         *string                         `json:"inventory_vm_node"`
	InventoryVmVmid         *int32                          `json:"inventory_vm_vmid"`
	InventoryVmIsTemplate   *bool                           `json:"inventory_vm_is_template"`
}

func (q *Queries) ListPendingRequestsFiltered(ctx context.Context, arg ListPendingRequestsFilteredParams) ([]ListPendingRequestsFilteredRow, error) {
	rows, err := q.db.Query(ctx, listPendingRequestsFiltered,
		arg.Kinds,
		arg.Search,
		arg.RowOffset,
		arg.Rows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingRequestsFilteredRow
	for rows.Next() {
		var i ListPendingRequestsFilteredRow
		if err := rows.Scan(
			&i.ID,
			&i.Family,
			&i.Kind,
			&i.RequesterPrincipalID,
			&i.ReviewerPrincipalID,
			&i.Status,
			&i.ReviewedAt,
			&i.ExecutedAt,
			&i.CanceledAt,
			&i.ExecutionError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RequesterUsername,
			&i.ReviewerUsername,
			&i.InventoryItemID,
			&i.PowerAction,
			&i.SnapshotName,
			&i.InventoryItemKind,
			&i.InventoryItemName,
			&i.InventoryItemParentID,
			&i.InventoryItemParentName,
			&i.InventoryItemPath,
			&i.InventoryVmNode,
			&i.InventoryVmVmid,
			&i.InventoryVmIsTemplate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequestHistoryByRequesterFiltered = `-- name: ListRequestHistoryByRequesterFiltered :many
SELECT
    r.id,
    r.family,
    r.kind,
    r.requester_principal_id,
    r.reviewer_principal_id,
    r.status,
    r.reviewed_at,
    r.executed_at,
    r.canceled_at,
    r.execution_error,
    r.created_at,
    r.updated_at,
    COALESCE(requester.name, requester.external_id) AS requester_username,
    COALESCE(reviewer.name, reviewer.external_id, '') AS reviewer_username,
    ir.inventory_item_id,
    ir.power_action,
    ir.snapshot_name,
    ii.kind AS inventory_item_kind,
    ii.name AS inventory_item_name,
    ii.parent_id AS inventory_item_parent_id,
    parent.name AS inventory_item_parent_name,
    get_inventory_item_path(ii.id) AS inventory_item_path,
    pv.node AS inventory_vm_node,
    pv.vmid AS inventory_vm_vmid,
    pv.is_template AS inventory_vm_is_template
FROM requests r
JOIN principals requester
  ON requester.id = r.requester_principal_id
LEFT JOIN principals reviewer
  ON reviewer.id = r.reviewer_principal_id
LEFT JOIN inventory_requests ir
  ON ir.request_id = r.id
LEFT JOIN inventory_items ii
  ON ii.id = ir.inventory_item_id
LEFT JOIN inventory_items parent
  ON parent.id = ii.parent_id
LEFT JOIN proxmox_vms pv
  ON pv.inventory_item_id = ir.inventory_item_id
WHERE r.requester_principal_id = $1
  AND r.status IN ('approved', 'executing', 'denied', 'executed', 'execution_failed')
  AND (
      $2::TEXT = ''
      OR r.kind ILIKE '%' || $2::TEXT || '%'
      OR ir.power_action::TEXT ILIKE '%' || $2::TEXT || '%'
      OR ir.snapshot_name ILIKE '%' || $2::TEXT || '%'
      OR r.status::TEXT ILIKE '%' || $2::TEXT || '%'
      OR COALESCE(requester.name, requester.external_id) ILIKE '%' || $2::TEXT || '%'
      OR COALESCE(reviewer.name, reviewer.external_id, '') ILIKE '%' || $2::TEXT || '%'
      OR r.reviewer_principal_id::TEXT ILIKE '%' || $2::TEXT || '%'
      OR ii.name ILIKE '%' || $2::TEXT || '%'
      OR ir.inventory_item_id::TEXT ILIKE '%' || $2::TEXT || '%'
      OR parent.name ILIKE '%' || $2::TEXT || '%'
      OR get_inventory_item_path(ii.id) ILIKE '%' || $2::TEXT || '%'
      OR pv.node ILIKE '%' || $2::TEXT || '%'
      OR pv.vmid::TEXT ILIKE '%' || $2::TEXT || '%'
      OR r.execution_error ILIKE '%' || $2::TEXT || '%'
  )
ORDER BY r.updated_at DESC, r.created_at DESC, r.id DESC
LIMIT $4
OFFSET $3
`

type ListRequestHistoryByRequesterFilteredParams struct {
	RequesterPrincipalID uuid.UUID `json:"requester_principal_id"`
	Search               string    `json:"search"`
	RowOffset            int32     `json:"row_offset"`
	Rows                 int32     `json:"rows"`
}

type ListRequestHistoryByRequesterFilteredRow struct {
	ID                      uuid.UUID                       `json:"id"`
	Family                  RequestFamily                   `json:"family"`
	Kind                    string                          `json:"kind"`
	RequesterPrincipalID    uuid.UUID                       `json:"requester_principal_id"`
	ReviewerPrincipalID     *uuid.UUID                      `json:"reviewer_principal_id"`
	Status                  RequestStatus                   `json:"status"`
	ReviewedAt              pgtype.Timestamptz              `json:"reviewed_at"`
	ExecutedAt              pgtype.Timestamptz              `json:"executed_at"`
	CanceledAt              pgtype.Timestamptz              `json:"canceled_at"`
	ExecutionError          *string                         `json:"execution_error"`
	CreatedAt               pgtype.Timestamptz              `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz              `json:"updated_at"`
	RequesterUsername       string                          `json:"requester_username"`
	ReviewerUsername        string                          `json:"reviewer_username"`
	InventoryItemID         *uuid.UUID                      `json:"inventory_item_id"`
	PowerAction             NullInventoryRequestPowerAction `json:"power_action"`
	SnapshotName            *string                         `json:"snapshot_name"`
	InventoryItemKind       NullInventoryItemKind           `json:"inventory_item_kind"`
	InventoryItemName       *string                         `json:"inventory_item_name"`
	InventoryItemParentID   *uuid.UUID                      `json:"inventory_item_parent_id"`
	InventoryItemParentName *string                         `json:"inventory_item_parent_name"`
	InventoryItemPath       string                          `json:"inventory_item_path"`
	InventoryVmNode         *string                         `json:"inventory_vm_node"`
	InventoryVmVmid         *int32                          `json:"inventory_vm_vmid"`
	InventoryVmIsTemplate   *bool                           `json:"inventory_vm_is_template"`
}

func (q *Queries) ListRequestHistoryByRequesterFiltered(ctx context.Context, arg ListRequestHistoryByRequesterFilteredParams) ([]ListRequestHistoryByRequesterFilteredRow, error) {
	rows, err := q.db.Query(ctx, listRequestHistoryByRequesterFiltered,
		arg.RequesterPrincipalID,
		arg.Search,
		arg.RowOffset,
		arg.Rows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRequestHistoryByRequesterFilteredRow
	for rows.Next() {
		var i ListRequestHistoryByRequesterFilteredRow
		if err := rows.Scan(
			&i.ID,
			&i.Family,
			&i.Kind,
			&i.RequesterPrincipalID,
			&i.ReviewerPrincipalID,
			&i.Status,
			&i.ReviewedAt,
			&i.ExecutedAt,
			&i.CanceledAt,
			&i.ExecutionError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RequesterUsername,
			&i.ReviewerUsername,
			&i.InventoryItemID,
			&i.PowerAction,
			&i.SnapshotName,
			&i.InventoryItemKind,
			&i.InventoryItemName,
			&i.InventoryItemParentID,
			&i.InventoryItemParentName,
			&i.InventoryItemPath,
			&i.InventoryVmNode,
			&i.InventoryVmVmid,
			&i.InventoryVmIsTemplate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
