// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: requests_actions.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const approveRequest = `-- name: ApproveRequest :one
UPDATE requests
SET
    status = 'executing',
    reviewer_principal_id = $2,
    reviewed_at = now(),
    execution_started_at = now(),
    canceled_at = NULL,
    execution_error = NULL
WHERE id = $1
  AND status = 'pending'
RETURNING
    id,
    family,
    kind,
    requester_principal_id,
    reviewer_principal_id,
    status,
    reviewed_at,
    execution_started_at,
    executed_at,
    canceled_at,
    execution_error,
    created_at,
    updated_at
`

type ApproveRequestParams struct {
	ID                  uuid.UUID  `json:"id"`
	ReviewerPrincipalID *uuid.UUID `json:"reviewer_principal_id"`
}

func (q *Queries) ApproveRequest(ctx context.Context, arg ApproveRequestParams) (Requests, error) {
	row := q.db.QueryRow(ctx, approveRequest, arg.ID, arg.ReviewerPrincipalID)
	var i Requests
	err := row.Scan(
		&i.ID,
		&i.Family,
		&i.Kind,
		&i.RequesterPrincipalID,
		&i.ReviewerPrincipalID,
		&i.Status,
		&i.ReviewedAt,
		&i.ExecutionStartedAt,
		&i.ExecutedAt,
		&i.CanceledAt,
		&i.ExecutionError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const cancelRequest = `-- name: CancelRequest :one
UPDATE requests
SET
    status = 'canceled',
    canceled_at = now()
WHERE id = $1
  AND status = 'pending'
RETURNING
    id,
    family,
    kind,
    requester_principal_id,
    reviewer_principal_id,
    status,
    reviewed_at,
    executed_at,
    canceled_at,
    execution_error,
    created_at,
    updated_at
`

type CancelRequestRow struct {
	ID                   uuid.UUID          `json:"id"`
	Family               RequestFamily      `json:"family"`
	Kind                 string             `json:"kind"`
	RequesterPrincipalID uuid.UUID          `json:"requester_principal_id"`
	ReviewerPrincipalID  *uuid.UUID         `json:"reviewer_principal_id"`
	Status               RequestStatus      `json:"status"`
	ReviewedAt           pgtype.Timestamptz `json:"reviewed_at"`
	ExecutedAt           pgtype.Timestamptz `json:"executed_at"`
	CanceledAt           pgtype.Timestamptz `json:"canceled_at"`
	ExecutionError       *string            `json:"execution_error"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CancelRequest(ctx context.Context, id uuid.UUID) (CancelRequestRow, error) {
	row := q.db.QueryRow(ctx, cancelRequest, id)
	var i CancelRequestRow
	err := row.Scan(
		&i.ID,
		&i.Family,
		&i.Kind,
		&i.RequesterPrincipalID,
		&i.ReviewerPrincipalID,
		&i.Status,
		&i.ReviewedAt,
		&i.ExecutedAt,
		&i.CanceledAt,
		&i.ExecutionError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const denyRequest = `-- name: DenyRequest :one
UPDATE requests
SET
    status = 'denied',
    reviewer_principal_id = $2,
    reviewed_at = now(),
    canceled_at = NULL
WHERE id = $1
  AND status = 'pending'
RETURNING
    id,
    family,
    kind,
    requester_principal_id,
    reviewer_principal_id,
    status,
    reviewed_at,
    executed_at,
    canceled_at,
    execution_error,
    created_at,
    updated_at
`

type DenyRequestParams struct {
	ID                  uuid.UUID  `json:"id"`
	ReviewerPrincipalID *uuid.UUID `json:"reviewer_principal_id"`
}

type DenyRequestRow struct {
	ID                   uuid.UUID          `json:"id"`
	Family               RequestFamily      `json:"family"`
	Kind                 string             `json:"kind"`
	RequesterPrincipalID uuid.UUID          `json:"requester_principal_id"`
	ReviewerPrincipalID  *uuid.UUID         `json:"reviewer_principal_id"`
	Status               RequestStatus      `json:"status"`
	ReviewedAt           pgtype.Timestamptz `json:"reviewed_at"`
	ExecutedAt           pgtype.Timestamptz `json:"executed_at"`
	CanceledAt           pgtype.Timestamptz `json:"canceled_at"`
	ExecutionError       *string            `json:"execution_error"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) DenyRequest(ctx context.Context, arg DenyRequestParams) (DenyRequestRow, error) {
	row := q.db.QueryRow(ctx, denyRequest, arg.ID, arg.ReviewerPrincipalID)
	var i DenyRequestRow
	err := row.Scan(
		&i.ID,
		&i.Family,
		&i.Kind,
		&i.RequesterPrincipalID,
		&i.ReviewerPrincipalID,
		&i.Status,
		&i.ReviewedAt,
		&i.ExecutedAt,
		&i.CanceledAt,
		&i.ExecutionError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listStaleExecutingRequests = `-- name: ListStaleExecutingRequests :many
SELECT
    id,
    family,
    kind,
    requester_principal_id,
    reviewer_principal_id,
    status,
    reviewed_at,
    execution_started_at,
    executed_at,
    canceled_at,
    execution_error,
    created_at,
    updated_at
FROM requests
WHERE status = 'executing'
  AND execution_started_at IS NOT NULL
  AND execution_started_at < $1
ORDER BY execution_started_at ASC, id ASC
`

func (q *Queries) ListStaleExecutingRequests(ctx context.Context, executionStartedAt pgtype.Timestamptz) ([]Requests, error) {
	rows, err := q.db.Query(ctx, listStaleExecutingRequests, executionStartedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Requests
	for rows.Next() {
		var i Requests
		if err := rows.Scan(
			&i.ID,
			&i.Family,
			&i.Kind,
			&i.RequesterPrincipalID,
			&i.ReviewerPrincipalID,
			&i.Status,
			&i.ReviewedAt,
			&i.ExecutionStartedAt,
			&i.ExecutedAt,
			&i.CanceledAt,
			&i.ExecutionError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRequestExecuted = `-- name: MarkRequestExecuted :one
UPDATE requests
SET
    status = 'executed',
    executed_at = now(),
    execution_error = NULL
WHERE id = $1
  AND status = 'executing'
RETURNING
    id,
    family,
    kind,
    requester_principal_id,
    reviewer_principal_id,
    status,
    reviewed_at,
    execution_started_at,
    executed_at,
    canceled_at,
    execution_error,
    created_at,
    updated_at
`

func (q *Queries) MarkRequestExecuted(ctx context.Context, id uuid.UUID) (Requests, error) {
	row := q.db.QueryRow(ctx, markRequestExecuted, id)
	var i Requests
	err := row.Scan(
		&i.ID,
		&i.Family,
		&i.Kind,
		&i.RequesterPrincipalID,
		&i.ReviewerPrincipalID,
		&i.Status,
		&i.ReviewedAt,
		&i.ExecutionStartedAt,
		&i.ExecutedAt,
		&i.CanceledAt,
		&i.ExecutionError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markRequestExecutionFailed = `-- name: MarkRequestExecutionFailed :one
UPDATE requests
SET
    status = 'execution_failed',
    executed_at = now(),
    execution_error = $2
WHERE id = $1
  AND status = 'executing'
RETURNING
    id,
    family,
    kind,
    requester_principal_id,
    reviewer_principal_id,
    status,
    reviewed_at,
    execution_started_at,
    executed_at,
    canceled_at,
    execution_error,
    created_at,
    updated_at
`

type MarkRequestExecutionFailedParams struct {
	ID             uuid.UUID `json:"id"`
	ExecutionError *string   `json:"execution_error"`
}

func (q *Queries) MarkRequestExecutionFailed(ctx context.Context, arg MarkRequestExecutionFailedParams) (Requests, error) {
	row := q.db.QueryRow(ctx, markRequestExecutionFailed, arg.ID, arg.ExecutionError)
	var i Requests
	err := row.Scan(
		&i.ID,
		&i.Family,
		&i.Kind,
		&i.RequesterPrincipalID,
		&i.ReviewerPrincipalID,
		&i.Status,
		&i.ReviewedAt,
		&i.ExecutionStartedAt,
		&i.ExecutedAt,
		&i.CanceledAt,
		&i.ExecutionError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
