// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: requests_create.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countPendingRequestsByRequester = `-- name: CountPendingRequestsByRequester :one
SELECT count(*)::int
FROM requests
WHERE requester_principal_id = $1
  AND status = 'pending'
`

func (q *Queries) CountPendingRequestsByRequester(ctx context.Context, requesterPrincipalID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countPendingRequestsByRequester, requesterPrincipalID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createInventoryRequest = `-- name: CreateInventoryRequest :one
INSERT INTO inventory_requests (
    request_id,
    inventory_item_id,
    power_action,
    snapshot_name
) VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING
    request_id,
    inventory_item_id,
    power_action,
    snapshot_name,
    created_at
`

type CreateInventoryRequestParams struct {
	RequestID       uuid.UUID                       `json:"request_id"`
	InventoryItemID uuid.UUID                       `json:"inventory_item_id"`
	PowerAction     NullInventoryRequestPowerAction `json:"power_action"`
	SnapshotName    *string                         `json:"snapshot_name"`
}

func (q *Queries) CreateInventoryRequest(ctx context.Context, arg CreateInventoryRequestParams) (InventoryRequests, error) {
	row := q.db.QueryRow(ctx, createInventoryRequest,
		arg.RequestID,
		arg.InventoryItemID,
		arg.PowerAction,
		arg.SnapshotName,
	)
	var i InventoryRequests
	err := row.Scan(
		&i.RequestID,
		&i.InventoryItemID,
		&i.PowerAction,
		&i.SnapshotName,
		&i.CreatedAt,
	)
	return i, err
}

const createRequest = `-- name: CreateRequest :one
INSERT INTO requests (
    family,
    kind,
    requester_principal_id
) VALUES (
    $1,
    $2,
    $3
)
RETURNING
    id,
    family,
    kind,
    requester_principal_id,
    reviewer_principal_id,
    status,
    reviewed_at,
    executed_at,
    canceled_at,
    execution_error,
    created_at,
    updated_at
`

type CreateRequestParams struct {
	Family               RequestFamily `json:"family"`
	Kind                 string        `json:"kind"`
	RequesterPrincipalID uuid.UUID     `json:"requester_principal_id"`
}

type CreateRequestRow struct {
	ID                   uuid.UUID          `json:"id"`
	Family               RequestFamily      `json:"family"`
	Kind                 string             `json:"kind"`
	RequesterPrincipalID uuid.UUID          `json:"requester_principal_id"`
	ReviewerPrincipalID  *uuid.UUID         `json:"reviewer_principal_id"`
	Status               RequestStatus      `json:"status"`
	ReviewedAt           pgtype.Timestamptz `json:"reviewed_at"`
	ExecutedAt           pgtype.Timestamptz `json:"executed_at"`
	CanceledAt           pgtype.Timestamptz `json:"canceled_at"`
	ExecutionError       *string            `json:"execution_error"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateRequest(ctx context.Context, arg CreateRequestParams) (CreateRequestRow, error) {
	row := q.db.QueryRow(ctx, createRequest, arg.Family, arg.Kind, arg.RequesterPrincipalID)
	var i CreateRequestRow
	err := row.Scan(
		&i.ID,
		&i.Family,
		&i.Kind,
		&i.RequesterPrincipalID,
		&i.ReviewerPrincipalID,
		&i.Status,
		&i.ReviewedAt,
		&i.ExecutedAt,
		&i.CanceledAt,
		&i.ExecutionError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRequestEvent = `-- name: CreateRequestEvent :one
INSERT INTO request_events (
    request_id,
    event_kind,
    actor_principal_id,
    from_status,
    to_status,
    error_message
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING
    id,
    request_id,
    event_kind,
    actor_principal_id,
    from_status,
    to_status,
    error_message,
    created_at
`

type CreateRequestEventParams struct {
	RequestID        uuid.UUID         `json:"request_id"`
	EventKind        RequestEventKind  `json:"event_kind"`
	ActorPrincipalID *uuid.UUID        `json:"actor_principal_id"`
	FromStatus       NullRequestStatus `json:"from_status"`
	ToStatus         RequestStatus     `json:"to_status"`
	ErrorMessage     *string           `json:"error_message"`
}

func (q *Queries) CreateRequestEvent(ctx context.Context, arg CreateRequestEventParams) (RequestEvents, error) {
	row := q.db.QueryRow(ctx, createRequestEvent,
		arg.RequestID,
		arg.EventKind,
		arg.ActorPrincipalID,
		arg.FromStatus,
		arg.ToStatus,
		arg.ErrorMessage,
	)
	var i RequestEvents
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.EventKind,
		&i.ActorPrincipalID,
		&i.FromStatus,
		&i.ToStatus,
		&i.ErrorMessage,
		&i.CreatedAt,
	)
	return i, err
}

const getPendingRequestByRequesterAndKind = `-- name: GetPendingRequestByRequesterAndKind :one
SELECT id
FROM requests
WHERE requester_principal_id = $1
  AND kind = $2
  AND status = 'pending'
LIMIT 1
`

type GetPendingRequestByRequesterAndKindParams struct {
	RequesterPrincipalID uuid.UUID `json:"requester_principal_id"`
	Kind                 string    `json:"kind"`
}

func (q *Queries) GetPendingRequestByRequesterAndKind(ctx context.Context, arg GetPendingRequestByRequesterAndKindParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getPendingRequestByRequesterAndKind, arg.RequesterPrincipalID, arg.Kind)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const lockRequestRequester = `-- name: LockRequestRequester :one

SELECT id
FROM principals
WHERE id = $1
FOR UPDATE
`

// ---------------------------------------------------------------------------
// Request creation
// ---------------------------------------------------------------------------
func (q *Queries) LockRequestRequester(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, lockRequestRequester, id)
	err := row.Scan(&id)
	return id, err
}
