// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: requests.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const approveRequest = `-- name: ApproveRequest :one

UPDATE requests
SET
    status = 'executing',
    reviewer_principal_id = $2,
    reviewed_at = now(),
    execution_started_at = now(),
    canceled_at = NULL,
    execution_error = NULL
WHERE id = $1
  AND status = 'pending'
RETURNING
    id,
    family,
    kind,
    requester_principal_id,
    reviewer_principal_id,
    status,
    reviewed_at,
    execution_started_at,
    executed_at,
    canceled_at,
    execution_error,
    created_at,
    updated_at
`

type ApproveRequestParams struct {
	ID                  uuid.UUID  `json:"id"`
	ReviewerPrincipalID *uuid.UUID `json:"reviewer_principal_id"`
}

// ---------------------------------------------------------------------------
// Request status updates
// ---------------------------------------------------------------------------
func (q *Queries) ApproveRequest(ctx context.Context, arg ApproveRequestParams) (Requests, error) {
	row := q.db.QueryRow(ctx, approveRequest, arg.ID, arg.ReviewerPrincipalID)
	var i Requests
	err := row.Scan(
		&i.ID,
		&i.Family,
		&i.Kind,
		&i.RequesterPrincipalID,
		&i.ReviewerPrincipalID,
		&i.Status,
		&i.ReviewedAt,
		&i.ExecutionStartedAt,
		&i.ExecutedAt,
		&i.CanceledAt,
		&i.ExecutionError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const cancelRequest = `-- name: CancelRequest :one
UPDATE requests
SET
    status = 'canceled',
    canceled_at = now()
WHERE id = $1
  AND status = 'pending'
RETURNING
    id,
    family,
    kind,
    requester_principal_id,
    reviewer_principal_id,
    status,
    reviewed_at,
    executed_at,
    canceled_at,
    execution_error,
    created_at,
    updated_at
`

type CancelRequestRow struct {
	ID                   uuid.UUID          `json:"id"`
	Family               RequestFamily      `json:"family"`
	Kind                 string             `json:"kind"`
	RequesterPrincipalID uuid.UUID          `json:"requester_principal_id"`
	ReviewerPrincipalID  *uuid.UUID         `json:"reviewer_principal_id"`
	Status               RequestStatus      `json:"status"`
	ReviewedAt           pgtype.Timestamptz `json:"reviewed_at"`
	ExecutedAt           pgtype.Timestamptz `json:"executed_at"`
	CanceledAt           pgtype.Timestamptz `json:"canceled_at"`
	ExecutionError       *string            `json:"execution_error"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CancelRequest(ctx context.Context, id uuid.UUID) (CancelRequestRow, error) {
	row := q.db.QueryRow(ctx, cancelRequest, id)
	var i CancelRequestRow
	err := row.Scan(
		&i.ID,
		&i.Family,
		&i.Kind,
		&i.RequesterPrincipalID,
		&i.ReviewerPrincipalID,
		&i.Status,
		&i.ReviewedAt,
		&i.ExecutedAt,
		&i.CanceledAt,
		&i.ExecutionError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countPendingRequestsByRequester = `-- name: CountPendingRequestsByRequester :one
SELECT count(*)::int
FROM requests
WHERE requester_principal_id = $1
  AND status = 'pending'
`

func (q *Queries) CountPendingRequestsByRequester(ctx context.Context, requesterPrincipalID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countPendingRequestsByRequester, requesterPrincipalID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createInventoryRequest = `-- name: CreateInventoryRequest :one
INSERT INTO inventory_requests (
    request_id,
    inventory_item_id,
    power_action,
    snapshot_name
) VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING
    request_id,
    inventory_item_id,
    power_action,
    snapshot_name,
    created_at
`

type CreateInventoryRequestParams struct {
	RequestID       uuid.UUID                       `json:"request_id"`
	InventoryItemID uuid.UUID                       `json:"inventory_item_id"`
	PowerAction     NullInventoryRequestPowerAction `json:"power_action"`
	SnapshotName    *string                         `json:"snapshot_name"`
}

func (q *Queries) CreateInventoryRequest(ctx context.Context, arg CreateInventoryRequestParams) (InventoryRequests, error) {
	row := q.db.QueryRow(ctx, createInventoryRequest,
		arg.RequestID,
		arg.InventoryItemID,
		arg.PowerAction,
		arg.SnapshotName,
	)
	var i InventoryRequests
	err := row.Scan(
		&i.RequestID,
		&i.InventoryItemID,
		&i.PowerAction,
		&i.SnapshotName,
		&i.CreatedAt,
	)
	return i, err
}

const createRequest = `-- name: CreateRequest :one
INSERT INTO requests (
    family,
    kind,
    requester_principal_id
) VALUES (
    $1,
    $2,
    $3
)
RETURNING
    id,
    family,
    kind,
    requester_principal_id,
    reviewer_principal_id,
    status,
    reviewed_at,
    executed_at,
    canceled_at,
    execution_error,
    created_at,
    updated_at
`

type CreateRequestParams struct {
	Family               RequestFamily `json:"family"`
	Kind                 string        `json:"kind"`
	RequesterPrincipalID uuid.UUID     `json:"requester_principal_id"`
}

type CreateRequestRow struct {
	ID                   uuid.UUID          `json:"id"`
	Family               RequestFamily      `json:"family"`
	Kind                 string             `json:"kind"`
	RequesterPrincipalID uuid.UUID          `json:"requester_principal_id"`
	ReviewerPrincipalID  *uuid.UUID         `json:"reviewer_principal_id"`
	Status               RequestStatus      `json:"status"`
	ReviewedAt           pgtype.Timestamptz `json:"reviewed_at"`
	ExecutedAt           pgtype.Timestamptz `json:"executed_at"`
	CanceledAt           pgtype.Timestamptz `json:"canceled_at"`
	ExecutionError       *string            `json:"execution_error"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateRequest(ctx context.Context, arg CreateRequestParams) (CreateRequestRow, error) {
	row := q.db.QueryRow(ctx, createRequest, arg.Family, arg.Kind, arg.RequesterPrincipalID)
	var i CreateRequestRow
	err := row.Scan(
		&i.ID,
		&i.Family,
		&i.Kind,
		&i.RequesterPrincipalID,
		&i.ReviewerPrincipalID,
		&i.Status,
		&i.ReviewedAt,
		&i.ExecutedAt,
		&i.CanceledAt,
		&i.ExecutionError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRequestEvent = `-- name: CreateRequestEvent :one
INSERT INTO request_events (
    request_id,
    event_kind,
    actor_principal_id,
    from_status,
    to_status,
    error_message
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING
    id,
    request_id,
    event_kind,
    actor_principal_id,
    from_status,
    to_status,
    error_message,
    created_at
`

type CreateRequestEventParams struct {
	RequestID        uuid.UUID         `json:"request_id"`
	EventKind        RequestEventKind  `json:"event_kind"`
	ActorPrincipalID *uuid.UUID        `json:"actor_principal_id"`
	FromStatus       NullRequestStatus `json:"from_status"`
	ToStatus         RequestStatus     `json:"to_status"`
	ErrorMessage     *string           `json:"error_message"`
}

func (q *Queries) CreateRequestEvent(ctx context.Context, arg CreateRequestEventParams) (RequestEvents, error) {
	row := q.db.QueryRow(ctx, createRequestEvent,
		arg.RequestID,
		arg.EventKind,
		arg.ActorPrincipalID,
		arg.FromStatus,
		arg.ToStatus,
		arg.ErrorMessage,
	)
	var i RequestEvents
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.EventKind,
		&i.ActorPrincipalID,
		&i.FromStatus,
		&i.ToStatus,
		&i.ErrorMessage,
		&i.CreatedAt,
	)
	return i, err
}

const denyRequest = `-- name: DenyRequest :one
UPDATE requests
SET
    status = 'denied',
    reviewer_principal_id = $2,
    reviewed_at = now(),
    canceled_at = NULL
WHERE id = $1
  AND status = 'pending'
RETURNING
    id,
    family,
    kind,
    requester_principal_id,
    reviewer_principal_id,
    status,
    reviewed_at,
    executed_at,
    canceled_at,
    execution_error,
    created_at,
    updated_at
`

type DenyRequestParams struct {
	ID                  uuid.UUID  `json:"id"`
	ReviewerPrincipalID *uuid.UUID `json:"reviewer_principal_id"`
}

type DenyRequestRow struct {
	ID                   uuid.UUID          `json:"id"`
	Family               RequestFamily      `json:"family"`
	Kind                 string             `json:"kind"`
	RequesterPrincipalID uuid.UUID          `json:"requester_principal_id"`
	ReviewerPrincipalID  *uuid.UUID         `json:"reviewer_principal_id"`
	Status               RequestStatus      `json:"status"`
	ReviewedAt           pgtype.Timestamptz `json:"reviewed_at"`
	ExecutedAt           pgtype.Timestamptz `json:"executed_at"`
	CanceledAt           pgtype.Timestamptz `json:"canceled_at"`
	ExecutionError       *string            `json:"execution_error"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) DenyRequest(ctx context.Context, arg DenyRequestParams) (DenyRequestRow, error) {
	row := q.db.QueryRow(ctx, denyRequest, arg.ID, arg.ReviewerPrincipalID)
	var i DenyRequestRow
	err := row.Scan(
		&i.ID,
		&i.Family,
		&i.Kind,
		&i.RequesterPrincipalID,
		&i.ReviewerPrincipalID,
		&i.Status,
		&i.ReviewedAt,
		&i.ExecutedAt,
		&i.CanceledAt,
		&i.ExecutionError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInventoryRequestByRequestID = `-- name: GetInventoryRequestByRequestID :one
SELECT
    ir.request_id,
    ir.inventory_item_id,
    ir.power_action,
    ir.snapshot_name,
    ir.created_at,
    ii.kind AS inventory_item_kind,
    ii.name AS inventory_item_name,
    ii.parent_id AS inventory_item_parent_id,
    pv.node AS inventory_vm_node,
    pv.vmid AS inventory_vm_vmid,
    pv.is_template AS inventory_vm_is_template
FROM inventory_requests ir
JOIN inventory_items ii
  ON ii.id = ir.inventory_item_id
LEFT JOIN proxmox_vms pv
  ON pv.inventory_item_id = ir.inventory_item_id
WHERE ir.request_id = $1
`

type GetInventoryRequestByRequestIDRow struct {
	RequestID             uuid.UUID                       `json:"request_id"`
	InventoryItemID       uuid.UUID                       `json:"inventory_item_id"`
	PowerAction           NullInventoryRequestPowerAction `json:"power_action"`
	SnapshotName          *string                         `json:"snapshot_name"`
	CreatedAt             pgtype.Timestamptz              `json:"created_at"`
	InventoryItemKind     InventoryItemKind               `json:"inventory_item_kind"`
	InventoryItemName     string                          `json:"inventory_item_name"`
	InventoryItemParentID *uuid.UUID                      `json:"inventory_item_parent_id"`
	InventoryVmNode       *string                         `json:"inventory_vm_node"`
	InventoryVmVmid       *int32                          `json:"inventory_vm_vmid"`
	InventoryVmIsTemplate *bool                           `json:"inventory_vm_is_template"`
}

func (q *Queries) GetInventoryRequestByRequestID(ctx context.Context, requestID uuid.UUID) (GetInventoryRequestByRequestIDRow, error) {
	row := q.db.QueryRow(ctx, getInventoryRequestByRequestID, requestID)
	var i GetInventoryRequestByRequestIDRow
	err := row.Scan(
		&i.RequestID,
		&i.InventoryItemID,
		&i.PowerAction,
		&i.SnapshotName,
		&i.CreatedAt,
		&i.InventoryItemKind,
		&i.InventoryItemName,
		&i.InventoryItemParentID,
		&i.InventoryVmNode,
		&i.InventoryVmVmid,
		&i.InventoryVmIsTemplate,
	)
	return i, err
}

const getRequestByID = `-- name: GetRequestByID :one
SELECT
    r.id,
    r.family,
    r.kind,
    r.requester_principal_id,
    r.reviewer_principal_id,
    r.status,
    r.reviewed_at,
    r.executed_at,
    r.canceled_at,
    r.execution_error,
    r.created_at,
    r.updated_at,
    COALESCE(requester.name, requester.external_id) AS requester_username,
    COALESCE(reviewer.name, reviewer.external_id, '') AS reviewer_username,
    ir.inventory_item_id,
    ir.power_action,
    ir.snapshot_name,
    ii.kind AS inventory_item_kind,
    ii.name AS inventory_item_name,
    ii.parent_id AS inventory_item_parent_id,
    pv.node AS inventory_vm_node,
    pv.vmid AS inventory_vm_vmid,
    pv.is_template AS inventory_vm_is_template
FROM requests r
JOIN principals requester
  ON requester.id = r.requester_principal_id
LEFT JOIN principals reviewer
  ON reviewer.id = r.reviewer_principal_id
LEFT JOIN inventory_requests ir
  ON ir.request_id = r.id
LEFT JOIN inventory_items ii
  ON ii.id = ir.inventory_item_id
LEFT JOIN proxmox_vms pv
  ON pv.inventory_item_id = ir.inventory_item_id
WHERE r.id = $1
`

type GetRequestByIDRow struct {
	ID                    uuid.UUID                       `json:"id"`
	Family                RequestFamily                   `json:"family"`
	Kind                  string                          `json:"kind"`
	RequesterPrincipalID  uuid.UUID                       `json:"requester_principal_id"`
	ReviewerPrincipalID   *uuid.UUID                      `json:"reviewer_principal_id"`
	Status                RequestStatus                   `json:"status"`
	ReviewedAt            pgtype.Timestamptz              `json:"reviewed_at"`
	ExecutedAt            pgtype.Timestamptz              `json:"executed_at"`
	CanceledAt            pgtype.Timestamptz              `json:"canceled_at"`
	ExecutionError        *string                         `json:"execution_error"`
	CreatedAt             pgtype.Timestamptz              `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz              `json:"updated_at"`
	RequesterUsername     string                          `json:"requester_username"`
	ReviewerUsername      string                          `json:"reviewer_username"`
	InventoryItemID       *uuid.UUID                      `json:"inventory_item_id"`
	PowerAction           NullInventoryRequestPowerAction `json:"power_action"`
	SnapshotName          *string                         `json:"snapshot_name"`
	InventoryItemKind     NullInventoryItemKind           `json:"inventory_item_kind"`
	InventoryItemName     *string                         `json:"inventory_item_name"`
	InventoryItemParentID *uuid.UUID                      `json:"inventory_item_parent_id"`
	InventoryVmNode       *string                         `json:"inventory_vm_node"`
	InventoryVmVmid       *int32                          `json:"inventory_vm_vmid"`
	InventoryVmIsTemplate *bool                           `json:"inventory_vm_is_template"`
}

func (q *Queries) GetRequestByID(ctx context.Context, id uuid.UUID) (GetRequestByIDRow, error) {
	row := q.db.QueryRow(ctx, getRequestByID, id)
	var i GetRequestByIDRow
	err := row.Scan(
		&i.ID,
		&i.Family,
		&i.Kind,
		&i.RequesterPrincipalID,
		&i.ReviewerPrincipalID,
		&i.Status,
		&i.ReviewedAt,
		&i.ExecutedAt,
		&i.CanceledAt,
		&i.ExecutionError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RequesterUsername,
		&i.ReviewerUsername,
		&i.InventoryItemID,
		&i.PowerAction,
		&i.SnapshotName,
		&i.InventoryItemKind,
		&i.InventoryItemName,
		&i.InventoryItemParentID,
		&i.InventoryVmNode,
		&i.InventoryVmVmid,
		&i.InventoryVmIsTemplate,
	)
	return i, err
}

const getRequestForExecution = `-- name: GetRequestForExecution :one
SELECT
    r.id,
    r.family,
    r.kind,
    r.requester_principal_id,
    r.reviewer_principal_id,
    r.status,
    r.reviewed_at,
    r.executed_at,
    r.canceled_at,
    r.execution_error,
    r.created_at,
    r.updated_at,
    COALESCE(requester.name, requester.external_id) AS requester_username,
    COALESCE(reviewer.name, reviewer.external_id, '') AS reviewer_username,
    ir.inventory_item_id,
    ir.power_action,
    ir.snapshot_name,
    ii.kind AS inventory_item_kind,
    ii.name AS inventory_item_name,
    ii.parent_id AS inventory_item_parent_id,
    pv.node AS inventory_vm_node,
    pv.vmid AS inventory_vm_vmid,
    pv.is_template AS inventory_vm_is_template
FROM requests r
JOIN principals requester
  ON requester.id = r.requester_principal_id
LEFT JOIN principals reviewer
  ON reviewer.id = r.reviewer_principal_id
LEFT JOIN inventory_requests ir
  ON ir.request_id = r.id
LEFT JOIN inventory_items ii
  ON ii.id = ir.inventory_item_id
LEFT JOIN proxmox_vms pv
  ON pv.inventory_item_id = ir.inventory_item_id
WHERE r.id = $1
FOR UPDATE OF r
`

type GetRequestForExecutionRow struct {
	ID                    uuid.UUID                       `json:"id"`
	Family                RequestFamily                   `json:"family"`
	Kind                  string                          `json:"kind"`
	RequesterPrincipalID  uuid.UUID                       `json:"requester_principal_id"`
	ReviewerPrincipalID   *uuid.UUID                      `json:"reviewer_principal_id"`
	Status                RequestStatus                   `json:"status"`
	ReviewedAt            pgtype.Timestamptz              `json:"reviewed_at"`
	ExecutedAt            pgtype.Timestamptz              `json:"executed_at"`
	CanceledAt            pgtype.Timestamptz              `json:"canceled_at"`
	ExecutionError        *string                         `json:"execution_error"`
	CreatedAt             pgtype.Timestamptz              `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz              `json:"updated_at"`
	RequesterUsername     string                          `json:"requester_username"`
	ReviewerUsername      string                          `json:"reviewer_username"`
	InventoryItemID       *uuid.UUID                      `json:"inventory_item_id"`
	PowerAction           NullInventoryRequestPowerAction `json:"power_action"`
	SnapshotName          *string                         `json:"snapshot_name"`
	InventoryItemKind     NullInventoryItemKind           `json:"inventory_item_kind"`
	InventoryItemName     *string                         `json:"inventory_item_name"`
	InventoryItemParentID *uuid.UUID                      `json:"inventory_item_parent_id"`
	InventoryVmNode       *string                         `json:"inventory_vm_node"`
	InventoryVmVmid       *int32                          `json:"inventory_vm_vmid"`
	InventoryVmIsTemplate *bool                           `json:"inventory_vm_is_template"`
}

func (q *Queries) GetRequestForExecution(ctx context.Context, id uuid.UUID) (GetRequestForExecutionRow, error) {
	row := q.db.QueryRow(ctx, getRequestForExecution, id)
	var i GetRequestForExecutionRow
	err := row.Scan(
		&i.ID,
		&i.Family,
		&i.Kind,
		&i.RequesterPrincipalID,
		&i.ReviewerPrincipalID,
		&i.Status,
		&i.ReviewedAt,
		&i.ExecutedAt,
		&i.CanceledAt,
		&i.ExecutionError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RequesterUsername,
		&i.ReviewerUsername,
		&i.InventoryItemID,
		&i.PowerAction,
		&i.SnapshotName,
		&i.InventoryItemKind,
		&i.InventoryItemName,
		&i.InventoryItemParentID,
		&i.InventoryVmNode,
		&i.InventoryVmVmid,
		&i.InventoryVmIsTemplate,
	)
	return i, err
}

const listCompletedRequests = `-- name: ListCompletedRequests :many
SELECT
    r.id,
    r.family,
    r.kind,
    r.requester_principal_id,
    r.reviewer_principal_id,
    r.status,
    r.reviewed_at,
    r.executed_at,
    r.canceled_at,
    r.execution_error,
    r.created_at,
    r.updated_at,
    COALESCE(requester.name, requester.external_id) AS requester_username,
    COALESCE(reviewer.name, reviewer.external_id, '') AS reviewer_username,
    ir.inventory_item_id,
    ir.power_action,
    ir.snapshot_name,
    ii.kind AS inventory_item_kind,
    ii.name AS inventory_item_name,
    ii.parent_id AS inventory_item_parent_id,
    pv.node AS inventory_vm_node,
    pv.vmid AS inventory_vm_vmid,
    pv.is_template AS inventory_vm_is_template
FROM requests r
JOIN principals requester
  ON requester.id = r.requester_principal_id
LEFT JOIN principals reviewer
  ON reviewer.id = r.reviewer_principal_id
LEFT JOIN inventory_requests ir
  ON ir.request_id = r.id
LEFT JOIN inventory_items ii
  ON ii.id = ir.inventory_item_id
LEFT JOIN proxmox_vms pv
  ON pv.inventory_item_id = ir.inventory_item_id
WHERE r.status IN ('approved', 'executing', 'denied', 'executed', 'execution_failed')
ORDER BY r.updated_at DESC, r.created_at DESC, r.id DESC
`

type ListCompletedRequestsRow struct {
	ID                    uuid.UUID                       `json:"id"`
	Family                RequestFamily                   `json:"family"`
	Kind                  string                          `json:"kind"`
	RequesterPrincipalID  uuid.UUID                       `json:"requester_principal_id"`
	ReviewerPrincipalID   *uuid.UUID                      `json:"reviewer_principal_id"`
	Status                RequestStatus                   `json:"status"`
	ReviewedAt            pgtype.Timestamptz              `json:"reviewed_at"`
	ExecutedAt            pgtype.Timestamptz              `json:"executed_at"`
	CanceledAt            pgtype.Timestamptz              `json:"canceled_at"`
	ExecutionError        *string                         `json:"execution_error"`
	CreatedAt             pgtype.Timestamptz              `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz              `json:"updated_at"`
	RequesterUsername     string                          `json:"requester_username"`
	ReviewerUsername      string                          `json:"reviewer_username"`
	InventoryItemID       *uuid.UUID                      `json:"inventory_item_id"`
	PowerAction           NullInventoryRequestPowerAction `json:"power_action"`
	SnapshotName          *string                         `json:"snapshot_name"`
	InventoryItemKind     NullInventoryItemKind           `json:"inventory_item_kind"`
	InventoryItemName     *string                         `json:"inventory_item_name"`
	InventoryItemParentID *uuid.UUID                      `json:"inventory_item_parent_id"`
	InventoryVmNode       *string                         `json:"inventory_vm_node"`
	InventoryVmVmid       *int32                          `json:"inventory_vm_vmid"`
	InventoryVmIsTemplate *bool                           `json:"inventory_vm_is_template"`
}

func (q *Queries) ListCompletedRequests(ctx context.Context) ([]ListCompletedRequestsRow, error) {
	rows, err := q.db.Query(ctx, listCompletedRequests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCompletedRequestsRow
	for rows.Next() {
		var i ListCompletedRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.Family,
			&i.Kind,
			&i.RequesterPrincipalID,
			&i.ReviewerPrincipalID,
			&i.Status,
			&i.ReviewedAt,
			&i.ExecutedAt,
			&i.CanceledAt,
			&i.ExecutionError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RequesterUsername,
			&i.ReviewerUsername,
			&i.InventoryItemID,
			&i.PowerAction,
			&i.SnapshotName,
			&i.InventoryItemKind,
			&i.InventoryItemName,
			&i.InventoryItemParentID,
			&i.InventoryVmNode,
			&i.InventoryVmVmid,
			&i.InventoryVmIsTemplate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingRequests = `-- name: ListPendingRequests :many

SELECT
    r.id,
    r.family,
    r.kind,
    r.requester_principal_id,
    r.reviewer_principal_id,
    r.status,
    r.reviewed_at,
    r.executed_at,
    r.canceled_at,
    r.execution_error,
    r.created_at,
    r.updated_at,
    COALESCE(requester.name, requester.external_id) AS requester_username,
    COALESCE(reviewer.name, reviewer.external_id, '') AS reviewer_username,
    ir.inventory_item_id,
    ir.power_action,
    ir.snapshot_name,
    ii.kind AS inventory_item_kind,
    ii.name AS inventory_item_name,
    ii.parent_id AS inventory_item_parent_id,
    pv.node AS inventory_vm_node,
    pv.vmid AS inventory_vm_vmid,
    pv.is_template AS inventory_vm_is_template
FROM requests r
JOIN principals requester
  ON requester.id = r.requester_principal_id
LEFT JOIN principals reviewer
  ON reviewer.id = r.reviewer_principal_id
LEFT JOIN inventory_requests ir
  ON ir.request_id = r.id
LEFT JOIN inventory_items ii
  ON ii.id = ir.inventory_item_id
LEFT JOIN proxmox_vms pv
  ON pv.inventory_item_id = ir.inventory_item_id
WHERE r.status = 'pending'
ORDER BY r.created_at ASC, r.id ASC
`

type ListPendingRequestsRow struct {
	ID                    uuid.UUID                       `json:"id"`
	Family                RequestFamily                   `json:"family"`
	Kind                  string                          `json:"kind"`
	RequesterPrincipalID  uuid.UUID                       `json:"requester_principal_id"`
	ReviewerPrincipalID   *uuid.UUID                      `json:"reviewer_principal_id"`
	Status                RequestStatus                   `json:"status"`
	ReviewedAt            pgtype.Timestamptz              `json:"reviewed_at"`
	ExecutedAt            pgtype.Timestamptz              `json:"executed_at"`
	CanceledAt            pgtype.Timestamptz              `json:"canceled_at"`
	ExecutionError        *string                         `json:"execution_error"`
	CreatedAt             pgtype.Timestamptz              `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz              `json:"updated_at"`
	RequesterUsername     string                          `json:"requester_username"`
	ReviewerUsername      string                          `json:"reviewer_username"`
	InventoryItemID       *uuid.UUID                      `json:"inventory_item_id"`
	PowerAction           NullInventoryRequestPowerAction `json:"power_action"`
	SnapshotName          *string                         `json:"snapshot_name"`
	InventoryItemKind     NullInventoryItemKind           `json:"inventory_item_kind"`
	InventoryItemName     *string                         `json:"inventory_item_name"`
	InventoryItemParentID *uuid.UUID                      `json:"inventory_item_parent_id"`
	InventoryVmNode       *string                         `json:"inventory_vm_node"`
	InventoryVmVmid       *int32                          `json:"inventory_vm_vmid"`
	InventoryVmIsTemplate *bool                           `json:"inventory_vm_is_template"`
}

// ---------------------------------------------------------------------------
// Request reads
// ---------------------------------------------------------------------------
func (q *Queries) ListPendingRequests(ctx context.Context) ([]ListPendingRequestsRow, error) {
	rows, err := q.db.Query(ctx, listPendingRequests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingRequestsRow
	for rows.Next() {
		var i ListPendingRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.Family,
			&i.Kind,
			&i.RequesterPrincipalID,
			&i.ReviewerPrincipalID,
			&i.Status,
			&i.ReviewedAt,
			&i.ExecutedAt,
			&i.CanceledAt,
			&i.ExecutionError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RequesterUsername,
			&i.ReviewerUsername,
			&i.InventoryItemID,
			&i.PowerAction,
			&i.SnapshotName,
			&i.InventoryItemKind,
			&i.InventoryItemName,
			&i.InventoryItemParentID,
			&i.InventoryVmNode,
			&i.InventoryVmVmid,
			&i.InventoryVmIsTemplate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingRequestsByRequester = `-- name: ListPendingRequestsByRequester :many
SELECT
    r.id,
    r.family,
    r.kind,
    r.requester_principal_id,
    r.reviewer_principal_id,
    r.status,
    r.reviewed_at,
    r.executed_at,
    r.canceled_at,
    r.execution_error,
    r.created_at,
    r.updated_at,
    COALESCE(requester.name, requester.external_id) AS requester_username,
    COALESCE(reviewer.name, reviewer.external_id, '') AS reviewer_username,
    ir.inventory_item_id,
    ir.power_action,
    ir.snapshot_name,
    ii.kind AS inventory_item_kind,
    ii.name AS inventory_item_name,
    ii.parent_id AS inventory_item_parent_id,
    pv.node AS inventory_vm_node,
    pv.vmid AS inventory_vm_vmid,
    pv.is_template AS inventory_vm_is_template
FROM requests r
JOIN principals requester
  ON requester.id = r.requester_principal_id
LEFT JOIN principals reviewer
  ON reviewer.id = r.reviewer_principal_id
LEFT JOIN inventory_requests ir
  ON ir.request_id = r.id
LEFT JOIN inventory_items ii
  ON ii.id = ir.inventory_item_id
LEFT JOIN proxmox_vms pv
  ON pv.inventory_item_id = ir.inventory_item_id
WHERE r.requester_principal_id = $1
  AND r.status = 'pending'
ORDER BY r.created_at DESC, r.id DESC
`

type ListPendingRequestsByRequesterRow struct {
	ID                    uuid.UUID                       `json:"id"`
	Family                RequestFamily                   `json:"family"`
	Kind                  string                          `json:"kind"`
	RequesterPrincipalID  uuid.UUID                       `json:"requester_principal_id"`
	ReviewerPrincipalID   *uuid.UUID                      `json:"reviewer_principal_id"`
	Status                RequestStatus                   `json:"status"`
	ReviewedAt            pgtype.Timestamptz              `json:"reviewed_at"`
	ExecutedAt            pgtype.Timestamptz              `json:"executed_at"`
	CanceledAt            pgtype.Timestamptz              `json:"canceled_at"`
	ExecutionError        *string                         `json:"execution_error"`
	CreatedAt             pgtype.Timestamptz              `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz              `json:"updated_at"`
	RequesterUsername     string                          `json:"requester_username"`
	ReviewerUsername      string                          `json:"reviewer_username"`
	InventoryItemID       *uuid.UUID                      `json:"inventory_item_id"`
	PowerAction           NullInventoryRequestPowerAction `json:"power_action"`
	SnapshotName          *string                         `json:"snapshot_name"`
	InventoryItemKind     NullInventoryItemKind           `json:"inventory_item_kind"`
	InventoryItemName     *string                         `json:"inventory_item_name"`
	InventoryItemParentID *uuid.UUID                      `json:"inventory_item_parent_id"`
	InventoryVmNode       *string                         `json:"inventory_vm_node"`
	InventoryVmVmid       *int32                          `json:"inventory_vm_vmid"`
	InventoryVmIsTemplate *bool                           `json:"inventory_vm_is_template"`
}

func (q *Queries) ListPendingRequestsByRequester(ctx context.Context, requesterPrincipalID uuid.UUID) ([]ListPendingRequestsByRequesterRow, error) {
	rows, err := q.db.Query(ctx, listPendingRequestsByRequester, requesterPrincipalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingRequestsByRequesterRow
	for rows.Next() {
		var i ListPendingRequestsByRequesterRow
		if err := rows.Scan(
			&i.ID,
			&i.Family,
			&i.Kind,
			&i.RequesterPrincipalID,
			&i.ReviewerPrincipalID,
			&i.Status,
			&i.ReviewedAt,
			&i.ExecutedAt,
			&i.CanceledAt,
			&i.ExecutionError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RequesterUsername,
			&i.ReviewerUsername,
			&i.InventoryItemID,
			&i.PowerAction,
			&i.SnapshotName,
			&i.InventoryItemKind,
			&i.InventoryItemName,
			&i.InventoryItemParentID,
			&i.InventoryVmNode,
			&i.InventoryVmVmid,
			&i.InventoryVmIsTemplate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequestEventsByRequestID = `-- name: ListRequestEventsByRequestID :many
SELECT
    re.id,
    re.request_id,
    re.event_kind,
    re.actor_principal_id,
    re.from_status,
    re.to_status,
    re.error_message,
    re.created_at,
    COALESCE(actor.name, actor.external_id, '') AS actor_username
FROM request_events re
LEFT JOIN principals actor
  ON actor.id = re.actor_principal_id
WHERE re.request_id = $1
ORDER BY re.created_at ASC, re.id ASC
`

type ListRequestEventsByRequestIDRow struct {
	ID               int64              `json:"id"`
	RequestID        uuid.UUID          `json:"request_id"`
	EventKind        RequestEventKind   `json:"event_kind"`
	ActorPrincipalID *uuid.UUID         `json:"actor_principal_id"`
	FromStatus       NullRequestStatus  `json:"from_status"`
	ToStatus         RequestStatus      `json:"to_status"`
	ErrorMessage     *string            `json:"error_message"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	ActorUsername    string             `json:"actor_username"`
}

func (q *Queries) ListRequestEventsByRequestID(ctx context.Context, requestID uuid.UUID) ([]ListRequestEventsByRequestIDRow, error) {
	rows, err := q.db.Query(ctx, listRequestEventsByRequestID, requestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRequestEventsByRequestIDRow
	for rows.Next() {
		var i ListRequestEventsByRequestIDRow
		if err := rows.Scan(
			&i.ID,
			&i.RequestID,
			&i.EventKind,
			&i.ActorPrincipalID,
			&i.FromStatus,
			&i.ToStatus,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.ActorUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequestHistoryByRequester = `-- name: ListRequestHistoryByRequester :many
SELECT
    r.id,
    r.family,
    r.kind,
    r.requester_principal_id,
    r.reviewer_principal_id,
    r.status,
    r.reviewed_at,
    r.executed_at,
    r.canceled_at,
    r.execution_error,
    r.created_at,
    r.updated_at,
    COALESCE(requester.name, requester.external_id) AS requester_username,
    COALESCE(reviewer.name, reviewer.external_id, '') AS reviewer_username,
    ir.inventory_item_id,
    ir.power_action,
    ir.snapshot_name,
    ii.kind AS inventory_item_kind,
    ii.name AS inventory_item_name,
    ii.parent_id AS inventory_item_parent_id,
    pv.node AS inventory_vm_node,
    pv.vmid AS inventory_vm_vmid,
    pv.is_template AS inventory_vm_is_template
FROM requests r
JOIN principals requester
  ON requester.id = r.requester_principal_id
LEFT JOIN principals reviewer
  ON reviewer.id = r.reviewer_principal_id
LEFT JOIN inventory_requests ir
  ON ir.request_id = r.id
LEFT JOIN inventory_items ii
  ON ii.id = ir.inventory_item_id
LEFT JOIN proxmox_vms pv
  ON pv.inventory_item_id = ir.inventory_item_id
WHERE r.requester_principal_id = $1
  AND r.status IN ('approved', 'executing', 'denied', 'executed', 'execution_failed')
ORDER BY r.updated_at DESC, r.created_at DESC, r.id DESC
`

type ListRequestHistoryByRequesterRow struct {
	ID                    uuid.UUID                       `json:"id"`
	Family                RequestFamily                   `json:"family"`
	Kind                  string                          `json:"kind"`
	RequesterPrincipalID  uuid.UUID                       `json:"requester_principal_id"`
	ReviewerPrincipalID   *uuid.UUID                      `json:"reviewer_principal_id"`
	Status                RequestStatus                   `json:"status"`
	ReviewedAt            pgtype.Timestamptz              `json:"reviewed_at"`
	ExecutedAt            pgtype.Timestamptz              `json:"executed_at"`
	CanceledAt            pgtype.Timestamptz              `json:"canceled_at"`
	ExecutionError        *string                         `json:"execution_error"`
	CreatedAt             pgtype.Timestamptz              `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz              `json:"updated_at"`
	RequesterUsername     string                          `json:"requester_username"`
	ReviewerUsername      string                          `json:"reviewer_username"`
	InventoryItemID       *uuid.UUID                      `json:"inventory_item_id"`
	PowerAction           NullInventoryRequestPowerAction `json:"power_action"`
	SnapshotName          *string                         `json:"snapshot_name"`
	InventoryItemKind     NullInventoryItemKind           `json:"inventory_item_kind"`
	InventoryItemName     *string                         `json:"inventory_item_name"`
	InventoryItemParentID *uuid.UUID                      `json:"inventory_item_parent_id"`
	InventoryVmNode       *string                         `json:"inventory_vm_node"`
	InventoryVmVmid       *int32                          `json:"inventory_vm_vmid"`
	InventoryVmIsTemplate *bool                           `json:"inventory_vm_is_template"`
}

func (q *Queries) ListRequestHistoryByRequester(ctx context.Context, requesterPrincipalID uuid.UUID) ([]ListRequestHistoryByRequesterRow, error) {
	rows, err := q.db.Query(ctx, listRequestHistoryByRequester, requesterPrincipalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRequestHistoryByRequesterRow
	for rows.Next() {
		var i ListRequestHistoryByRequesterRow
		if err := rows.Scan(
			&i.ID,
			&i.Family,
			&i.Kind,
			&i.RequesterPrincipalID,
			&i.ReviewerPrincipalID,
			&i.Status,
			&i.ReviewedAt,
			&i.ExecutedAt,
			&i.CanceledAt,
			&i.ExecutionError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RequesterUsername,
			&i.ReviewerUsername,
			&i.InventoryItemID,
			&i.PowerAction,
			&i.SnapshotName,
			&i.InventoryItemKind,
			&i.InventoryItemName,
			&i.InventoryItemParentID,
			&i.InventoryVmNode,
			&i.InventoryVmVmid,
			&i.InventoryVmIsTemplate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleExecutingRequests = `-- name: ListStaleExecutingRequests :many
SELECT
    id,
    family,
    kind,
    requester_principal_id,
    reviewer_principal_id,
    status,
    reviewed_at,
    execution_started_at,
    executed_at,
    canceled_at,
    execution_error,
    created_at,
    updated_at
FROM requests
WHERE status = 'executing'
  AND execution_started_at IS NOT NULL
  AND execution_started_at < $1
ORDER BY execution_started_at ASC, id ASC
`

func (q *Queries) ListStaleExecutingRequests(ctx context.Context, executionStartedAt pgtype.Timestamptz) ([]Requests, error) {
	rows, err := q.db.Query(ctx, listStaleExecutingRequests, executionStartedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Requests
	for rows.Next() {
		var i Requests
		if err := rows.Scan(
			&i.ID,
			&i.Family,
			&i.Kind,
			&i.RequesterPrincipalID,
			&i.ReviewerPrincipalID,
			&i.Status,
			&i.ReviewedAt,
			&i.ExecutionStartedAt,
			&i.ExecutedAt,
			&i.CanceledAt,
			&i.ExecutionError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockRequestRequester = `-- name: LockRequestRequester :one

SELECT id
FROM principals
WHERE id = $1
FOR UPDATE
`

// ---------------------------------------------------------------------------
// Request creation
// ---------------------------------------------------------------------------
func (q *Queries) LockRequestRequester(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, lockRequestRequester, id)
	err := row.Scan(&id)
	return id, err
}

const markRequestExecuted = `-- name: MarkRequestExecuted :one
UPDATE requests
SET
    status = 'executed',
    executed_at = now(),
    execution_error = NULL
WHERE id = $1
  AND status = 'executing'
RETURNING
    id,
    family,
    kind,
    requester_principal_id,
    reviewer_principal_id,
    status,
    reviewed_at,
    execution_started_at,
    executed_at,
    canceled_at,
    execution_error,
    created_at,
    updated_at
`

func (q *Queries) MarkRequestExecuted(ctx context.Context, id uuid.UUID) (Requests, error) {
	row := q.db.QueryRow(ctx, markRequestExecuted, id)
	var i Requests
	err := row.Scan(
		&i.ID,
		&i.Family,
		&i.Kind,
		&i.RequesterPrincipalID,
		&i.ReviewerPrincipalID,
		&i.Status,
		&i.ReviewedAt,
		&i.ExecutionStartedAt,
		&i.ExecutedAt,
		&i.CanceledAt,
		&i.ExecutionError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markRequestExecutionFailed = `-- name: MarkRequestExecutionFailed :one
UPDATE requests
SET
    status = 'execution_failed',
    executed_at = now(),
    execution_error = $2
WHERE id = $1
  AND status = 'executing'
RETURNING
    id,
    family,
    kind,
    requester_principal_id,
    reviewer_principal_id,
    status,
    reviewed_at,
    execution_started_at,
    executed_at,
    canceled_at,
    execution_error,
    created_at,
    updated_at
`

type MarkRequestExecutionFailedParams struct {
	ID             uuid.UUID `json:"id"`
	ExecutionError *string   `json:"execution_error"`
}

func (q *Queries) MarkRequestExecutionFailed(ctx context.Context, arg MarkRequestExecutionFailedParams) (Requests, error) {
	row := q.db.QueryRow(ctx, markRequestExecutionFailed, arg.ID, arg.ExecutionError)
	var i Requests
	err := row.Scan(
		&i.ID,
		&i.Family,
		&i.Kind,
		&i.RequesterPrincipalID,
		&i.ReviewerPrincipalID,
		&i.Status,
		&i.ReviewedAt,
		&i.ExecutionStartedAt,
		&i.ExecutedAt,
		&i.CanceledAt,
		&i.ExecutionError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
