// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: requests_detail.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getInventoryRequestByRequestID = `-- name: GetInventoryRequestByRequestID :one
SELECT
    ir.request_id,
    ir.inventory_item_id,
    ir.power_action,
    ir.snapshot_name,
    ir.created_at,
    ii.kind AS inventory_item_kind,
    ii.name AS inventory_item_name,
    ii.parent_id AS inventory_item_parent_id,
    pv.node AS inventory_vm_node,
    pv.vmid AS inventory_vm_vmid,
    pv.is_template AS inventory_vm_is_template
FROM inventory_requests ir
JOIN inventory_items ii
  ON ii.id = ir.inventory_item_id
LEFT JOIN proxmox_vms pv
  ON pv.inventory_item_id = ir.inventory_item_id
WHERE ir.request_id = $1
`

type GetInventoryRequestByRequestIDRow struct {
	RequestID             uuid.UUID                       `json:"request_id"`
	InventoryItemID       uuid.UUID                       `json:"inventory_item_id"`
	PowerAction           NullInventoryRequestPowerAction `json:"power_action"`
	SnapshotName          *string                         `json:"snapshot_name"`
	CreatedAt             pgtype.Timestamptz              `json:"created_at"`
	InventoryItemKind     InventoryItemKind               `json:"inventory_item_kind"`
	InventoryItemName     string                          `json:"inventory_item_name"`
	InventoryItemParentID *uuid.UUID                      `json:"inventory_item_parent_id"`
	InventoryVmNode       *string                         `json:"inventory_vm_node"`
	InventoryVmVmid       *int32                          `json:"inventory_vm_vmid"`
	InventoryVmIsTemplate *bool                           `json:"inventory_vm_is_template"`
}

func (q *Queries) GetInventoryRequestByRequestID(ctx context.Context, requestID uuid.UUID) (GetInventoryRequestByRequestIDRow, error) {
	row := q.db.QueryRow(ctx, getInventoryRequestByRequestID, requestID)
	var i GetInventoryRequestByRequestIDRow
	err := row.Scan(
		&i.RequestID,
		&i.InventoryItemID,
		&i.PowerAction,
		&i.SnapshotName,
		&i.CreatedAt,
		&i.InventoryItemKind,
		&i.InventoryItemName,
		&i.InventoryItemParentID,
		&i.InventoryVmNode,
		&i.InventoryVmVmid,
		&i.InventoryVmIsTemplate,
	)
	return i, err
}

const getRequestByID = `-- name: GetRequestByID :one
SELECT
    r.id,
    r.family,
    r.kind,
    r.requester_principal_id,
    r.reviewer_principal_id,
    r.status,
    r.reviewed_at,
    r.executed_at,
    r.canceled_at,
    r.execution_error,
    r.created_at,
    r.updated_at,
    COALESCE(requester.name, requester.external_id) AS requester_username,
    COALESCE(reviewer.name, reviewer.external_id, '') AS reviewer_username,
    ir.inventory_item_id,
    ir.power_action,
    ir.snapshot_name,
    ii.kind AS inventory_item_kind,
    ii.name AS inventory_item_name,
    ii.parent_id AS inventory_item_parent_id,
    pv.node AS inventory_vm_node,
    pv.vmid AS inventory_vm_vmid,
    pv.is_template AS inventory_vm_is_template
FROM requests r
JOIN principals requester
  ON requester.id = r.requester_principal_id
LEFT JOIN principals reviewer
  ON reviewer.id = r.reviewer_principal_id
LEFT JOIN inventory_requests ir
  ON ir.request_id = r.id
LEFT JOIN inventory_items ii
  ON ii.id = ir.inventory_item_id
LEFT JOIN proxmox_vms pv
  ON pv.inventory_item_id = ir.inventory_item_id
WHERE r.id = $1
`

type GetRequestByIDRow struct {
	ID                    uuid.UUID                       `json:"id"`
	Family                RequestFamily                   `json:"family"`
	Kind                  string                          `json:"kind"`
	RequesterPrincipalID  uuid.UUID                       `json:"requester_principal_id"`
	ReviewerPrincipalID   *uuid.UUID                      `json:"reviewer_principal_id"`
	Status                RequestStatus                   `json:"status"`
	ReviewedAt            pgtype.Timestamptz              `json:"reviewed_at"`
	ExecutedAt            pgtype.Timestamptz              `json:"executed_at"`
	CanceledAt            pgtype.Timestamptz              `json:"canceled_at"`
	ExecutionError        *string                         `json:"execution_error"`
	CreatedAt             pgtype.Timestamptz              `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz              `json:"updated_at"`
	RequesterUsername     string                          `json:"requester_username"`
	ReviewerUsername      string                          `json:"reviewer_username"`
	InventoryItemID       *uuid.UUID                      `json:"inventory_item_id"`
	PowerAction           NullInventoryRequestPowerAction `json:"power_action"`
	SnapshotName          *string                         `json:"snapshot_name"`
	InventoryItemKind     NullInventoryItemKind           `json:"inventory_item_kind"`
	InventoryItemName     *string                         `json:"inventory_item_name"`
	InventoryItemParentID *uuid.UUID                      `json:"inventory_item_parent_id"`
	InventoryVmNode       *string                         `json:"inventory_vm_node"`
	InventoryVmVmid       *int32                          `json:"inventory_vm_vmid"`
	InventoryVmIsTemplate *bool                           `json:"inventory_vm_is_template"`
}

func (q *Queries) GetRequestByID(ctx context.Context, id uuid.UUID) (GetRequestByIDRow, error) {
	row := q.db.QueryRow(ctx, getRequestByID, id)
	var i GetRequestByIDRow
	err := row.Scan(
		&i.ID,
		&i.Family,
		&i.Kind,
		&i.RequesterPrincipalID,
		&i.ReviewerPrincipalID,
		&i.Status,
		&i.ReviewedAt,
		&i.ExecutedAt,
		&i.CanceledAt,
		&i.ExecutionError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RequesterUsername,
		&i.ReviewerUsername,
		&i.InventoryItemID,
		&i.PowerAction,
		&i.SnapshotName,
		&i.InventoryItemKind,
		&i.InventoryItemName,
		&i.InventoryItemParentID,
		&i.InventoryVmNode,
		&i.InventoryVmVmid,
		&i.InventoryVmIsTemplate,
	)
	return i, err
}

const getRequestForExecution = `-- name: GetRequestForExecution :one
SELECT
    r.id,
    r.family,
    r.kind,
    r.requester_principal_id,
    r.reviewer_principal_id,
    r.status,
    r.reviewed_at,
    r.executed_at,
    r.canceled_at,
    r.execution_error,
    r.created_at,
    r.updated_at,
    COALESCE(requester.name, requester.external_id) AS requester_username,
    COALESCE(reviewer.name, reviewer.external_id, '') AS reviewer_username,
    ir.inventory_item_id,
    ir.power_action,
    ir.snapshot_name,
    ii.kind AS inventory_item_kind,
    ii.name AS inventory_item_name,
    ii.parent_id AS inventory_item_parent_id,
    pv.node AS inventory_vm_node,
    pv.vmid AS inventory_vm_vmid,
    pv.is_template AS inventory_vm_is_template
FROM requests r
JOIN principals requester
  ON requester.id = r.requester_principal_id
LEFT JOIN principals reviewer
  ON reviewer.id = r.reviewer_principal_id
LEFT JOIN inventory_requests ir
  ON ir.request_id = r.id
LEFT JOIN inventory_items ii
  ON ii.id = ir.inventory_item_id
LEFT JOIN proxmox_vms pv
  ON pv.inventory_item_id = ir.inventory_item_id
WHERE r.id = $1
FOR UPDATE OF r
`

type GetRequestForExecutionRow struct {
	ID                    uuid.UUID                       `json:"id"`
	Family                RequestFamily                   `json:"family"`
	Kind                  string                          `json:"kind"`
	RequesterPrincipalID  uuid.UUID                       `json:"requester_principal_id"`
	ReviewerPrincipalID   *uuid.UUID                      `json:"reviewer_principal_id"`
	Status                RequestStatus                   `json:"status"`
	ReviewedAt            pgtype.Timestamptz              `json:"reviewed_at"`
	ExecutedAt            pgtype.Timestamptz              `json:"executed_at"`
	CanceledAt            pgtype.Timestamptz              `json:"canceled_at"`
	ExecutionError        *string                         `json:"execution_error"`
	CreatedAt             pgtype.Timestamptz              `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz              `json:"updated_at"`
	RequesterUsername     string                          `json:"requester_username"`
	ReviewerUsername      string                          `json:"reviewer_username"`
	InventoryItemID       *uuid.UUID                      `json:"inventory_item_id"`
	PowerAction           NullInventoryRequestPowerAction `json:"power_action"`
	SnapshotName          *string                         `json:"snapshot_name"`
	InventoryItemKind     NullInventoryItemKind           `json:"inventory_item_kind"`
	InventoryItemName     *string                         `json:"inventory_item_name"`
	InventoryItemParentID *uuid.UUID                      `json:"inventory_item_parent_id"`
	InventoryVmNode       *string                         `json:"inventory_vm_node"`
	InventoryVmVmid       *int32                          `json:"inventory_vm_vmid"`
	InventoryVmIsTemplate *bool                           `json:"inventory_vm_is_template"`
}

func (q *Queries) GetRequestForExecution(ctx context.Context, id uuid.UUID) (GetRequestForExecutionRow, error) {
	row := q.db.QueryRow(ctx, getRequestForExecution, id)
	var i GetRequestForExecutionRow
	err := row.Scan(
		&i.ID,
		&i.Family,
		&i.Kind,
		&i.RequesterPrincipalID,
		&i.ReviewerPrincipalID,
		&i.Status,
		&i.ReviewedAt,
		&i.ExecutedAt,
		&i.CanceledAt,
		&i.ExecutionError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RequesterUsername,
		&i.ReviewerUsername,
		&i.InventoryItemID,
		&i.PowerAction,
		&i.SnapshotName,
		&i.InventoryItemKind,
		&i.InventoryItemName,
		&i.InventoryItemParentID,
		&i.InventoryVmNode,
		&i.InventoryVmVmid,
		&i.InventoryVmIsTemplate,
	)
	return i, err
}

const listRequestEventsByRequestID = `-- name: ListRequestEventsByRequestID :many
SELECT
    re.id,
    re.request_id,
    re.event_kind,
    re.actor_principal_id,
    re.from_status,
    re.to_status,
    re.error_message,
    re.created_at,
    COALESCE(actor.name, actor.external_id, '') AS actor_username
FROM request_events re
LEFT JOIN principals actor
  ON actor.id = re.actor_principal_id
WHERE re.request_id = $1
ORDER BY re.created_at ASC, re.id ASC
`

type ListRequestEventsByRequestIDRow struct {
	ID               int64              `json:"id"`
	RequestID        uuid.UUID          `json:"request_id"`
	EventKind        RequestEventKind   `json:"event_kind"`
	ActorPrincipalID *uuid.UUID         `json:"actor_principal_id"`
	FromStatus       NullRequestStatus  `json:"from_status"`
	ToStatus         RequestStatus      `json:"to_status"`
	ErrorMessage     *string            `json:"error_message"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	ActorUsername    string             `json:"actor_username"`
}

func (q *Queries) ListRequestEventsByRequestID(ctx context.Context, requestID uuid.UUID) ([]ListRequestEventsByRequestIDRow, error) {
	rows, err := q.db.Query(ctx, listRequestEventsByRequestID, requestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRequestEventsByRequestIDRow
	for rows.Next() {
		var i ListRequestEventsByRequestIDRow
		if err := rows.Scan(
			&i.ID,
			&i.RequestID,
			&i.EventKind,
			&i.ActorPrincipalID,
			&i.FromStatus,
			&i.ToStatus,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.ActorUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
