// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type InventoryAceEffect string

const (
	InventoryAceEffectAllow InventoryAceEffect = "allow"
	InventoryAceEffectDeny  InventoryAceEffect = "deny"
)

func (e *InventoryAceEffect) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = InventoryAceEffect(s)
	case string:
		*e = InventoryAceEffect(s)
	default:
		return fmt.Errorf("unsupported scan type for InventoryAceEffect: %T", src)
	}
	return nil
}

type NullInventoryAceEffect struct {
	InventoryAceEffect InventoryAceEffect `json:"inventory_ace_effect"`
	Valid              bool               `json:"valid"` // Valid is true if InventoryAceEffect is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullInventoryAceEffect) Scan(value interface{}) error {
	if value == nil {
		ns.InventoryAceEffect, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.InventoryAceEffect.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullInventoryAceEffect) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.InventoryAceEffect), nil
}

type InventoryItemKind string

const (
	InventoryItemKindFolder InventoryItemKind = "folder"
	InventoryItemKindVm     InventoryItemKind = "vm"
)

func (e *InventoryItemKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = InventoryItemKind(s)
	case string:
		*e = InventoryItemKind(s)
	default:
		return fmt.Errorf("unsupported scan type for InventoryItemKind: %T", src)
	}
	return nil
}

type NullInventoryItemKind struct {
	InventoryItemKind InventoryItemKind `json:"inventory_item_kind"`
	Valid             bool              `json:"valid"` // Valid is true if InventoryItemKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullInventoryItemKind) Scan(value interface{}) error {
	if value == nil {
		ns.InventoryItemKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.InventoryItemKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullInventoryItemKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.InventoryItemKind), nil
}

type InventoryRequestPowerAction string

const (
	InventoryRequestPowerActionPowerOn  InventoryRequestPowerAction = "power_on"
	InventoryRequestPowerActionShutdown InventoryRequestPowerAction = "shutdown"
	InventoryRequestPowerActionReboot   InventoryRequestPowerAction = "reboot"
	InventoryRequestPowerActionStop     InventoryRequestPowerAction = "stop"
)

func (e *InventoryRequestPowerAction) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = InventoryRequestPowerAction(s)
	case string:
		*e = InventoryRequestPowerAction(s)
	default:
		return fmt.Errorf("unsupported scan type for InventoryRequestPowerAction: %T", src)
	}
	return nil
}

type NullInventoryRequestPowerAction struct {
	InventoryRequestPowerAction InventoryRequestPowerAction `json:"inventory_request_power_action"`
	Valid                       bool                        `json:"valid"` // Valid is true if InventoryRequestPowerAction is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullInventoryRequestPowerAction) Scan(value interface{}) error {
	if value == nil {
		ns.InventoryRequestPowerAction, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.InventoryRequestPowerAction.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullInventoryRequestPowerAction) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.InventoryRequestPowerAction), nil
}

type PrincipalProviderType string

const (
	PrincipalProviderTypeActiveDirectory PrincipalProviderType = "active_directory"
	PrincipalProviderTypeProxmox         PrincipalProviderType = "proxmox"
	PrincipalProviderTypeSystem          PrincipalProviderType = "system"
)

func (e *PrincipalProviderType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PrincipalProviderType(s)
	case string:
		*e = PrincipalProviderType(s)
	default:
		return fmt.Errorf("unsupported scan type for PrincipalProviderType: %T", src)
	}
	return nil
}

type NullPrincipalProviderType struct {
	PrincipalProviderType PrincipalProviderType `json:"principal_provider_type"`
	Valid                 bool                  `json:"valid"` // Valid is true if PrincipalProviderType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPrincipalProviderType) Scan(value interface{}) error {
	if value == nil {
		ns.PrincipalProviderType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PrincipalProviderType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPrincipalProviderType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PrincipalProviderType), nil
}

type PrincipalType string

const (
	PrincipalTypeUser  PrincipalType = "user"
	PrincipalTypeGroup PrincipalType = "group"
)

func (e *PrincipalType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PrincipalType(s)
	case string:
		*e = PrincipalType(s)
	default:
		return fmt.Errorf("unsupported scan type for PrincipalType: %T", src)
	}
	return nil
}

type NullPrincipalType struct {
	PrincipalType PrincipalType `json:"principal_type"`
	Valid         bool          `json:"valid"` // Valid is true if PrincipalType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPrincipalType) Scan(value interface{}) error {
	if value == nil {
		ns.PrincipalType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PrincipalType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPrincipalType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PrincipalType), nil
}

type PublishedPodStatus string

const (
	PublishedPodStatusListed   PublishedPodStatus = "listed"
	PublishedPodStatusUnlisted PublishedPodStatus = "unlisted"
)

func (e *PublishedPodStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PublishedPodStatus(s)
	case string:
		*e = PublishedPodStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PublishedPodStatus: %T", src)
	}
	return nil
}

type NullPublishedPodStatus struct {
	PublishedPodStatus PublishedPodStatus `json:"published_pod_status"`
	Valid              bool               `json:"valid"` // Valid is true if PublishedPodStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPublishedPodStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PublishedPodStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PublishedPodStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPublishedPodStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PublishedPodStatus), nil
}

type RequestEventKind string

const (
	RequestEventKindSubmitted        RequestEventKind = "submitted"
	RequestEventKindApproved         RequestEventKind = "approved"
	RequestEventKindExecutionStarted RequestEventKind = "execution_started"
	RequestEventKindDenied           RequestEventKind = "denied"
	RequestEventKindExecuted         RequestEventKind = "executed"
	RequestEventKindExecutionFailed  RequestEventKind = "execution_failed"
	RequestEventKindCanceled         RequestEventKind = "canceled"
)

func (e *RequestEventKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RequestEventKind(s)
	case string:
		*e = RequestEventKind(s)
	default:
		return fmt.Errorf("unsupported scan type for RequestEventKind: %T", src)
	}
	return nil
}

type NullRequestEventKind struct {
	RequestEventKind RequestEventKind `json:"request_event_kind"`
	Valid            bool             `json:"valid"` // Valid is true if RequestEventKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRequestEventKind) Scan(value interface{}) error {
	if value == nil {
		ns.RequestEventKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RequestEventKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRequestEventKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RequestEventKind), nil
}

type RequestFamily string

const (
	RequestFamilyInventory RequestFamily = "inventory"
)

func (e *RequestFamily) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RequestFamily(s)
	case string:
		*e = RequestFamily(s)
	default:
		return fmt.Errorf("unsupported scan type for RequestFamily: %T", src)
	}
	return nil
}

type NullRequestFamily struct {
	RequestFamily RequestFamily `json:"request_family"`
	Valid         bool          `json:"valid"` // Valid is true if RequestFamily is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRequestFamily) Scan(value interface{}) error {
	if value == nil {
		ns.RequestFamily, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RequestFamily.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRequestFamily) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RequestFamily), nil
}

type RequestStatus string

const (
	RequestStatusPending         RequestStatus = "pending"
	RequestStatusApproved        RequestStatus = "approved"
	RequestStatusExecuting       RequestStatus = "executing"
	RequestStatusDenied          RequestStatus = "denied"
	RequestStatusExecuted        RequestStatus = "executed"
	RequestStatusExecutionFailed RequestStatus = "execution_failed"
	RequestStatusCanceled        RequestStatus = "canceled"
)

func (e *RequestStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RequestStatus(s)
	case string:
		*e = RequestStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for RequestStatus: %T", src)
	}
	return nil
}

type NullRequestStatus struct {
	RequestStatus RequestStatus `json:"request_status"`
	Valid         bool          `json:"valid"` // Valid is true if RequestStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRequestStatus) Scan(value interface{}) error {
	if value == nil {
		ns.RequestStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RequestStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRequestStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RequestStatus), nil
}

type AuthSessions struct {
	ID                  uuid.UUID          `json:"id"`
	PrincipalID         uuid.UUID          `json:"principal_id"`
	TokenHash           string             `json:"token_hash"`
	FamilyID            uuid.UUID          `json:"family_id"`
	ReplacedBySessionID *uuid.UUID         `json:"replaced_by_session_id"`
	UserAgent           *string            `json:"user_agent"`
	IpAddress           *string            `json:"ip_address"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	LastUsedAt          pgtype.Timestamptz `json:"last_used_at"`
	ExpiresAt           pgtype.Timestamptz `json:"expires_at"`
	RevokedAt           pgtype.Timestamptz `json:"revoked_at"`
}

type ClonedPods struct {
	ID              uuid.UUID          `json:"id"`
	PodID           uuid.UUID          `json:"pod_id"`
	UserPrincipalID uuid.UUID          `json:"user_principal_id"`
	FolderID        uuid.UUID          `json:"folder_id"`
	NetworkNumber   int32              `json:"network_number"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type FolderVmCapacityReservations struct {
	ID        uuid.UUID          `json:"id"`
	FolderID  uuid.UUID          `json:"folder_id"`
	VmCount   int32              `json:"vm_count"`
	Operation string             `json:"operation"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type InventoryRequests struct {
	RequestID       uuid.UUID                       `json:"request_id"`
	InventoryItemID uuid.UUID                       `json:"inventory_item_id"`
	PowerAction     NullInventoryRequestPowerAction `json:"power_action"`
	SnapshotName    *string                         `json:"snapshot_name"`
	CreatedAt       pgtype.Timestamptz              `json:"created_at"`
}

type PodDevNetworkAllocations struct {
	PodFolderID   uuid.UUID          `json:"pod_folder_id"`
	NetworkNumber int32              `json:"network_number"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type PublishedPods struct {
	ID                   uuid.UUID          `json:"id"`
	Title                string             `json:"title"`
	Slug                 string             `json:"slug"`
	Description          string             `json:"description"`
	ImageUrl             string             `json:"image_url"`
	Status               PublishedPodStatus `json:"status"`
	SourceFolderID       uuid.UUID          `json:"source_folder_id"`
	PublisherPrincipalID uuid.UUID          `json:"publisher_principal_id"`
	CloneCount           int32              `json:"clone_count"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type RequestEvents struct {
	ID               int64              `json:"id"`
	RequestID        uuid.UUID          `json:"request_id"`
	EventKind        RequestEventKind   `json:"event_kind"`
	ActorPrincipalID *uuid.UUID         `json:"actor_principal_id"`
	FromStatus       NullRequestStatus  `json:"from_status"`
	ToStatus         RequestStatus      `json:"to_status"`
	ErrorMessage     *string            `json:"error_message"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type Requests struct {
	ID                   uuid.UUID          `json:"id"`
	Family               RequestFamily      `json:"family"`
	Kind                 string             `json:"kind"`
	RequesterPrincipalID uuid.UUID          `json:"requester_principal_id"`
	ReviewerPrincipalID  *uuid.UUID         `json:"reviewer_principal_id"`
	Status               RequestStatus      `json:"status"`
	ReviewedAt           pgtype.Timestamptz `json:"reviewed_at"`
	ExecutionStartedAt   pgtype.Timestamptz `json:"execution_started_at"`
	ExecutedAt           pgtype.Timestamptz `json:"executed_at"`
	CanceledAt           pgtype.Timestamptz `json:"canceled_at"`
	ExecutionError       *string            `json:"execution_error"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type VmActionClaims struct {
	InventoryItemID  uuid.UUID          `json:"inventory_item_id"`
	Action           string             `json:"action"`
	ActorPrincipalID uuid.UUID          `json:"actor_principal_id"`
	ClaimedAt        pgtype.Timestamptz `json:"claimed_at"`
	Detail           *string            `json:"detail"`
}
