// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql/driver"
	"fmt"
)

type InventoryItemKind string

const (
	InventoryItemKindFolder InventoryItemKind = "folder"
	InventoryItemKindVm     InventoryItemKind = "vm"
)

func (e *InventoryItemKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = InventoryItemKind(s)
	case string:
		*e = InventoryItemKind(s)
	default:
		return fmt.Errorf("unsupported scan type for InventoryItemKind: %T", src)
	}
	return nil
}

type NullInventoryItemKind struct {
	InventoryItemKind InventoryItemKind `json:"inventory_item_kind"`
	Valid             bool              `json:"valid"` // Valid is true if InventoryItemKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullInventoryItemKind) Scan(value interface{}) error {
	if value == nil {
		ns.InventoryItemKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.InventoryItemKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullInventoryItemKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.InventoryItemKind), nil
}
