// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: vmactions.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const claimVMAction = `-- name: ClaimVMAction :one

INSERT INTO vm_action_claims (inventory_item_id, action, actor_principal_id, detail)
VALUES ($1, $2, $3, $4)
ON CONFLICT (inventory_item_id) DO NOTHING
RETURNING inventory_item_id, action, actor_principal_id, claimed_at, detail
`

type ClaimVMActionParams struct {
	InventoryItemID  uuid.UUID `json:"inventory_item_id"`
	Action           string    `json:"action"`
	ActorPrincipalID uuid.UUID `json:"actor_principal_id"`
	Detail           *string   `json:"detail"`
}

// ----------------------------------------------------------------------------
// VM action claims
// Durable serialization boundary for direct VM mutations.
// ----------------------------------------------------------------------------
func (q *Queries) ClaimVMAction(ctx context.Context, arg ClaimVMActionParams) (VmActionClaims, error) {
	row := q.db.QueryRow(ctx, claimVMAction,
		arg.InventoryItemID,
		arg.Action,
		arg.ActorPrincipalID,
		arg.Detail,
	)
	var i VmActionClaims
	err := row.Scan(
		&i.InventoryItemID,
		&i.Action,
		&i.ActorPrincipalID,
		&i.ClaimedAt,
		&i.Detail,
	)
	return i, err
}

const getVMActionClaim = `-- name: GetVMActionClaim :one
SELECT inventory_item_id, action, actor_principal_id, claimed_at, detail
FROM vm_action_claims
WHERE inventory_item_id = $1
`

func (q *Queries) GetVMActionClaim(ctx context.Context, inventoryItemID uuid.UUID) (VmActionClaims, error) {
	row := q.db.QueryRow(ctx, getVMActionClaim, inventoryItemID)
	var i VmActionClaims
	err := row.Scan(
		&i.InventoryItemID,
		&i.Action,
		&i.ActorPrincipalID,
		&i.ClaimedAt,
		&i.Detail,
	)
	return i, err
}

const releaseVMAction = `-- name: ReleaseVMAction :exec
DELETE FROM vm_action_claims
WHERE inventory_item_id = $1
`

func (q *Queries) ReleaseVMAction(ctx context.Context, inventoryItemID uuid.UUID) error {
	_, err := q.db.Exec(ctx, releaseVMAction, inventoryItemID)
	return err
}
