apiVersion: v1
kind: ConfigMap
metadata:
  name: kamino-config
  labels:
    app.kubernetes.io/part-of: kamino
data:
  PUBLIC_HOST: dev.placeholder.invalid
  GIN_MODE: release
  PORT: :8080
  FRONTEND_URL: https://dev.placeholder.invalid
  TRUSTED_PROXY_CIDRS: ""
  PROXMOX_INSECURE: "false"
  PROXMOX_INITIAL_SYNC_ENABLED: "true"
  PRINCIPAL_PROVIDER: active_directory
  PRINCIPAL_INITIAL_SYNC_ENABLED: "true"
  PROXMOX_AUTH_REALM: pve
  LDAP_INSECURE: "false"
  OTEL_ENABLED: "true"
  OTEL_SERVICE_NAME: kamino-api
  DEPLOYMENT_ENVIRONMENT: development
  OTEL_TRACE_SAMPLE_RATIO: "1"
  OTEL_K8S_CLUSTER_NAME: REPLACE_WITH_K8S_CLUSTER_NAME
