apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: kamino
  labels:
    app.kubernetes.io/part-of: kamino
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - dev.placeholder.invalid
      tls:
        httpsRedirect: true
    - port:
        number: 443
        name: https
        protocol: HTTPS
      hosts:
        - dev.placeholder.invalid
      tls:
        mode: SIMPLE
        credentialName: kamino-dev-tls
